### ISSUE TITLE
Add BSDF materials to Honeybee Radiance Materials

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#106]
Also RADToBSDF which can be used for complex fenestration.

PS: I can see how we are moving to apply 5 Phase method to Honeybee soon!

**Comment by basdav** [comment]
Hi, sorry for invading this post...
I just have a question regarding your answer of about 2 years ago... is that possible already to use 3-5 Phase Method in honeybee?...  I see that the use of BSDF is implemented but maybe only availabe for point in time simulations? I'm soon-to-be user of Honeybee, so at the moment just exploring the software capabilities... 
I'll appreciate your reply... thanks in advance.
Chantal.

**Comment by mostaphaRoudsari** [comment]
Hi @basdav! not yet. 3-5 phase is one of the most delayed features for our development. Keep an eye to the new [honeybee repository](https://github.com/ladybug-analysis-tools/honeybee). We're working on it.
