### ISSUE TITLE
Wish - Window Layout

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/Honeybee#111]
Hi guys

This will be my last wish before my holidays, and you will get rid of my comments for a while ;)

I have earlier with native component tried to automate different window layouts when studying facades. Previously I have done this with COMFEN. It works okay, but I want to have the flexibility Honeybee and Ladybug have, when I am studying different facade and room designs. Further it could be great with more control over window width, height, numbers etc. I know it mainly would have an influence on the daylight results. 

Is it something that fits into the Honeybee idea? I think this kind of component could be quite cool!

![honeybee_wish_window-layout-01](https://cloud.githubusercontent.com/assets/7299731/3558851/aae5c9e8-0941-11e4-8cd3-467cfcbfc238.JPG)

**Comment by arkdanielnielsen** [comment]
I have tried a workaround with double horizontal windows with isotrim (4). The strange thing is that isotrim flips (pt1) one of the 8 circular placed shoebox's. First I though it just was the shading that were flipped but the energy result is different than the other because the ext wall turning inside. I have tried to flip the wrong one but that does not help. 
I have experienced it before with a circular building. It seems to happen when something is circular or placed circular. But it is depending, in this case, of the facade width and no. of rotated SB's. If I change from 5m to 5.1 then all is fine or from 8 SB to 7. 
Maybe it is not the right place to post this, but I think it could also have something to do how the HBzones is created?
5) all other 7 SB is ok!
2) shade
3) window
![honeybee_glazing-01](https://cloud.githubusercontent.com/assets/7299731/6064518/d4001240-ad5e-11e4-8196-0f7ecfd5ebfe.JPG)

**Comment by mostaphaRoudsari** [comment]
Hi @arkdanielnielsen, I wonder if this happens for a similar reason as this #271. As far as I remember we are checking all the normal directions for child objects to match the parent surface. If you can post the file it will be much easier for us to track down the issue.

**Comment by arkdanielnielsen** [comment]
Hi
See linked file with both the window prob and the one about not created constructions. Hope it is okay to post both issue in one file because it is in the same gh it happens. This gh is just reduced component file.
https://www.dropbox.com/s/asap9lcow2ismgp/Honeybee_Flipped-Srf-probs_%2B_Constructions-probs.gh?dl=0
It is a "shoebox" study with 8 different orientations in one file. A initial preso like this:
![honeybee_roompreso](https://cloud.githubusercontent.com/assets/7299731/6097682/4c115324-afc7-11e4-9ac7-a81d12a42204.JPG)

**Comment by chriswmackey** [comment]
@arkdanielnielsen ,
I am sorry that this has taken so long but I can, at last, say that all 4 of your cases can be created with the newest glazingByRatio component that I committed ().

Here are all 4 of your cases:
![daniel cases](https://cloud.githubusercontent.com/assets/5567574/8760824/62754a48-2cff-11e5-86ee-a942febc36b6.PNG)

Here's the new component:
![newglzcomp](https://cloud.githubusercontent.com/assets/5567574/8760825/66444278-2cff-11e5-9e7e-34c3e2019c6e.PNG)

And here is the GH file showing you how to make all of them, including the last one, which can be made using the new splitGlzVertDist_ input.
https://www.dropbox.com/s/kvccdw2bqw56fku/DanielCases.gh?dl=0

I hope that having this last option of splitting the windows vertically will encourage more people to go for it out in practice.  It really seems to be the best performing in allowing daylight up high while still using a restrained glazing ratio with views to the outdoors.  Finally, I have also realized that it can be really good for buoyancy driven ventilation if both bottom and top windows are made operable.

Enjoy!
-Chris

**Comment by antonszilasi** [comment]
@chriswmackey  Chris I've noticed that when you pass a honeybee zone into this component the component will remove all previous glazing. This can be tricky sometimes, could we add some functionality so that previous glazing won't be removed when only skylights need to be added? Perhaps I can just add another tab that allows that?

**Comment by chriswmackey** [comment]
@antonszilasi ,
Yes, that sounds useful.  This component was also up for being split into two components:
https://github.com/mostaphaRoudsari/Honeybee/issues/449
If you want to take a stab at this, I trust you.  Otherwise, I'll get to it before the next stable relase.
-Chris
