### ISSUE TITLE
Energy Values Out of E+ Simulation Are Wrong If Rhino Model Units Are Inches

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#122]
I discovered that, if I have a Rhino Model in inches, I get absolutely bogus numbers for energy use out of the E+ simulation.  I ran the same geometry and GH file in a Rhino Model in Inches and then a Rhino model in meters.  Considering that I am simulating a small box that is 2m x 2m x 1m, I know that the inches model is wrong.  Here are two images of the heating load in inches and then meters.

![heating units in imperial](https://cloud.githubusercontent.com/assets/5567574/3592695/e7bdda54-0c75-11e4-92b5-1f05dcc8cb79.PNG)
![heating units in si](https://cloud.githubusercontent.com/assets/5567574/3592698/ec991688-0c75-11e4-95cb-9192cfbee79e.PNG)

Here's the GH file for the model that was run in inches:
https://www.dropbox.com/s/j5u3gwl2pofw9w7/EnergyModel.gh

Here's the GH file for the model that was run in meters:
https://www.dropbox.com/s/pi85jkfkd1l23cx/EnergyModel2.gh

The are the same with the exception of the internalized geometry.

**Comment by mostaphaRoudsari** [comment]
I added a warning for this for now so it doesn't let the user to run the analysis until we have it work in both units.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Now that we have the warning and the other issue about units, I am closing this one out.
-Chris
