### ISSUE TITLE
Add system names as an input

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#130]
@chiensiTB I think I need an example for this. Do you want to add a separate name for each system? What is the limitation with the current methodology?

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Can you clarify whether this issue is still relevant?  Right now we have a separate name for each system, no?  Is this an alternative workflow that you are thinking about here?
-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey I don't it is anymore. I'm closing this.
