### ISSUE TITLE
Add DOAS system with radiant

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#132]
I'm not sure if it helps but there is a measure for that on BCL.

**Comment by chriswmackey** [comment]
This will also be implemented over the next few days following this plan:
https://github.com/mostaphaRoudsari/Honeybee/commit/e76331052179231569dbe573d2b54231230514d1

**Comment by chriswmackey** [comment]
This is done!!! Woohoo!!!!
https://github.com/mostaphaRoudsari/Honeybee/commit/ab2df53a7090e83d64f0e396ae7d364110886a3a

**Comment by mostaphaRoudsari** [comment]
Great job @chriswmackey!
