### ISSUE TITLE
Add DOAS system with chilled beam

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#133]
There is a measure for this one too.

**Comment by chriswmackey** [comment]
I'm going to put a template in for this over the next few days following the plan I have laid out here:
https://github.com/mostaphaRoudsari/Honeybee/commit/e76331052179231569dbe573d2b54231230514d1
.. that is, unless someone says thinks otherwise.

**Comment by chriswmackey** [comment]
Done!
https://github.com/mostaphaRoudsari/Honeybee/commit/ddae852af5da3895f86eb7c9a144b7dfcffcdcde
