### ISSUE TITLE
Add a component to read system related outputs - so we can use them also for visualization

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#135]
@chiensiTB what are the outputs that you think we should have as outputs:

1. Chiller power
2. Chiller load
3. ?

**Comment by chriswmackey** [comment]
@mostaphaRoudsari and @chiensiTB , if you produce a stable version of the OpenStudio component for the upcoming release, I will ensure that my result readers can handle the output of the OpenStudio component (in addition to the result readers that you have been working on @chiensiTB ).  Let me know your thoughts on this soon.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey I have this on my list for this week (). Will let you know once ready!
https://github.com/mostaphaRoudsari/Honeybee/issues/241

**Comment by chriswmackey** [comment]
Ok.  Sounds good.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari and @chiensiTB ,

Is this issue still relevant now?   You can import the system-level results of two systems with the read EP result and we have the basic SQL reader now.    I can see that we should develop out the SQL one more but the development of it seems a bit frozen on my end with the PINVOKE error.

-Chris

**Comment by chriswmackey** [comment]
All system-level results of OpenStudio systems can now be imported with the ReadEPResult component and so I think this issue is close-able.  Please re-open if you disagree.
