### ISSUE TITLE
Wish - "Honeybee_Color Zones by EP Result"

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/Honeybee#153]
Hi @chriswmackey 
The "Honeybee_Color Zones by EP Result" and "Honeybee_Color Surfaces by EP Result" are really cool! To make them even more cool is the following wishes:
![honeybee_zonecolor-01](https://cloud.githubusercontent.com/assets/7299731/3903810/c5593b04-22d0-11e4-8d08-a9e32a330571.jpg)
There is maybe also a bug (4) !?

**Comment by chriswmackey** [comment]
@arkdanielnielsen ,
There are a lot of things discussed on this issue and I always have to read through it all to find out what the remaining requests are.  As such, I am closing this one out and making two issues for the remaining things that need to get done:
https://github.com/mostaphaRoudsari/Honeybee/issues/156
https://github.com/mostaphaRoudsari/Honeybee/issues/358
-Chris
