### ISSUE TITLE
Add functionality to OpenStudio to use csv files for schedule

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#161]
For the record this is how I did in EnergyPlus component. We create a schedule:file object based on csv input and then assign it to the zone.

https://github.com/mostaphaRoudsari/Honeybee/blob/master/src/Honeybee_%20Run%20Energy%20Simulation.py#L700-L757

I assume there should be an API call for this in OpenStudio. @macumber is it?

**Comment by macumber** [comment]
Related issue in OpenStudio https://github.com/NREL/OpenStudio/issues/50

**Comment by chriswmackey** [comment]
@macumber and @mostaphaRoudsari ,

I have added a work-around in Honeybee for this by writing CSV schedules into the IDF after OpenStudio outputs the IDF.  I know that this solution is far from elegant but the CSV schedules are such a critical part of the application of Honeybee, since the visual scripting interface is very conducive to schedules input as lists, that the workflow is almost unusable for me without this CSV capability.  

@macumber , let me know if this CSV capability is a feature that is planned for the near or far future and I can plan a timeline for rolling back my work-around accordingly.

-Chris

**Comment by macumber** [comment]
We will be working on refactoring the OSM file structure for OpenStudio 2.0 this year.  One of the main concerns here is to better define the file structure of OSMs so it is easier to find files associated with the OSM.  This should make it easier to reliably use CSV for input.  So I would say it is on the ~ 1 year time frame.

**Comment by chriswmackey** [comment]
Awesome.  Thanks for letting me know, @macumber !

**Comment by chriswmackey** [comment]
I think that I should readdress this issue for the time being with an implementation of compact schedules.  @AntonelloDN 's components offer a good opportunity for this.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey [here](http://bigladdersoftware.com/epx/docs/8-0/input-output-reference/page-009.html#scheduledayhourly) is the EnergyPlus object that I mentioned. You can parse the csv schedule and create daily schedules which can be used to create weekly schedules and so on. Using these objects you can have a single function that will work for any csv schedule. It should work well with @AntonelloDN's development.

**Comment by chriswmackey** [comment]
Awesome!  Thanks Mostapha.  This will be useful.

**Comment by chriswmackey** [comment]
Given that we now have [components to write schedules in the format that OpenStudio likes](https://github.com/mostaphaRoudsari/Honeybee/commit/d0c1b110bd2a9237d089298c46fe54aff8f33a45) and that we have [a workaround if someone really needs to use a CSV schedules with OS-generated IDFs](https://github.com/mostaphaRoudsari/Honeybee/blob/master/src/Honeybee_Export%20To%20OpenStudio.py#L2879-L2912), I am going to close out this issue for the time being.  I also wrote a [workaround for adding Holidays to the OS-generated IDF](https://github.com/mostaphaRoudsari/Honeybee/blob/master/src/Honeybee_Export%20To%20OpenStudio.py#L2926-L2929) , which should cover all of our bases until the new schedule features are implemented in OpenStudio.

I'll keep my eye out for when these features are implemented in OS and switch over to using the OS SDK once they are there.

-Chris
