### ISSUE TITLE
gbXML Export Fail and OpenStudio Not Understanding the Presence of the Latest Libraries

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#170]
Hi @chiensiTB ,

One of our users, @jacoposartore has been having a hard time getting grizzly bear and the openstudio components to work and I have had similar difficulties.  Particularly, Grizzly Bear is saying that my gbXML folder does not exist when it does:

![image](https://cloud.githubusercontent.com/assets/5567574/4033553/c04fcb72-2c7c-11e4-86fb-b2f69d90b233.png)

![image](https://cloud.githubusercontent.com/assets/5567574/4033592/2bb254d4-2c7d-11e4-89df-78f0347eb215.png)

Also, the openstudio exporter is telling me that I do not have the latest version of the OpenStudio Libraries when I just updated them a few minutes ago.
![image](https://cloud.githubusercontent.com/assets/5567574/4033625/60c338f0-2c7d-11e4-9747-52b2dfdacbea.png)

The GH file with the above errors can be found here:
https://www.dropbox.com/s/yn5puorlz6q903p/OpenStudio%2BgbXML%20_1Room_CWM.gh?dl=0

@chiensiTB , if you could shed some light on what is going on here, that would be awesome.  Also @jacoposartore, please add anything that I forgot.

**Comment by macumber** [comment]
@mostaphaRoudsari @chiensiTB are you guys still having this issue?

**Comment by mostaphaRoudsari** [comment]
@macumber I still do have the issue. Do you want me to try it with the new version of OpenStudio?

**Comment by mostaphaRoudsari** [comment]
This is [potentially] a good news! I downloaded OpenStudio1.8.0 today and tested the libraries and it worked with no issues on my machine. @chriswmackey and @chiensiTB can you guys also try and let me know. This can be a great news for all of us. The development for OpenStudio has been on hold for awhile because of this issue.

**Comment by mostaphaRoudsari** [comment]
I'm closing this issue as this is duplicate with this one (https://github.com/mostaphaRoudsari/Honeybee/issues/214). Please leave your comments in the other issue.
