### ISSUE TITLE
Give a warning for rotated Honeybee Objects - 

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#183]
Or should I update the data for the geometry and coordinates at the last minute. I can check both approaches.

**Comment by chriswmackey** [comment]
This issue will be partially addressed once this is implemented:
https://github.com/mostaphaRoudsari/Honeybee/issues/373

**Comment by mostaphaRoudsari** [comment]
http://www.grasshopper3d.com/group/ladybug/forum/topics/modeling-high-rise-buildings-in-hb?commentId=2985220%3AComment%3A1392588&groupId=2985220%3AGroup%3A658987
