### ISSUE TITLE
Add time-out to version check so in case user has a firewall it doesn't take so long to let Honeybee fly

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#185]
http://www.grasshopper3d.com/xn/detail/2985220:Comment:1142010

**Comment by Vyrwn** [comment]
Hi Mostapha,

Do you have any update on this issue? I have been checking since October but did not want to bother you since you seem to be updating a lot of stuff in the code. I was wandering if you are going to address this issue since it has become a bit irritating for me to wait 2-3 mins every time I use Honeybee-Honeybee behind corporate Firewall, and I do that quite often every week.

I will be looking forward to this.

thank you very much for all the tools you have provided and for the constant work you and your team is conducting.

Byron

**Comment by mostaphaRoudsari** [comment]
Hi @Vyrwn, Thank you for sending the reminder. If you can help me with testing we can get this fixed before the next release next week? Does it sound good to you?

**Comment by Vyrwn** [comment]
Hi Mostapha,

yes of course i would be happy to help.

**Comment by mostaphaRoudsari** [comment]
Ok. Here we go! Please try this file and let me know if it is fine. It should only wait for 10s and then just ignore the version check: https://www.dropbox.com/s/w9qeuzuf551wm3q/timeout_and_download_issues.gh?dl=0

PS: Sorry for the delay! I'm not traveling for the next few days so I can get back to you pretty fast. Let's get this fixed!

**Comment by Vyrwn** [comment]
Hi Mostapha,

thank you very much for looking into this problem. Well I just loaded the file you sent me, but unfortunatelly it does not seem to change something. Loading is still taking too long.

Ladybug_Ladybug is working fine as you had fixed it in previous fix, but Honeybee_Honeybee takes about 5-7 minutes.

**Comment by Vyrwn** [comment]
update!

I isolated the Honeybee_Honeybee component from the file you sent me and it droped loading time significantly, but still it took 172 seconds.

**Comment by Vyrwn** [comment]
Hi Mostapha,

I set everything into False in CheckForUpdates line (LB=False, HB=False etc). And it still fails to load faster than 3 minutes. Wouldnt that mean that the problem is not with the update attempt?

I am just trying stuff, maybe they are not very helpful, just trying to help from my end.

**Comment by Vyrwn** [comment]
it seems that some of the dropbox links are being blocked by the firewall.

**Comment by mostaphaRoudsari** [comment]
@Vyrwn thanks for checking. Can you please try this new file? https://www.dropbox.com/s/0bitdduywpgvycu/downloading_issues.gh?dl=0

I made couple of changes which I hope solve the issues. Set the Boolean to True and let's see how long does it take for component to download the files and print out the numbers. The component assumes you have a folder as c:\ladybug already created on your system.

**Comment by Vyrwn** [comment]
it run instantly but came back with error

1. Solution exception:The remote server returned an error: (407) Proxy Authentication Required.
2. Traceback: line 9, in script

i do have a c:\ladybug created with all the files needed.

**Comment by Vyrwn** [comment]
i rerun it and now it worked... 

0. 0.696144104004 1421864222.69

**Comment by mostaphaRoudsari** [comment]
Great news! so I just need to catch the exception in cases that it may fail and give a warning to download it manually. I will send you the link once I have the components updated. Thanks

**Comment by Vyrwn** [comment]
thank you very much. I will be waiting,
