### ISSUE TITLE
RunEnergySimulation - No results if there's a space in the EPW's path.

### ISSUE THREAD

**Issue by Sfix** [mostaphaRoudsari/Honeybee#189]
No results with Honeybee_ Run Energy Simulation (RunEnergySimulation) if there's a space in the path for the EPW (Mine is at "F:\NSfix\Work\Countries\USA\Weather Data\USA_MD_Baltimore.724060_TMY2.epw") 

Solution that has worked for me is to add " before and after the file in the .Bat . To do so I have modified the line 828 to
      '\\Epl-run ' + fullPath + ' ' + fullPath + ' idf "' + epwFileAddress + '" EP N nolimit N N 0 Y'

(WriteBatchFile of class RunIDF . Assignment of batchStr)

**Comment by mostaphaRoudsari** [comment]
Thanks @Sfix! I added the change for the new release.
