### ISSUE TITLE
searchEPConstruction & Underground wall

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#199]
Hi,
Wanted to report that the surfaceType  + Underground wall input in the component is not accepting the value in the hint (0.5). It says:
1. 0.5 is not a valid surface type.
Also there is a typo in the hint: UNDERGOUNDWALL (R missing)

**Comment by mostaphaRoudsari** [comment]
Abraham (@ayezioro ), the reason that you cannot fine undergorund wall construction is that there is no construction with that name.
@chriswmackey I modified the component and kept the new input that you added. It looks pretty useful and I liked how you merged two inputs into one as keyword:

![image](https://cloud.githubusercontent.com/assets/2915573/5895207/533cfd42-a4e6-11e4-88d4-476d5c7565b7.png)
