### ISSUE TITLE
EnergyPlus 8.2 compatible !?

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/Honeybee#203]
Hi
I want to know if it is possible to use EP 8.2 with Honeybee before I try to install it. Have any of you seen this: http://autodesk.typepad.com/bpa/2014/10/energyplus-raised-to-the-power-of-cloud.html
Probably you have. I wanted to try it and generate the model from Honeybee for that.
/daniel

**Comment by mostaphaRoudsari** [comment]
Based on the webinar today! No hourly results. No custom variables - 

![image](https://cloud.githubusercontent.com/assets/2915573/6132291/8c26d930-b11f-11e4-80b7-8b7e6747123d.png)

**Comment by ayezioro** [comment]
Yes, but this is only in the Cloud version not the local computer.

**Comment by mostaphaRoudsari** [comment]
Hi Abraham. You are right. This is a discussion inside discussion now. I copied the image for cloud connection and not moving to 8.2.

**Comment by ayezioro** [comment]
Hi Mostapha,
For my not HB simulations i test-moved to 8.2 (the last release, which make improvements in simulation time). No problems so far. Results are consistent with 8.1.  So we are about to move to this release in our software (... soon).
-A.

**Comment by mostaphaRoudsari** [comment]
Great to know. What do you think is the best approach to move to 8.2 then? Do you have an example of Honeybee files in both versions. I want to run a text differ to realize what objects are changed in the new version.

**Comment by chriswmackey** [comment]
Hey guys,
Just to add another point: it seems that a user with 8.2 was able to run the IDFs generated by HB through E+ 8.2 if they opened EPLaunch:
http://www.grasshopper3d.com/group/ladybug/forum/topics/thoughts-on-bouancy-driven-natural-ventilation?commentId=2985220%3AComment%3A1207131&xg_source=msg_com_gr_forum
(see the end of the discussion)
Hopefully, this means that we don't need to change much to cross over from 8.1 to 8.2.
-Chris

**Comment by ayezioro** [comment]
Yes. What I've found is that the only change to do is the version number :-)
But if you have a complex file you can run the updater in the EPLaunch and compare.
-A.

**Comment by mostaphaRoudsari** [comment]
I updated Honeybee_Honeybee and RunEnergySimulation components. Now they should work with EP8.1 or EP8.2 - Please give it a try and let me know if you find any bugs. Closing this...

**Comment by ayezioro** [comment]
Running well. The OpenStudio component is still running 8.1. They don't support 8/2 yet?

**Comment by mostaphaRoudsari** [comment]
Nice! Back to OpenStudio we have major issues importing recent versions of OpenStudio which is using 8.2 so we had to keep using the old version which is compatible with 8.1 > See #214
