### ISSUE TITLE
Example file for OpenStudio HVAC systems

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#222]
@chiensiTB if you have an example file, Kristoffer is interested to take. He also offered to clean it and share it back. You can read more here: http://www.grasshopper3d.com/xn/detail/2985220:Comment:1177226

**Comment by chiensiTB** [comment]
Sorry guys.  I hope that my videos have served their purpose.  Is this ok to close?

**Comment by mostaphaRoudsari** [comment]
We  can close this but there is one here that needs help and has been open for sometime:
http://www.grasshopper3d.com/group/ladybug/forum/topics/advanced-systems-setup?commentId=2985220%3AComment%3A1324495&groupId=2985220%3AGroup%3A658987
It is great to have you back! :)

**Comment by chiensiTB** [comment]
Ok, will do.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey [has already addressed](https://hydrashare.github.io/hydra/index.html?keywords=HVAC) this on Hydra
