### ISSUE TITLE
Decompose Zone should output Honeybee objects and not Breps

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#235]
http://www.grasshopper3d.com/group/ladybug/forum/topic/show?id=2985220%3ATopic%3A1181819&xg_source=msg

**Comment by mostaphaRoudsari** [comment]
This needs a little bit more thinking. In a way maybe it is not a good idea... What should we do for child surfaces in this case? What are your thoughts on this @chriswmackey?

For now I remove this from January release.

**Comment by chriswmackey** [comment]
Hi @mostaphaRoudsari ,
I definitely sympathize with not doing this for the January release.  What do you currently do with child surfaces for the DecomposeHBZone component?  Are they not included?
Also, I realized that we would not be able to use punched geometry for the windows surfaces so I agree that the decompose based on type component should stay the way that it is.  Would it be a bad idea to suggest that the DecomposeHBZone component have separate outputs based on surface type?  They would not have to be as numerous as the decompose based on type component.
-Chris

**Comment by mostaphaRoudsari** [comment]
Thanks @chriswmackey! Sounds like a good idea. I think outputs will be similar to what DecomposeHBZone used to be.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
It seems like this one was fixed a LONG time ago.  I'm closing it!
-Chris
