### ISSUE TITLE
Honeybee fails to generate window

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#237]
Haven't checked it yet. Reported by one of the users: http://www.grasshopper3d.com/xn/detail/2985220:Comment:1186903

**Comment by chriswmackey** [comment]
I provided an answer here:
http://www.grasshopper3d.com/group/ladybug/forum/topics/the-problem-of-daylight-simulation?commentId=2985220%3AComment%3A1186903&groupId=2985220%3AGroup%3A658987
@mostaphaRoudsari , if this sounds satisfactory, can we close out the issue for the time being?

**Comment by mostaphaRoudsari** [comment]
:+1:
