### ISSUE TITLE
Default HAVC Ideal Loads Template

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#238]
@chriswmackey let's talk about the new HVACTemplate that you defined for EP component once we meet. We talked about this once before on one of your projects and here is another discussion: http://www.grasshopper3d.com/group/ladybug/forum/topics/monthy-load

I'm not sure how you came up with the schedules but, as a general rule, it is really tricky to define some default schedules and controls without giving the users access to overwrite it. Reminds me of some of the other developments ;) If we are making changes to default EP Template we should be crystal clear about it otherwise let's stick to the default template. :melon:

**Comment by chriswmackey** [comment]
@mostaphaRoudsari , we has a talk about this yesterday and I have finished implementing the old template. It has been put back in the same way that you had it with one key exception:  in your old template, you did not have the ideal air system connected to the outdoor air object.  This causes the model to not react when you change the ventilation per person or ventilation pera area.  I took this as an error and ensured that your old Ideal Air template was connected to the outdoor object.  However, when this happened, E+ demanded that I include an object for sizing periods.  Accordingly, I added two objects that size the system based on the extreme hot and extreme cold days of the weather file.  Now, before E+ runs the whole simulation, it does a sizing calculation (like OpenStudio) and this seems to ensure more accurate results.

I also added in the ability to control a lot of features of the ideal air system, including heat recovery, demand controlled ventilation, and air side economizers.  I was originally putting this all in the "Set Zone Thresholds" component but the component became too large and a lot of the inputs did not seem to fit in the zone thresholds component.  Accordingly, I moved them to a new one.

Let me know your thoughts and I believe that, for now, we can consider this issue closed.
