### ISSUE TITLE
Create blind moves the blinds in the wrong direction

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#240]
If the user change the angle of the blind and then put a number for distance from glass it moved the blinds in the wrong direction. Try angle -90.

**Comment by chriswmackey** [comment]
This is now fixed!
![shadesfixed](https://cloud.githubusercontent.com/assets/5567574/5694613/7bb19924-993b-11e4-951d-5dba8f6651c2.PNG)
