### ISSUE TITLE
Q - applying EP Construction

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/Honeybee#245]
What is a good setup now when the "Search EP Construction" does not have same functionalities as the old from 29. of July?
![honeybee_epconstruction-01](https://cloud.githubusercontent.com/assets/7299731/5851293/637b0ca0-a205-11e4-8058-256ec6c50b7d.JPG)

**Comment by mostaphaRoudsari** [comment]
@arkdanielnielsen see #199. They are temporarily gone and will be back soon.

**Comment by mostaphaRoudsari** [comment]
@arkdanielnielsen the new component should do what you are looking for and also has the keyword input that Chris has added to the old version! Please give it a try and let me know if you have any issues.

![image](https://cloud.githubusercontent.com/assets/2915573/5895177/624fd15c-a4e5-11e4-9ec3-bc6364930dfc.png)

**Comment by chriswmackey** [comment]
@mostaphaRoudsari,
What always confused me about the version that you have up there is that I never understood what my options were for surfaceType. I expected to be able to put in numbers for ground floor, ceiling, interior wall, etc. like the HBSrfs component. Instead I was getting results of climate zones that corresponded to the numbers that I input for surfaceType. Can you write clearly what the inputs are suposed to be in the description of surfaceType or change it back to "keyword," which it seems to really be as far as I understand it in the code.

**Comment by chriswmackey** [comment]
Ah.  Ignore my last comment, @mostaphaRoudsari .  I see that the description of surfaceType includes the 5 viable options.  All looks good and sorry about that.
