### ISSUE TITLE
Add in the Ability to Separately Change Heating + Cooling HVAC Availability

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#246]
As per this email discussion:

Now the problem is how to stop the boiler (from 15 apr - 15 oct) and the chiller (1 jan - 15 apr & 15 oct - 31 dec). I've tried with the setpoint schedules to stop it but it seems that the boiler is on summer and the chiller is on in winter. The results are not trustable for chilling, I will check the file better to understand what's on!

**Comment by mostaphaRoudsari** [comment]
@chriswmackey can you elaborate a little bit more here. As far as I understand the system should work fine even without setting up availability. We need a sample file for this.
cc: @chiensiTB and @antonszilasi I wonder if you guys have any inputs on this.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I know that the ideal air system template that we use allows you to set availability schedules in 3 different ways:
1) Availability of the entire HVAC system
2) Availability of Cooling
3) Availability of Heating

I have implemented the firs one on the Set EnergyPlus Zone Schedules component but not the separate availability of cooling and heating.

I found a user who wants to shut off cooling availability in winter since they find it weird that, in an office setting with a lot of heat gains, the AC will be running in the middle of winter.  The want to see what will happen if cooling is not available in the winter.

**Comment by mostaphaRoudsari** [comment]
Thanks @chriswmackey. That makes sense but my question is why the cooling system turns on during the winter? Is it because indoor temperature reaches the setPt (because of too much internal gains + solar gain + ...) or is it because something is going wrong in the model? If it is the second case then we want to delve more into the model and see what is exactly going on.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I am pretty sure that it is because of the former (because of too much internal gains + solar gain + ...).  I would not say that the model is wrong.  Just that the HVAC system is doing what we tell it to do, which is to cool the space down any time that the zone temperature goes above the cooling setpoint (no matter the time of year).

**Comment by chiensiTB** [comment]
Most likely the reason that there is cooling in the winter is because there is no airside economizer to offset the internal gains.  Or if there is an airside economizer, it is set up incorrectly.  That would be my guess.  It would be wrong to shut off cooling, because that isn't how a building would really work.  This is one reason why using ideal air loads has never been the right way to model. @mostaphaRoudsari  and @chriswmackey you maybe will have to take an energy modeling session from me.  I'll trade you if you want to teach me more about trees and attractors.

**Comment by chriswmackey** [comment]
@chiensiTB ,
I have been meaning to ask you about air-side economizers.  I have given users the option of including  or excluding the air side economizer on the ideal air system with a new  "Set Ideal Air Loads Parameters" component.  However, I know that most people are probably not going to use this and they are just going to go with the defaults.  Right now, the default is not to have an air side economizer but I was wondering if, in practice, every building today basically has an air side economizer, in which case, I should probably include it by default.

The reason for the HVAC schedules is separate from the air side economizer.  Someone was imagining having their building with a "summer mode" and "winter mode," which is something that I have experienced in some new buildings.  It makes sense to me because, in certain parts of the year, there is no need to run a heating system even if the temperature is below the heating setpoint since the temperature is barely below the setpoint and, within a few hours, the space will probably be warm enough again.

I would love to trade knowledge of data trees for some HVAC knowledge.
-Chris

**Comment by mostaphaRoudsari** [comment]
@chiensiTB Trade knowledge of data sounds great to me. I love to do it. Just please let's set it up after the end of February!

**Comment by ayezioro** [comment]
Can i just assist this trade fair as a free listener? :-)
I was about to ask about this seasonal Heating/Cooling issue, but i see that the last word hasn't said.
Also i wanted to ask/request about controlling the relative humidity using IdealLoadSystem.
I use the Humidstat control for that, but i don't thing HB is using it (or any) for this system.
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
The humidity deserves its own issue and I have just created one:
https://github.com/mostaphaRoudsari/Honeybee/issues/360

-Chris

**Comment by chriswmackey** [comment]
These capabilities now exist with the new HVAC implementation and so I am closing out the issue.
