### ISSUE TITLE
Make sure set construction supports all surface types

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#256]
There are multiple types missing!
![image](https://cloud.githubusercontent.com/assets/2915573/5986355/e5095c2c-a8c2-11e4-92bc-d9e655ee5244.png)

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I think that one other component to change constructions related to the ground/floor (underground, ground floor, and exposed floor) should do the trick.  I think that I might prefer this to adding more inputs to the current components.  What do you think?
-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey I like that idea. It will be cleaner that way. :+1: I will add a new component.
