### ISSUE TITLE
Add a new component to setEPConstruction in level of surfaces

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#257]
Mainly useful with explodeHBZone so it allows the user the change construction for a single or number of surfaces.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
How would this be different from passing the surface through a createHBSrfs component?
I know that, technically, the createHBSrfs component will overwrite any previous properties of the surface and I can imagine that this new component will not do this but I can't think of any case where overwriting would be that much of an inconvenience.  Also, when you go to recombine the surfaces back into a zone, you will essentially be overwriting your old zone and it's properties anyway.  I guess that I am just saying that, if you go with this route, you should make a "recombineHBZone" component to bring back the old zone and its properties from the surfaces.
Also, let me know if I am misunderstanding.
-Chris

**Comment by mostaphaRoudsari** [comment]
You are right but there is one specific case (which is actually a common case) that this process will make it much easier/cleaner to make construction changes and that's when you have a child surface with the parent surface. Imagine if I want to change the window construction for the wall facing west and then put them back together. Right now just because of that you won't be able to use mass to zone component and need to set it up surface by surface which is a pain. Do you agree on this use case?
![image](https://cloud.githubusercontent.com/assets/2915573/5988420/2cb77fa8-a92d-11e4-81c6-2136b55bce86.png)

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

I see now how it is useful and how it will make window assigning nicer.

Go for it!
-Chris

**Comment by mostaphaRoudsari** [comment]
8edb1a79955b15ce47c3c887ef8548ceca328004
