### ISSUE TITLE
HB_runEnergySimulation error message

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#260]
Hi,
Just downloaded the updated version and i get this error message in the HB_runEnergySimulation component:
1. Solution exception:'EPZone' object has no attribute 'internalMassNames' 
Thanks,
-A.

**Comment by ayezioro** [comment]
I commented the lines, 1140-1147, to overcome the problem. The simulation runs but now the problem is transferred to the HB_readEPResult:
1. Solution exception:index out of range: 0
Happening at line 459.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
You are using the version of Run Energy Simulation that I forgot to put the compatibility check in:
https://github.com/mostaphaRoudsari/Honeybee/issues/252

Update everything (including HB_HB and the result reader) to the most recent version.

@mostaphaRoudsari , man, I really have to change the compatibility every time I commit.  If I change a component that is dependent upon a component that had to have an updated HB_HB compatibility check, I have to change the compatibility.  I am just going to do this every time here on out.

-Chris

**Comment by mostaphaRoudsari** [comment]
Hi Abraham, let us know if updating again solves the issue. The latest Honeybee_Honeybee has on input for default folder.
 
@chriswmackey sounds good to me!

**Comment by ayezioro** [comment]
Hi Mostapha and Chirs,
Unfortunately is not working. I updated everything today 2-3 times :-)
The EnergySimulation is ok now but the EPReadResults (dated Jan 30 2015) is not. The same error as above. Restarted the machine, the program but no help.
Added the default folder location, even though there is no need for it, in my case.
Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
Thanks Abraham! I didn't realize that EPReadResults is the issue. @chriswmackey can help you with this. Good to know runEnergySimulation works fine.

**Comment by chriswmackey** [comment]
@ayezioro ,
Yes, it was a bug!  Very sorry about that.  I forgot to test it in cases where I did not set zoneComfortMetrics to True.  I just put a working version on the github.  Thanks a million.  I'm very happy that we caught this before the release.
![improtresultsworking](https://cloud.githubusercontent.com/assets/5567574/5992474/4d07d5f6-a9f9-11e4-8366-b5374785d54f.PNG)

-Chris

**Comment by mostaphaRoudsari** [comment]
Thanks @chriswmackey! and once more it is a reminder that project is getting big enough that we need to develop our own test cases.
