### ISSUE TITLE
writeResultParameters vs EPOutput

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#263]
Hi,
Is there any difference between those 2 components?
As i see you can dispose one of them.
-A.

**Comment by chriswmackey** [comment]
Good catch @ayezioro ,
I changed the name of the component since writeResultParameters is a really confusing name.  I had deleted the old component but it seems @mostaphaRoudsari accidentally added it back.  I just deleted it again.

**Comment by mostaphaRoudsari** [comment]
Oops! Sorry... Thank you for reporting and thank you for getting it fixed.
