### ISSUE TITLE
EPBlindsMat thickness

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#264]
Hi,
The slatThickness input receives milimeters instead of meters.
If you input 1 the idf writes 0.001
If you input 0.001 you get 0.00001
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
Yes it does and I say this in the description of the input.  I imagined that people usually want to refer to the thickness of blind blades in mm.  Is this a problem?
-Chris

**Comment by ayezioro** [comment]
Shame on me!!
I remember a wise guy said something related to a Hammer and a Nail ...
-A.
