### ISSUE TITLE
EPWindowShades --> blindsSchedule_

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#265]
Hi,
I noticed that the blindsSchedule_ is written in the IDF as the path of the CSV file, in the WindowProperty:ShadingControl.
The thing is that the line in the IDF editor is pink colored. I remember sending a ticket in the E+ helpserve. They said it is only color but is is supposed to work.
For my surprise, and after becoming almost crazy becouse doesn't matter what i change in the blinds definition the results are still the same, i changed in the IDF that instead the CSV path i choose the schedule name defined in the Schedule:Name group. Now it works!!!
So my suggestion/request is to change in your definitions that you use the name of the schedule instead the CSV path. Without this blinds are ON all the time.
Please see the figures. First 2 belong to the actual definition. Second 2, changing as my request.

Thanks,
-A.

**Comment by ayezioro** [comment]
![capture](https://cloud.githubusercontent.com/assets/7526023/5999504/050d73ae-aadb-11e4-8db4-46f0b7fd31d7.jpg)
![capture1](https://cloud.githubusercontent.com/assets/7526023/5999506/0a467a1e-aadb-11e4-845e-166e507220b4.jpg)
![capture3](https://cloud.githubusercontent.com/assets/7526023/5999510/0f2086ce-aadb-11e4-8f69-73cbe687ae3f.JPG)
![capture2](https://cloud.githubusercontent.com/assets/7526023/5999512/13a8fd5c-aadb-11e4-8c3a-38548c2e3217.jpg)

**Comment by chriswmackey** [comment]
@ayezioro ,
Good catch.  I just fixed this and sorry for not realizing this sooner.  I had to do something similar for the nat vent component but I forgot to update this one.
![fixedblindsched](https://cloud.githubusercontent.com/assets/5567574/6005628/c55f1fc4-aad9-11e4-89a4-2ea4938c8d20.PNG)
https://www.dropbox.com/s/84uh9ijcr73a7ue/HB_shoeboxing_CWM_AY_Resid_ORG_CWM.gh?dl=0
-Chris
