### ISSUE TITLE
Put in a warning if the user inputs a zone or surface name starting/ending with a blank space

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#267]
EnergyPlus apparently cuts out the space:
http://www.grasshopper3d.com/group/ladybug/forum/topic/show?id=2985220%3ATopic%3A1216920&xg_source=msg

**Comment by mostaphaRoudsari** [comment]
@chriswmackey maybe we should just strip() the inputs for names in initial components. It will remove spaces and \n from start and end of the string

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I forgot about strip().  That sounds great and very similar to what E+ does with the zone names.  I'll add it in at some point.
-Chris

**Comment by chriswmackey** [comment]
Fixed.
https://github.com/mostaphaRoudsari/Honeybee/commit/df011a50dbe109e729e365754582ff01cc561617
Should have done this a long time ago.
-Chris
