### ISSUE TITLE
Honeybee fails to find exisiting constructions

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#270]
http://www.grasshopper3d.com/xn/detail/2985220:Comment:1217139

**Comment by arkdanielnielsen** [comment]
For some reason it helps to Graft the input when adding Constructions or Materials to library. The same occur when searching for the new materials....

**Comment by mostaphaRoudsari** [comment]
I found a similar issue right now in the class with material names. I will check it after the class:

![image](https://cloud.githubusercontent.com/assets/2915573/6048051/b19dd658-ac7b-11e4-933c-ffdd7ec4d7ca.png)

**Comment by arkdanielnielsen** [comment]
I get similar issues. But by updating or replugin it typical works.
I also found another issue when creating Custom EP Library. I think I am doing it right with the text (I know it should be placed in the userCustomEPLibrary.idf this is just a backup).
https://www.dropbox.com/s/bkzvgsnybdvnk4q/_userCustomEPLibrary_backup.txt?dl=0
![honeybee_epconstruction-04](https://cloud.githubusercontent.com/assets/7299731/6056772/0bc942e4-ad16-11e4-983c-418738faba73.jpg)
