### ISSUE TITLE
Add Parallel Coordinate visualization to Honeybee

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#279]
[This is the plan- I will break it down into separate issues later]

I'm changing the plan for integrating Pollination (https://github.com/HoneyPatch/pollination/issues/1) into Honeybee. Let's first get the visualization part working and leave cloud-based simulation for later. In many cases analysis can be run locally and so we need to have a better way to visualize and explore the results.

Here are the steps to get a prototype version to work this weekend:

1. Grasshopper components: We need a component that collects the data from parametric runs and  generates a .csv or json file. I'm thinking to use branches and keep the component simple but then it is up to users to get the data structure right! (Good luck with this one) or we can modify lookup folder components to somehow do this--

2. Web interface: I can borrow the base code from https://github.com/HoneyPatch/pollination project or one of the other available parallel coordinates examples (https://syntagmatic.github.io/parallel-coordinates/) and modify it for Honeybee. Better colorset, better highlight, and potentially integration with some images of the project.

Data can be embedded into an html file and loaded locally for an easier access and/or be loaded to web.

Ok. I'm excited for this - Let's make it happen :honey_pot:

**Comment by mostaphaRoudsari** [comment]
More useful links:
http://www.columbia.edu/~cme2126/datavisuals/bigdata_parallelcoordinates.html
http://bl.ocks.org/jasondavies/1341281

**Comment by mostaphaRoudsari** [comment]
Here is the page - Still very basic: http://mostapharoudsari.github.io/Honeybee/Pollination

![image](https://cloud.githubusercontent.com/assets/2915573/6223883/6f7285d4-b640-11e4-866d-91aec4aabf7e.png)


Here is an example file if anyone wants to go ahead and play around:
https://www.dropbox.com/s/3rb8xhjf6zf75yd/Pollination_R_00.gh?dl=0

![image](https://cloud.githubusercontent.com/assets/2915573/6223844/fc90c6f2-b63f-11e4-8282-10c039967a77.png)

**Comment by mostaphaRoudsari** [comment]
Almost ready to go!

![image](https://cloud.githubusercontent.com/assets/2915573/6243867/7b585d96-b718-11e4-9bec-a721fceb1a09.png)

**Comment by mostaphaRoudsari** [comment]
cell size is also fixed now

**Comment by mostaphaRoudsari** [comment]
Ready to go > http://mostapharoudsari.github.io/Honeybee/Pollination

**Comment by arkdanielnielsen** [comment]
This is really cool!
Also a great link to the presentation by Kai Chang - really funny and interesting!
1) Would it be possible to save/make a html link with the data, so you don't have to import the data each time you want to see the result. I am thinking this could be useful for sharing with other. 
2) As you also write somewhere it could be cool with images of the different runs. Maybe something like this: 
![udklip](https://cloud.githubusercontent.com/assets/7299731/6378069/f820a606-bd28-11e4-947c-4fbdbff5f1b2.JPG)

**Comment by mostaphaRoudsari** [comment]
Hi @arkdanielnielsen,

1. I see this one coming! :) There are solutions but I want to find a way to do it with no back-end set up. This week I will probably do no development this week as I want to capture more videos before I lose my free Camtasia license. ;) - but seriously my Ladybug/Honeybee emails reached +100 now and I'm afraid if I don't get back to them this week it probably won't ever happen.

2. I think we can have a special column for images and it links every option to one image which will be loaded once you click on the line.

Feel free to go ahead and open separate issues for both of them and I will try to address them ASAP.

**Comment by mostaphaRoudsari** [comment]
@arkdanielnielsen try this: http://tt-acm.github.io/DesignExplorer/

**Comment by arkdanielnielsen** [comment]
@mostaphaRoudsari This is awesome!!

**Comment by arkdanielnielsen** [comment]
@mostaphaRoudsari one Q.... is the setup the same as Honeybee>Pollination and what about attaching images? Do you have a example file?

**Comment by mostaphaRoudsari** [comment]
@arkdanielnielsen thanks. It's very similar. check file preparation here: https://github.com/tt-acm/DesignExplorer/wiki
Images should be hosted on the web and the link should be provided inside the csv file.
