### ISSUE TITLE
set default value for callFromHive to True

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#282]
@chriswmackey I found that it is very confusing for most of the users! What do you think about changing the default to True?

![decomposezone](https://cloud.githubusercontent.com/assets/2915573/6204579/9008d6b8-b51e-11e4-8fa9-9af4952189e1.png)

Here is one more example: http://www.grasshopper3d.com/group/ladybug/forum/topic/show?id=2985220%3ATopic%3A1224499&xg_source=msg

**Comment by mostaphaRoudsari** [comment]
My bad! It is already set to True. Sorry @chriswmackey!

**Comment by chriswmackey** [comment]
No worries.  I feel like I underwent this same deliberation a few months ago.
