### ISSUE TITLE
Add mouse hover for each polyline

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#284]
Now highlight triggers from the table but what will be really useful is if I can click on the line and it gives me more information on the chart, and yes I'm thinking that there should be an image that pops up for that option. Probably a good solution is to keep the images locally on users system and load them on demand otherwise it will add to loading time but I will worry about this later.

**Comment by mostaphaRoudsari** [comment]
I need to learn more about CanvasRenderingContext2D to be able to do this. They are not svg objects!
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial

Here is an old example that draws the lines as separate paths so adding mouse events are easy:
http://dexvis.com/vis/blog/parallel2/MasseyRatingsSEC2012.html

**Comment by mostaphaRoudsari** [comment]
I'm not obviously the only person who is looking for this: https://github.com/syntagmatic/parallel-coordinates/issues/32 and fortunately there are ways to do it: http://bl.ocks.org/syntagmatic/5441022

I think I will give it a try https://github.com/syntagmatic/parallel-coordinates/issues/32#issuecomment-75105344

**Comment by mostaphaRoudsari** [comment]
Done with tooltip! Tooltip won't work for multiple selections though.
![image](https://cloud.githubusercontent.com/assets/2915573/6313497/3477b582-b97c-11e4-86bd-b8fc2363c1e7.png)

**Comment by mostaphaRoudsari** [comment]
And here it is for multiple sets - I leave this open to make sure I remember to put an example together for parallel coordinate.
![image](https://cloud.githubusercontent.com/assets/2915573/6313526/f22ac3d8-b97e-11e4-9353-4f2ef0fa6f74.png)

**Comment by mostaphaRoudsari** [comment]
Also added reversed link from click to gird - time to clean and re-organize functions

![image](https://cloud.githubusercontent.com/assets/2915573/6315982/9899aa6a-b9e1-11e4-81e7-b965bbbc64b8.png)

**Comment by mostaphaRoudsari** [comment]
Done and done!

![image](https://cloud.githubusercontent.com/assets/2915573/6317501/93e51566-ba24-11e4-84ba-32129170add3.png)

I still need to right an example for parrcoord!

**Comment by jcrichard** [comment]
hi mostaphaRoudsari. I am using your viz thanks a lot for sharing. I just find a bug when we want smoothness and bundleDimension. Di you desactivate these options ?
