### ISSUE TITLE
honeybee_honeybee error

### ISSUE THREAD

**Issue by agusHariyadi** [mostaphaRoudsari/Honeybee#285]
![honeybee error](https://cloud.githubusercontent.com/assets/6168707/6280471/f750722e-b8f0-11e4-8be4-92d9d1abe58d.JPG)
@mostaphaRoudsari 
What should I do?

**Comment by mostaphaRoudsari** [comment]
@agusHariyadi it should technically never happen. I assume you don't have EnergyPlus installed on this system but it still should work fine. Do you still have the issue? If it still happens for you can you upload your file? I checked with the latest version and it gives me the right warning if it can't find the folder.

**Comment by agusHariyadi** [comment]
@mostaphaRoudsari  Yes and No..
It still happen but only in my system. when I open the file in my laptop It just fine..
I try to install EP 8.2 with EP 8.1 still in my system and It gave me the same error..
When I uninstall both EP version the error gone..
then I install EP 8.1 again and the error appeared again..
Finally I only install EP 8.2 in my system and now It works.. but the problem still mysterious to me..
https://www.dropbox.com/s/kozn1hz6qv34ocw/honeybee.gh?dl=0

**Comment by jacoposartore** [comment]
Hi @mostaphaRoudsari I have the same error on my system. I have always had EnergyPlus 8.1 installed on my sytem. Should I install EnergyPlus 8.2?

![epversion error](https://cloud.githubusercontent.com/assets/8501837/6325212/a922e702-bb44-11e4-9d4e-76ace1334f40.png)

**Comment by agusHariyadi** [comment]
Hi @jacoposartore  The easiest way is to install EnergyPlus 8.2 and uninstall EnergyPlus 8.1..
base on https://github.com/mostaphaRoudsari/Honeybee/issues/203 from @ayezioro Results are consistent..
but if you deal with OpenStudio,you might have a problem.. the issue still open..https://github.com/mostaphaRoudsari/Honeybee/issues/214
What do you think @chriswmackey  @mostaphaRoudsari ?

**Comment by ayezioro** [comment]
Hi,
I have both versions installed. That should be not a problem.
-A.

**Comment by jacoposartore** [comment]
Thank you @agusHariyadi Honeybee is now fully working. I first uninstalled EP 8.1 and then installed EP 8.2 but the error was still there. So I uninstalled EP 8.2 so that the component reported that it couldn't find any version of EP and finally I installed it again and got it working.

**Comment by mostaphaRoudsari** [comment]
This one should be solved now > https://github.com/mostaphaRoudsari/Honeybee/commit/808e592c06abdb77a4afafd9da21adf0f5ebe04d
