### ISSUE TITLE
Double check IdealAirLoads system

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#287]
Read more here: http://www.grasshopper3d.com/group/ladybug/forum/topic/show?id=2985220%3ATopic%3A1229923

@chriswmackey I know you will be already checking this but I just add this here to keep track of issues related to IdealAirLoads system. I will be super busy tomorrow until I submit the papers but I'm planning not to develop new features and spend more time on testing and support.

PS: @chiensiTB it would be great if you can take a look to this discussion if you get a chance.

**Comment by chriswmackey** [comment]
I fixed the issue as best I can.  The reality at the end of the day is that the ideal air system is incredibly simple and it is not right for us to be taking values from it as fact.  See my full response on the Grasshopper discussion Mostapha posted.
-Chris

**Comment by mostaphaRoudsari** [comment]
Thanks @chriswmackey! I saw that this conversation is still going on back in the group. Looking forward to see the results. Also I will try  to block some time this week to check new features of IdealLoads in more details.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari , I feel that I have gone on a wild goose chase with the ideal air system that has lead all of the way back to the original ideal air system template and attributes that you had.  I guess that you can at least change the attributes now and I feel that I finally understand how the ideal air system works and why using it without understanding the assumptions can be really dangerous.  I definitely need to make some tutorial videos on it soon.
