### ISSUE TITLE
Add a component to let assign shadings with schedule to window

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#29]
@chriswmackey: "I have a feeling that a lot of users might be interested in shading schedules and possibly creating their own schedules based on kinetic facades, glare studies that account for users drawing blinds, etc.  I feel like this could probably be added to the inputs of the "Update Schedules" component for the zone but I'm not sure if it would be better if it was window-specific."

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Now that we have a bunch of more specific issues about blinds open, I am going to close this very old one out.
-Chris
