### ISSUE TITLE
Q - runItAll

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/Honeybee#295]
Why is the "runItAll" as well not in the Honeybee tab? That is in the parametric example file.

**Comment by mostaphaRoudsari** [comment]
@arkdanielnielsen thanks! runItAll is in C# and is originally developed by David Rutten and I modified it. We have an open discussion for this on ladybug (https://github.com/mostaphaRoudsari/ladybug/issues/95) so I'm closing this one.

**Comment by mostaphaRoudsari** [comment]
It's now under 4|Extra in Ladybug.

![image](https://cloud.githubusercontent.com/assets/2915573/10866803/3e649c0a-8018-11e5-822a-a86b9f1726e4.png)

**Comment by mostaphaRoudsari** [comment]
oh... and it's called fly! :)
