### ISSUE TITLE
OpenStudio simulation not working with HVACSystemList other than Ideal Load, PTAC and PTHP

### ISSUE THREAD

**Issue by jacoposartore** [mostaphaRoudsari/Honeybee#304]
Hi @chiensiTB I have had an error while recreating the OpenStudio systems you showed on your YouTube tutorial https://www.youtube.com/watch?v=3VTQDGGMZm8, with all the HVAC templates but the PTAC, PTHP and Ideal Loads.

Here is the image that shows that when choosing for example the PTHP the definition works fine

![openstudio pthp ok](https://cloud.githubusercontent.com/assets/8501837/6734535/eef31d70-ce58-11e4-8ca8-9dc0f8d9a6c5.png)
 
whereas when the Packaged VAV is selected, it returns the error "No .eio file was found adjacent to the .csv _resultFileAddress.results cannot be read back into grasshopper without this file."

![openstudio packaged vav error](https://cloud.githubusercontent.com/assets/8501837/6734548/061d38d2-ce59-11e4-8909-318793098720.png)

I checked the folder where the files are stored and the .err file reports this:

Program Version,EnergyPlus-Windows-64 8.1.0.009, YMD=2015.03.19 16:54,IDD_Version 8.1.0.009
   ************* IDF Context for following error/warning message:
   ************* Note -- lines truncated at 300 characters, if necessary...
   *************   1619 Sizing:System,
   ************* indicated Name=Packaged Rooftop VAV with Reheat
   ************* Only last 10 lines before error line shown.....
   *************   1631   Yes,                                    !- 100% Outdoor Air in Cooling
   *************   1632   Yes,                                    !- 100% Outdoor Air in Heating
   *************   1633   0.0085,                                 !- Central Cooling Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   *************   1634   0.008,                                  !- Central Heating Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   *************   1635   DesignDay,                              !- Cooling Design Air Flow Method
   *************   1636   0,                                      !- Cooling Design Air Flow Rate {m3/s}
   *************   1637   ,                                       !- Supply Air Flow Rate Per Floor Area During Cooling Operation {m3/s-m2}
   *************   1638   ,                                       !- Fraction of Autosized Design Cooling Supply Air Flow Rate
   *************   1639   ,                                       !- Design Supply Air Flow Rate Per Unit Cooling Capacity {m3/s-W}
   *************   1640   DesignDay,                              !- Heating Design Air Flow Method
   ** Severe  ** IP: IDF line~1640 Invalid Number in Numeric Field#13 (Zone Maximum Outdoor Air Fraction), value=DESIGNDAY, in SIZING:SYSTEM=PACKAGED ROOFTOP VAV WITH REHEAT
   ** Warning ** IP: Note -- Some missing fields have been filled with defaults. See the audit output file for details.
   ** Severe  ** IP: Possible incorrect IDD File
   **   ~~~   ** IDD Version:"IDD_Version 8.1.0.009"
   **   ~~~   ** Version in IDF="8.2" not the same as expected="8.1.0"
   **   ~~~   ** Possible Invalid Numerics or other problems
   **  Fatal  ** IP: Errors occurred on processing IDF file. Preceding condition(s) cause termination.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=2
   ..... Last severe error=IP: Possible incorrect IDD File
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 1 Warning; 2 Severe Errors; Elapsed Time=00hr 00min  1.14sec

Here is the definition (https://www.dropbox.com/s/k3myybof2o8ab0o/test_OS.gh?dl=0).

**Comment by chiensiTB** [comment]
Hi @jacoposartore are you still having this problem?  I opened your file and it ran just perfectly on my machine.  When I look at your screenshots, it is the results file that seems to be in error, not the OpenStudio component.  Is this correct?

I admit that I have not tested the HoneybeeReadEPResult component very much with my OpenStudio component.  Usually, I query the SQL files.

@chriswmackey, does this look like a ReadEPResult error to you?

**Comment by jacoposartore** [comment]
Hi @chiensiTB I'm stille haing the issue. The OpenStudio component works fine as the file is correctly created and if I open it in OpenStudio the systems are generated with the specific values given by the definition (see the High Speed COP for example)

![openstudio ok](https://cloud.githubusercontent.com/assets/8501837/6776806/6a7436f4-d143-11e4-82bd-bd9b214301f5.png)

Moreover, if I run it within OpenStudio, the simulation runs perfectly.

![openstudio results ok](https://cloud.githubusercontent.com/assets/8501837/6776848/1068a432-d144-11e4-8cf2-8daed311df39.png)

**Comment by chiensiTB** [comment]
@jacoposartore what versions of EnergyPlus and OpenStudio do you have installed on your computer?  Looking more closely at the error, for some reason the IDF is written to 8.2 but the IDD is 8.1.0.009

I think you are right.  It is an issue with the versions not aligning.  Can you confirm what version of OpenStudio and EnergyPlus (you may have multiple) installed.

**Comment by jacoposartore** [comment]
On my system I have installed EnergyPlus 8.1.0.009 (I had previously installed 8.2.0 but I removed it with the uninstaller) and OpenStudio 1.6.0. What do you think I should do to align them?

**Comment by jacoposartore** [comment]
@chiensiTB I checked again the .err file that OpenStudio generated, this time the one created by OpenStudio, and I figured out that OpenStudio 1.6.0 now runs with EP 8.2.0 (my bad, I didn't know that), whereas the idd files I created within the definition were 8.1.0, as you previously noticed. I uninstalled then EP 8.1 from my system and installed EP 8.2, so that the idd file version now is 8.2 (and OpenStudio doesn't report that warning anymore).

As I activate the toggle to activate the simulation within the OpenStudio component, the command prompt windows opens and instantly closes before even opening EnergyPlus. By opening the .bat file I discovered that the reference folder for the Epl-run file is still C:\EnergyPlusV8-1-0 whereas it should point to C:\EnergyPlusV8-2-0. Here is its content:

c:
cd\ladybug\unnamed\OpenStudio\unnamed\
C:\EnergyPlusV8-1-0\Epl-run c:\ladybug\unnamed\OpenStudio\unnamed\ModelToIdf\in c:\ladybug\unnamed\OpenStudio\unnamed\ModelToIdf\in idf C:\ladybug\ITA_Venezia-Tessera\ITA_Venezia-Tessera.161050_IGDG.epw EP N nolimit N N 0 Y

**Comment by jacoposartore** [comment]
@chiensiTB I solved the problem by editing all the C:\EnergyPlusV8-1-0 references within the OpenStudio component to to C:\EnergyPlusV8-2-0. Thank you very much for your hints!

Anyhow, I think that could be useful to automate the EP folder reference according to to the OpenStudio dlls and EP installed version.

**Comment by chriswmackey** [comment]
Hey guys,

I am glad that this seems to have gotten fixed and sorry for coming late to the discussion. Just to check, is the Read EP Result component bringing in the results correctly for you now, @jacoposartore ?

-Chris

**Comment by jacoposartore** [comment]
Hi @chriswmackey, I'm still having the issue when, for example, a VAV system is selected. Although the simulation runs correctly now (see the Read EP surface component in the picture), now the orange error reports

![read ep result vav](https://cloud.githubusercontent.com/assets/8501837/6809450/b30ff462-d25a-11e4-9d5d-54a56492a07e.png)

"Failed to parse the result file.  The csv file might not have existed when connected or the simulation did not run correctly.Try reconnecting the _resultfileAddress to this component or re-running your simulation."

If a packaged VAV is selected the Read EP result seems to work fine 

![read ep result packaged vav](https://cloud.githubusercontent.com/assets/8501837/6809571/816129bc-d25b-11e4-880b-31d6095eb654.png)

but later causes the Indoor Comfort Analysis to brake

![read ep result packaged vav indoor comfort error](https://cloud.githubusercontent.com/assets/8501837/6809622/c8d6425a-d25b-11e4-82ff-ffd2da3a00e6.png)

with the error:

"Runtime error (AggregateException): Si sono verificati uno o più errori.
Traceback:
  line 670, in mainAdapt, "<string>"
  line 1029, in script"

This error happens also if a select PTHP as a system, even if the Read Result seems to work fine.

![read ep result pthp](https://cloud.githubusercontent.com/assets/8501837/6809854/54181cd4-d25d-11e4-820c-51eabd8c67e3.png)

Needless to say, if I use Energy Plus component instead of OpenStudio one all these components work perfectly and the workflow is able to visualize comfort results.

Chris, please tell me if you need the gh definition.

**Comment by chriswmackey** [comment]
@jacoposartore ,

You are awesome.  Thanks for taking the components to a new level and finding these bugs.  There may be two separate bugs in what you have found here (one with the Result Reader and the other with the indoor comfort map.  There may also be an issue with the requested outputs).

If you post a link to the dropbox file, I will fix it as soon as I can.
-Chris

**Comment by jacoposartore** [comment]
@chriswmackey you, @mostaphaRoudsari, @chiensiTB and everybody else is collaborating with you are awesome, guys! I couldn't do my job without the components you did!

Getting back to the point, I have uploaded here (https://www.dropbox.com/s/s306t2zvwrsr7yg/test_OS_Read_EP_Error.gh?dl=0) the definition and here (https://www.dropbox.com/s/4tdtlyle2zwnfso/unnamed.zip?dl=0) the folder that contains both the .osm file and the folder (where basically the EnergyPlus outputs are located) created by the OpenStudio component inside c:\ladybug . I added the second link as I don't know if you still have the PINVOKE error #214 on your system and you are therefore able to run the simulation.

**Comment by chriswmackey** [comment]
@jacoposartore ,

I am sorry for getting back so late.  This past week was very busy with my thesis around the temperature maps and a 3-day LB+HB workshop that I gave.

I did, in fact have the PINVOKE error so it was good that you posted the other files:
![image](https://cloud.githubusercontent.com/assets/5567574/6931928/09894b32-d7e1-11e4-921f-c556cb23a1ac.png)

You had indeed found a bug.  It seems that the structure of the boiler and Chiller outputs had changed from a previous version of EnergyPlus.  The fixed Read Result Reader is now on the github and in the attached file:
https://www.dropbox.com/s/iwl97xgf860swlu/test_OS_Read_EP_Error_CWM.gh?dl=0

As for the comfort map error, there was someone at a workshop that I was just running who found the exact same error.  I am currently aware of a couple of bugs with the comfort map workflow and I am working to fix them now. It looks like this one was actually the result of an old bug that I thought I had fixed.  Because E+ has difficulty understanding quad glazing, Honeybee will sometimes export two window triangles instead and will re-name one of them.  I could not find a fix to re-name the two triangels correctly within HB_HB as this is Mostapha's code and it was just too hard to track down.  I just put in an extra check in the Comfort map workflow and the color surfaces based on EP result that works by the same logic.  Hopefully, this fixes the issue once and for all. This fixed comfort map is also in your attached file.

-Chris

**Comment by jacoposartore** [comment]
@chriswmackey,

Great that you managed to solve the issues! Thank you!  You don't have to apologize for being late, I knew you were busy with the workshop in Mexico City.

I have re-run the file you have updated and comfort maps components are working fine as well as color zone surfaces (also glazed surfaces are shown)! Great job!
Unfortunately, I came up with another error:

Some of the outputs of Read EP Result can't generate correct outputs (colored mesh + legend) of Color Zones by EP Result, if connected to the _zoneData input. Those are: totalThermalEnergy, thermalEnergyBalance, cooling, heating and fanElectric.

I have uploaded here the definition (https://www.dropbox.com/s/kj2a7c8k49vpiw6/test_OS_Read_EP_Error_JS.gh?dl=0) and here the folder (https://www.dropbox.com/s/4tdtlyle2zwnfso/unnamed.zip?dl=0).

**Comment by chriswmackey** [comment]
@jacoposartore ,
When you use a central HVAC system like a VAV system, the cooling and heating outputs that you get out of the ReadEPResult component are those values of electricity or fuel heat used at the chiller and boiler.  Since OpenStudio, by default, only generates one boiler and chiller for the entire building, the results cannot be associated with any given zone and so the colorZonesByEP result component does not color any of the zones with the data.  I know that this is a bit confusing in your case because your building is only one zone but I still think that this makes sense in this case as the boiler is still assigned at the building level in E+.
If you use a system that works on a zone-by-zone basis, like a PTHP or an ideal air system, you will see zones colored with heating and/or cooling.
Let me know if this makes sense.
-Chris

**Comment by jacoposartore** [comment]
@chriswmackey ,
I totally agree with you that a VAV system has central plants (boiler, chiller, cooling tower) and therefore their results can't be related to the fuel or electricity used to air condition a single zone. 

As when dealing with multiple zones it is desirable to know how performs, in therms of energy use, each of them in comparison with the others, which parameter do you think I should take into account? 

As the same VAV system has also heating coil located in every zone (see the selected item in the first image) that made up the whole building in order to reheat the air treated by the AHU, in my opinion I should either use the mass (kg/s) flow rate of each air terminal duct for every zone (see the second image) or the zone balance system (W) air transfer rate (see the third image).

![openstudio vav systems](https://cloud.githubusercontent.com/assets/8501837/7019557/9383777e-dd11-11e4-8f9c-4976fdbd68f6.png)

![openstudio vav zone duct mass flow](https://cloud.githubusercontent.com/assets/8501837/7020292/14eb85f8-dd18-11e4-8fa3-a3b71cd07402.png)

![openstudio vav zone balance system air transfer rate](https://cloud.githubusercontent.com/assets/8501837/7020531/09fdbab0-dd1a-11e4-8fe3-992c2e0d98d7.png)

Let me know your thoughts.

**Comment by chriswmackey** [comment]
@jacoposartore ,
To be honest, I have not really given much thought as to how to deal with the results of the central system yet. My implementation on the ReadEPResult component of bringing in chiller/boiler loads was just what made sense to me at the time.
Thinking more about your response, it might make the most sense to import a central system's zone-level heating/cooling loads with the ReadEPHVACResult component.  Right now, you should see that this component should import the mass flow rate of HVAC air into each of the zones as you request.  I realize it can also bring in the latent and sensible cooling from the coils as well (right now, the sensible and latent heat only comes out with the ideal air system).  Let me know if having these zone-level sensible and latent heat values would be useful and I will implement them.
-Chris

**Comment by jacoposartore** [comment]
@chriswmackey,
The mechanical engineer I'm collaborating with told me that latent heat (that changes the humidity of the air) is generally adjusted within the AHU whereas the sensible heat (that changes the temperature of the air) is modified at each zone level. Thus meaning that it should be fine enough to retrieve the sensible heat for each zone and that having the heat values for each zone would be useful. I will possibly discuss my first assumption with him and let you know.

By the way, at the moment the ReadEPHVACResult component only works with Ideal Air Loads, see the error when a Packaged VAV is selected.

![readephvacresult ideal air load](https://cloud.githubusercontent.com/assets/8501837/7028843/0d3eb97e-dd59-11e4-8ea0-cc4f27e11d55.png)

![readephvacresult packaged vav](https://cloud.githubusercontent.com/assets/8501837/7028844/10434f7c-dd59-11e4-899d-d0d171f4bf6b.png)

**Comment by chiensiTB** [comment]
Hi guys-

Since this was originally an issue about open studio not working (but now it does)...@chriswmackey...can we close this issue and reassign it to a new issue, something about visualizing OpenStudio results?

**Comment by jacoposartore** [comment]
I agree with you, the thread has moved from the problem I had. 

By the way, I still have to manually edit all the references of C:\EnergyPlusV8-1-0 within the OpenStudio component to C:\EnergyPlusV8-2-0 (my actual EnergyPlus installed). I wonder if you guys can adjust its code to self update according to the version of EnergyPlus installed (I think using the folders.EPPath variable).

**Comment by mostaphaRoudsari** [comment]
@jacoposartore can you open a new issue for the version. It's tricky since some of the users (including me) can't use the newer versions of OpenStudio because of the loading bug, and the old version works with EP 8.1. We can add couple of checks to get the versions right.

I'm closing this.
