### ISSUE TITLE
Missing Economizer Schedules from OpenStudioMasterTemplate

### ISSUE THREAD

**Issue by jacoposartore** [mostaphaRoudsari/Honeybee#305]
Hi there,

I'm watching the videos that @chiensiTB uploaded to YouTube about OpenStudio (very well done and useful, by the way) and during the Airside Economizer one I figured out that I couldn't find on my system the schedule (Economizer Availabilty 6AM-7PM) he was referring.

I even deleted the OpenStudioMasterTemplate and OpenStudio_Standards files to get new ones from the internet but the schedules are still missing.

![openstudio schedules missing](https://cloud.githubusercontent.com/assets/8501837/6753646/e4bf70be-cf17-11e4-8bec-58fc9da2c6ba.png)

**Comment by mostaphaRoudsari** [comment]
Hi @jacoposartore! I leave this open for @chiensiTB's inputs but I assume he created the schedule himself. We don't have that in our library.

**Comment by chiensiTB** [comment]
Yes, @jacoposartore Mostapha is right.  I made this schedule using Honeybee's "Add to library" feature.  Have you used it before?  I can send you an example...

**Comment by jacoposartore** [comment]
Hi @chiensiTB, great to know that! Could you post an example? I only managed to create a csv schedule that can't be added to the EP library. Thank you very much!

**Comment by jacoposartore** [comment]
Hi @chiensiTB, I managed to create a simple definition that adds a schedule to the EP library. Here is the file if anyone else needs it (https://www.dropbox.com/s/geapgq76fpsg256/EPCustomSchedules.gh?dl=0).
