### ISSUE TITLE
Lighting Control Group issue

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#306]
Read more here: http://www.grasshopper3d.com/group/ladybug/forum/topics/lighting-control-group-issue?commentId=2985220%3AComment%3A1244821&xg_source=msg_com_gr_forum

I need to take a closer look. In case of sending a list Daysim crashes and once it is  a tree it only generates a single output. Something is wrong there.

Mostapha

**Comment by francesco-de-luca** [comment]
Mostapha what you mean "list" and "tree"? In my case Daysim never crashed. If list is a tree with one branch and tree a tree with multiple branches, in my case in the former there were all the outputs but only the first was a valid value, the other were 0, and in the latter there was just one single output ( with a valid value).

Francesco

**Comment by mostaphaRoudsari** [comment]
@francesco-de-luca,

I tested this issue for couple of different cases and to me it looks like an issue with Daysim and not Honeybee. I can get the results for two control group but the 3rd one always return 0. I checked the heading file and it looks fine.

![image](https://cloud.githubusercontent.com/assets/2915573/6997031/7f1a2188-db78-11e4-93cb-637381bf3a16.png)

Next step is to check the source code of daysim and see if there is something that I'm missing here.

Back to list vs datatree, I'm sorry that I made a confusion. If you have a single space you should pass all of your control groups as a single flatten list. Branching is only needed if you have multiple spaces.

**Comment by francesco-de-luca** [comment]
Hello Mostapha,
thank you for the work! Ok I see that it could be a problem with Daysim and not HB. Hope you can check the Daysim code. Anyway I was never able in anynway, flattening grafting or whatever, to get even two results. Maybe I have to input only two Lighting controp groups? In the sense that if I input three I get just one result and if I input two I get two? Sorry I read about but I don't remember now and I am not in front the computer but... what is the heading file?
Thank you for the lists and datatree clarification.

Best.

Francesco



Sent from my Samsung device


-------- Original message --------

**Comment by mostaphaRoudsari** [comment]
Heading file is one of the input files for Daysim. I think I get it fixed. It was a matter of having the numbers as int and not float numbers. I will update this issue and the one on Grasshopper group soon. Thanks.

**Comment by francesco-de-luca** [comment]
Ok sounds great! I will check for the fixed and new component in github. Thanks to you!

Francesco



Sent from my Samsung device


-------- Original message --------

**Comment by mostaphaRoudsari** [comment]
![image](https://cloud.githubusercontent.com/assets/2915573/6997323/7f36a058-db85-11e4-9f13-335673d902ca.png)

Here is the file: https://www.dropbox.com/s/8on2dmbwtoufh8f/lighting_control_groups_msr.gh?dl=0

**Comment by mostaphaRoudsari** [comment]
@francesco-de-luca it would be great if you can also update the discussion in Grasshopper group.

**Comment by Ding-** [comment]
@mostaphaRoudsari @francesco-de-luca 
Could you please see my questions regarding the work mechanism of the lighting control in HB/Daysim (http://www.grasshopper3d.com/group/ladybug/forum/topics/lighting-control-group-issue-2) at your convenience? thank you so much  in advance!
