### ISSUE TITLE
Lighting Control Group output

### ISSUE THREAD

**Issue by francesco-de-luca** [mostaphaRoudsari/Honeybee#309]
Hello,
congratulations for the huge work.
So far the results of the calculations of the energy consuption for electric lighting using the lightingControlGroup component in the Honeybee_Read Annual Result I component are readable only (?) in the Daysim report. Would be very useful to have this data as numeric output from the same Honeybee_Read Annual Result I component like all the others regarding Daylight Autonomy metrics, and splitted in case of more than one lighting control group (maybe one tree with different branches). Thank you!

Best

Francesco

**Comment by mostaphaRoudsari** [comment]
Thanks @francesco-de-luca - I know that this has been there for some time now. I blocked some time this Saturday to solely work on Honeybee and bugs like this one. You should have it fixed soon.

Duplicated with this one: https://github.com/mostaphaRoudsari/Honeybee/issues/306

**Comment by mostaphaRoudsari** [comment]
Making some progress here:

![image](https://cloud.githubusercontent.com/assets/2915573/6995766/0e38e33e-db2b-11e4-8528-5f0b0e778b81.png)

**Comment by francesco-de-luca** [comment]
Hey this is cool! is it already possible to download it?

Francesco



Sent from my Samsung device


-------- Original message --------

**Comment by mostaphaRoudsari** [comment]
Yes. You can find it under tab 04.
![image](https://cloud.githubusercontent.com/assets/2915573/6997335/dc2b9d7c-db85-11e4-9261-914c5ae30f91.png)
