### ISSUE TITLE
Honeybee_Honeybee overwrites user's defined constructions each time

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#324]
Well! It shouldn't. Check this discussion: http://www.grasshopper3d.com/xn/detail/2985220:Comment:1261028

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
For clarity, does this mean that this issue won't be addressed until LB_LB + HB_HB become standalone libraries that are no longer in a component?
-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey it has been fixed which means only the first time that Honeybee_honeybee is dropped on canvas default libraries will be loaded. Otherwise the libraries will be kept as it is. As a result if user has created any new constructions, they will have access to it which was the bug.

**Comment by chriswmackey** [comment]
Wow!  That's Awesome!!!!!
Thanks for the clarification!!!!!
