### ISSUE TITLE
Wish - OpenStudio self-updating EP version reference

### ISSUE THREAD

**Issue by jacoposartore** [mostaphaRoudsari/Honeybee#326]
Hi there,

I'm opening this discussion following #304.

I wonder if it is possible to add some checks in OpenStudio main component to self update its reference folder of EnergyPlus according to the version of OpenStudio C# library files or the EnergyPlus version installed.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey has already addressed this one.

**Comment by jacoposartore** [comment]
Great! Thank you!
