### ISSUE TITLE
import gbXML component

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#328]
Multiple people asked me during the conference if we will ever have a gbXML importer so they can run some energy modeling with Honeybee for their REVIT model. I can see the value but am not sure if this is the right approach. REVIT gbxml exporter doesn't really have enough information and I wonder if we should just leave these sort of functionality for a Honeybee for Dynamo at some point?

**Comment by arkdanielnielsen** [comment]
Yes please ;)

**Comment by chiensiTB** [comment]
Mostapha-

Since the openstudio integration has a way to go, I think I will focus on
making the grizzlybear implementation better, as a primary method to
support the community better.

**Comment by mostaphaRoudsari** [comment]
@arkdanielnielsen yes please for which one? :)

@chiensiTB I agree. I will assign this to you. It will make so many people happy. We may also want to use OpenStudio's import gbxml method instead of writing our own version of it?

cc: @macumber

**Comment by chiensiTB** [comment]
Hi Mostahpa-

Most of the code we need is already there in GrizzlyBear.  It will be way
easier this way, just need to figure out how to port the data into Honebee
objects via python.  We already do it the other way around in GB.  I tried
for about an hour at the last hackathon.  I'm sure it will only take a
couple of days.  It may also be a good chance to try and check out the
power of the gbXML validator too.

**Comment by arkdanielnielsen** [comment]
For both, but it does not matter so much which strategy as long it gets easier. In both cases you need to do something more than just push the button, if you follow me.
But, it would be easier, I suppose if things worked in HB because it is already developed.

**Comment by arkdanielnielsen** [comment]
@mostaphaRoudsari by the way, I think there will be the same import problems with the zone geometry as with the .idf import as we looked at for a couple of month ago. Because of the zone creator in Revit.

**Comment by mostaphaRoudsari** [comment]
@chiensiTB you know better than anyone else what would be right approach for this so let's go ahead and do it as you suggested.
@arkdanielnielsen that's true. On the other hand I think this will push Autodesk's team to enhance their exporter. :pray:

**Comment by chiensiTB** [comment]
Guys, also back on board after being gone for a while.  We want a gbXML import, is that right?

**Comment by mostaphaRoudsari** [comment]
@chiensiTB yes please!

**Comment by mostaphaRoudsari** [comment]
Started addressing this. I couldn't export a revit gbXML with thermal properties. It only exports the names. There is also no schedule, and loads. @arkdanielnielsen do you know if there is a better way to do this?

![image](https://cloud.githubusercontent.com/assets/2915573/21533497/1d930d9a-cd29-11e6-8918-e78356eb24b1.png)

**Comment by arkdanielnielsen** [comment]
hi @mostaphaRoudsari No easy way to get thermal prop, only through Green Building Studio... :/

**Comment by mostaphaRoudsari** [comment]
Hi @arkdanielnielsen, Thanks. That's what I figured. There is a construction name but no details.
