### ISSUE TITLE
Change the screen shots!

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#329]
I'm not sure why it is happening but all the images on github page as well as Grasshopper group looks terrible!

**Comment by ayezioro** [comment]
Yes. It happens, but when you open the image it looks fine. So i'm not sure that changing them will solve the issue.
-A.

**Comment by mostaphaRoudsari** [comment]
Ha... You are right. I have no clue why it is happening. They look good on my system! :|

**Comment by chriswmackey** [comment]
This is an issue that I have seen all over the grasshopper website starting from a single date when they must have updated the site.  I think that we need to bring it up to David Rutten or someone with a high level of authority.

**Comment by mostaphaRoudsari** [comment]
Well, the same is happening on github if you check the intro page. I wonder if this is an issue with .png files and changing to jpeg files will solve the issue. What is funny is that the one's on Grasshopper website looks fine on my laptop!

**Comment by chriswmackey** [comment]
Ah.  You are right.  It's just something to do with the png format.  It happens any time a png is embedded in either github or GH.  See the last images in this discussion for the difference between the  png and the jpeg on the GH site:
http://www.grasshopper3d.com/group/ladybug/forum/topics/comfort-zone-problem

**Comment by chriswmackey** [comment]
I changed this on the main GH group page a while back.  Is there anywhere else where we should change this before closing the issue?

**Comment by mostaphaRoudsari** [comment]
Other places are Food4Rhino and github pages which seems to be fine. I'm closing this. Thanks @chriswmackey!
