### ISSUE TITLE
Icons for Honeybee generation

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Honeybee#331]
Hi everyone,

As an Engineer I am no artist and I don't know how to use Illustrator, therefore if someone could create icons for the following components which I will be releasing a beta of in the first week I'd really appreciate it. The components are as follows.

- Batteries,
- Inverters for EnergyPlus photovoltaics
- A energy generation system component (Takes individual components such as batteries,PV, wind turbines and links them together to form a generation system)
- Wind turbines
- Combustion engines (To come in the future)
- A visualization component - Visualize and energy and economic data from the Energy plus model (Still working on how exactly this one should work)

Cheers,

Anton

**Comment by chriswmackey** [comment]
@antonszilasi ,
It seems like this issue has been resolved now so I am closing it out.  Correct me if I am wrong.
-Chris
