### ISSUE TITLE
Energy-Plus 8.3 Compatibility 

### ISSUE THREAD

**Issue by HassanBaghdady** [mostaphaRoudsari/Honeybee#332]
Hi Mustafa,

Is Energy-Plus 8.3 compatible with Honeybee, in the installation instructions, version 8.1 was mentioned 

thank you&
best

**Comment by mostaphaRoudsari** [comment]
Hi @HassanBaghdady - The version on Food4Rhino supports EP8.1 and the one on github support EP8-2-7. No support for EnergyPlus 8-3 yet.
