### ISSUE TITLE
totalSolarGain_3DRotation

### ISSUE THREAD

**Issue by RobMDoe** [mostaphaRoudsari/Honeybee#333]
Having problems when 3DRotate as object goes through setEPZoneConstruction and seems to be cancelled out, so no rotation. All files and commentary at:
http://www.grasshopper3d.com/group/ladybug/forum/topics/totalsolargain
Thanks, Rob

**Comment by mostaphaRoudsari** [comment]
Duplicate #183

**Comment by chriswmackey** [comment]
This issue will be partially addressed once this is implemented:
https://github.com/mostaphaRoudsari/Honeybee/issues/373

**Comment by mostaphaRoudsari** [comment]
http://www.grasshopper3d.com/group/ladybug/forum/topics/modeling-high-rise-buildings-in-hb?commentId=2985220%3AComment%3A1392588&groupId=2985220%3AGroup%3A658987
