### ISSUE TITLE
Optimization for Honeybee generation 

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Honeybee#334]
Hi everyone!

Honeybee generation is almost ready to fly! im just trying to get the cashflow graph finished today, I have a question about the outputs from Read results files however, since the standard format in LB & HB is to create outputs like those below how should I craft my components so that a user could link the outputs up to Galapagos and undertake an Optermization study should I make an option so that the component only outputs the number?
![honeybee generation](https://cloud.githubusercontent.com/assets/8773483/7403909/a3124e44-ef1e-11e4-8e59-586f6c3e7e87.PNG)

**Comment by jacoposartore** [comment]
Hi Anton,

Great news! Users can separate text strings and numbers by using the Ladybug_Separate Data component. You can find it under the 1 | Analyze Weather Data group of Ladybug.

![cattura](https://cloud.githubusercontent.com/assets/8501837/7408183/b05b75e8-ef1a-11e4-922f-f1b252782267.PNG)

**Comment by antonszilasi** [comment]
Right - thanks I didnt know that!

**Comment by jacoposartore** [comment]
You're welcome! I'm glad to be helpful.
