### ISSUE TITLE
Make a component to separate based on Conditioned/Unconditioned

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#337]
As per this:
http://www.grasshopper3d.com/group/ladybug/forum/topics/component-request?commentId=2985220%3AComment%3A1278806&xg_source=msg_com_gr_forum

**Comment by mostaphaRoudsari** [comment]
Done via ff9ca51f820e11ab3e1d90c5b8ca2c9f7b075af9
