### ISSUE TITLE
Check the Direction of Normals in Surface-by-surface Method

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#339]
As per this discussion:
http://www.grasshopper3d.com/group/ladybug/forum/topics/significance-of-wall-orientation?commentId=2985220%3AComment%3A1279182&xg_source=msg_com_gr_forum

**Comment by chriswmackey** [comment]
I know it's not technically a bug but it's such a pain in the neck that I think it deserves the label.

**Comment by mostaphaRoudsari** [comment]
I think it is a bug actually. It should already check the normal direction for the faces (https://github.com/mostaphaRoudsari/Honeybee/blob/master/src/Honeybee_Honeybee.py#L4764).

**Comment by mostaphaRoudsari** [comment]
This should be also fixed via 50347c16676599a2c69f304e730fbd4eb3e2a2ac
