### ISSUE TITLE
Get Decompose Zone to Work

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#344]
A student at MIT discovered a bug today trying to bring HBSrfs back together into one zone:

https://www.dropbox.com/s/6iggpyz79ytb9gz/HoneyBee_MultiZone_Advanced_ghfile.gh?dl=0

**Comment by mostaphaRoudsari** [comment]
@chriswmackey what is exactly the issue here. There is no note inside the file.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

There were several students in Les's class that were using the new workflow with decompose zone and they were getting weird errors that I did not know how to fix at the time since I have not used this workflow yet.  I created the issue because I got a buggy GH file from one of the students and wanted to investigate it later when I had time.  The students might have just been using the workflow incorrectly and it might take some warnings to address it.  I will try to take a look at it sometime today so that we hopefully can close the issue.

-Chris

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
It was not an issue related to the decompose zone workflow. The student was just applying windows to the wrong surfaces. Everything seems good and the next time that I build an energy model, I will use this workflow so that I feel more comfortable when I am asked questions about it.
-Chris
