### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by fahimehm** [mostaphaRoudsari/Honeybee#346]
Hi Mostafa,
I have problem with the error:
"solution exception: index out of range"
I have tried DF or Grid based simulation but no change,
What's wrong with it?
Thanks
![image](https://cloud.githubusercontent.com/assets/12594885/7796083/db8c6e04-02f0-11e5-8db7-dd469090fbbc.png)

**Comment by chriswmackey** [comment]
@fahimehm ,
I don't know if this is going to fix your problem but you probably want to flip those floor surfaces around before plugging them into the test point component.  Also, you may want to update to the most recent version of the components on this github.  If you provide a link to a GH file that shows the problem, I guarantee that we can get to the bottom of it.
-Chris

**Comment by mostaphaRoudsari** [comment]
I agree with @chriswmackey that updating the components should solve this issue. I close this and suggest you to open a discussion in the group. If you already have an open discussion please provide us the link.
