### ISSUE TITLE
Put In A Check in Daylight Simulations to Make Sure the Number of Test Points is Greater Than the Number of Cores

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#347]
Some people were running quick annual daylight simulations of 4 points on computers with 8 logical processors.  As a result, they got no .ill files out of the component.  We should put in a warning to alert people when this happens.

**Comment by mostaphaRoudsari** [comment]
I thought I already took care of this. Here is where the check should be added: https://github.com/mostaphaRoudsari/Honeybee/blob/master/src/Honeybee_Honeybee.py#L1503

**Comment by chriswmackey** [comment]
Ah.  Therin lies the bug, no?  Shouldn't it be like so:

if numOfCPUs > numOfPoints: numOfCPUs = numOfPoints

Correct me if I am wrong.  If not, I will fix it now.
-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey that's it. I have a hard time to upload stuff to github with my connection. Please go ahead and get it fixed! Thanks.

**Comment by chriswmackey** [comment]
Awesome.  This is now fixed:
https://github.com/mostaphaRoudsari/Honeybee/commit/32582b2d2686d29c459d4faf48f3f630da83a141
