### ISSUE TITLE
Wish: North input back for HB_runDaylightAnalysis

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#350]
Hi,
Will be great if the input for North definition will be back for the HB_runDaylightAnalysis component.
Just needed it today, and i remember that the option was there in previous versions.
Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
@ayezioro it is removed because I couldn't implement it for annual analysis with Daysim at the time. You should be able to rotate the skies unless you are running an annual run. Does it solve your problem?

**Comment by ayezioro** [comment]
Oh, right.
The sky north will do the job.
Thanks ... and welcome back :-)
-A.

**Comment by mostaphaRoudsari** [comment]
Hi Abraham! Thank you sir. I should also thank you for taking care of discussions. We're so lucky to have you. :)
