### ISSUE TITLE
readComfortResult and adaptComfMtx differences

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#352]
Hi Chris,
Just downloaded the last version, as for 9.6.2015.
Updated one file and i see that the adaptComfMtx output from the IndoorComfAnalysis, which gives the percentage in the map, is different if i read the results file with the readComfortResult component, which gives a (delta?) temperature (instead of percentages).
FYI.
Thanks,
-A.

**Comment by ayezioro** [comment]
And, of course, i re-hooked the file paths and, now it is working well. Weird.
So i'm closing this one for now.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

There have been a lot of upgrades to the comfort map workflow over the last few days (I am happy to say that I just fixed the last of the bugs in complex geometric cases).  As such, I would recommend that you replace the 4 key comfort map components manually if you are upgrading to the most recent version.

-Chris

**Comment by ayezioro** [comment]
Yes Chris,
I've done that already.
Thanks,
-A.
