### ISSUE TITLE
import modifiers for radMaterials

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#354]
See this: http://www.grasshopper3d.com/group/ladybug/forum/topics/texfunc-material?page=1&commentId=2985220%3AComment%3A1299280&x=1#2985220Comment1299280

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
By virtue of the fact that this is a bug, I feel that it should probably be addressed by the next stable release.  Feel free to remove the milestone marker if you feel otherwise.
-Chris

**Comment by mostaphaRoudsari** [comment]
Thanks. Agreed. I will address this soon.

**Comment by mostaphaRoudsari** [comment]
```(\n|^)(\w*(\h*\w.*\n){1,})``` will work for almost any radiance object! I will implement this tomorrow

**Comment by mostaphaRoudsari** [comment]
![image](https://cloud.githubusercontent.com/assets/2915573/10870046/f0a17c3c-808e-11e5-96c5-80f258361b57.png)
