### ISSUE TITLE
Add Features Into OpenStudio Exporter that Have Been Missing Since PINVKOE Error

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#359]
I have started this issue since there are a number of features that I have implemented on the Write IDF component that I know I need to implement on the OpenStudio exporter but have been unable to since the almighty PINVOKE error has held a tyrannical grasp over all OpenStudio development.  Now that this impediment is finally removed (), I will try to implement most of these in the next few weeks.

Note that I have made this issue just for myself but I know others have features that they should implement in the OpenStudio exporter as well (notably, @antonszilasi , you should implement the HBGenerators and the Earth Tube capability on the OpenStudio component).

The list of things that I must implement is as follows:

1) Air walls (including mixing objects and the ability to change their mixing schedules).

2) Zone Natural Ventilation Objects (including both fan-driven and wind-and-stack objects).

3) Blinds and Dynamic Blinds
   To be done at the same time as these issues:
   (https://github.com/mostaphaRoudsari/Honeybee/issues/190)
   (https://github.com/mostaphaRoudsari/Honeybee/issues/300)

4) Adding Internal Mass to Zone

5) Add in additional strings for the IDF

6) Add in HVAC availability schedule 
   To be done at the same time as this issue:
   (https://github.com/mostaphaRoudsari/Honeybee/issues/246)

-Chris

**Comment by ayezioro** [comment]
Good news!
I'm for number 3 as they are the more critical (for me and for the crucial influence of shading in energy consumption).
-A.

**Comment by mostaphaRoudsari** [comment]
I also add these two to the list:

Get EnergyPlus version to be updated accordingly inside OpenStudio component -> https://github.com/mostaphaRoudsari/Honeybee/issues/326

Integrate 3Phase daylight simulation ->
https://github.com/mostaphaRoudsari/Honeybee/issues/290

**Comment by jacoposartore** [comment]
Thank you @mostaphaRoudsari for reporting my wish.
May I add the humidstat on this list? As @ayezioro wrote in #246.

**Comment by chriswmackey** [comment]
@ayezioro ,
I agree that the shades should be high on the priority list and I will get to them after adding in some last features to the glazing by ratio and energy shade benefit workflow.
-Chris

@jacoposartore ,
The humidity deserves its own issue and I have just created one:
https://github.com/mostaphaRoudsari/Honeybee/issues/360

-Chris

**Comment by chriswmackey** [comment]
I forgot to close this a while back when I put in the display of the date.

**Comment by chriswmackey** [comment]
Woops.  I closed the wrong issue

**Comment by chriswmackey** [comment]
@ayezioro ,
I have not yet gotten around to implementing the shade abilities in the OpenStudio workflow but I have finished adding all of the capabilities in the EnergyPlus one so I should be able to tackle this next.

**Comment by chriswmackey** [comment]
This list is getting narrower.  Now, we just need the following:

1) Blinds and Dynamic Blinds

2) Adding Internal Mass to Zone

3) Add in additional strings for the IDF

**Comment by NENEN** [comment]
Aha, now seeing this, I will pause for the moment in my effort to simulate dynamic blinds through the OS exporter. Thanks for all the work, CWM - it's uncanny how you have been just a couple steps ahead of what I've been trying to do for a couple years now, making the right HB modeling and simulations possible just in the nick of time, over and over.

**Comment by chriswmackey** [comment]
Thank you for the kind words, @NENEN .
We are down to just the Blinds now.  We have almost everything we need!

**Comment by chriswmackey** [comment]
Ladies and Gentlemen of the Bug and Bee!

It is with great pleasure that I finally close out this issue.  It has been a long time coming but I can say at last that all current "Non-WIP" Honeybee components are fully compatible with the "Export to OpenStudio" component.

Almost all of the features that we use in Honeybee could be written into the OpenStudio file with the exception of 4 abilities, which the "Export to OpenStudio" component supports by writing them into the IDF after it is exported from OpenStudio.  Hopefully, OpenStudio team will implement these things soon and I will switch the Export component over to write them in the .osm file.  These 4 features are:
1) CSV schedules
2) Natural Ventilation Objects
3) Any ShadeControl strategy that is not 'OnIfHighSolarOnWindow' (essentially all shadingControl)
4) Holidays

To help with the lack of CSV scedules, we have a new component by @AntonelloDN , which helps write schedules in the format that OpenStudio likes.

Additionally, to give a good reason for people to switch over to OpenStudio,14 major HVAC templates have been implemented on the OpenStudio component and they are as customizable as I can make them at present.  Furthermore, any HVAC feature that cannot be customized because the HVAC is simple will result in a warning to the user.

This marks the end of an era of tedious IDF writing.  Welcome to the dawn of the new age of OpenStudio!

**Comment by mostaphaRoudsari** [comment]
Thank you @chriswmackey! impressive...
