### ISSUE TITLE
Add in Humidistat

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#360]
I am adding in this issue as @ayezioro and @jacoposartore have requested it:
https://github.com/mostaphaRoudsari/Honeybee/issues/246
https://github.com/mostaphaRoudsari/Honeybee/issues/359

I have been keeping the humidistat low on the priority list as I have noticed that just conditioning a zone with an ideal air system includes a large restriction of indoor humidity ranges (by virtue of the fact that latent heat is removed by the ideal air system) and is not that greatly affected by further restrictions.  I imagine that the humidity issue will become more important when we start working in radiant systems and I hope the two of you who have requested it don't mind that I keep this low on the priority list until we get around to these radiant systems in the next few months.

-Chris

**Comment by ayezioro** [comment]
Sure!!
Thanks,
-A.

**Comment by jacoposartore** [comment]
No problem!
Thank you!
"Radiant systems"... great news! :thumbsup:

**Comment by antonszilasi** [comment]
@chriswmackey I'll give this a shot. I need some more practice with Open Studio

**Comment by chriswmackey** [comment]
This is now implemented on both E+ and Openstudio Components.
