### ISSUE TITLE
Glare Component Does Now Work With Most Recent evalglare.exe

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#361]
@mostaphaRoudsari ,

This was a bug that came up in the Rome workshop.  I had everyone download the most recent evalglare from http://www.ise.fraunhofer.de/en/downloads-englisch/software/evalglare_windows.zip/at_download/file.  This is currently what we tell everyone to do in our install instructions (https://github.com/mostaphaRoudsari/ladybug/blob/master/resources/Installation_Instructions.txt).

However, it seems that our current glare analysis component is not compatible with this recent release of evalglare.exe.  This is what I get when I try to run the component with the most recent evalglare installed:
![glarebug](https://cloud.githubusercontent.com/assets/5567574/9027556/f6978efa-3927-11e5-8d61-76f5bc5840a7.jpg)

A couple of students who had the old version of evalglare were able to run the calculation successfully so this seems just to be an issue of version compatibility.  I tried to fix this issue myself, @mostaphaRoudsari , but I think you would be able to do it 10 times faster.

In light of this, I am 100% behind the idea that we should package evalglare and falsecolor with the release of LB+HB (or have an automatic download or something). I know that you were playing around with this idea, @mostaphaRoudsari , and this seals the deal for me.

Here is the GH file that I was using in case this helps you fix things faster:
https://www.dropbox.com/s/hvx9tnhve5njp2y/evalGlareBug.gh?dl=0

-Chris

**Comment by ayezioro** [comment]
Hi,
I'm in doubt the problem is with Evalglare. I've just tried to broke my installed files and is still working. In the path, in my machine, it finds evalglare in Daysim/bin and Diva/DaysimBinaries (not in Radiance/bin. Weird). I changed the existing file with the one in the website and it runs OK. The version is 1.1.
I changed the name of the evalglare to something else but in the radiance\bin. Now i get Chris's error. It is not finding it in this location. When i change back the name in one of the previous locations it works.
This make me think that something with the radiance path definitions is not working as expected.
Right now i can't tell for sure which radiance version HB is using (Radiance\bin, or Daysym\bin, or Diva's).
Hope this helps to debug.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
I still get the error if I replace both the evalGlare in Daysim/bin and in Radiance/bin with the most recent one.  I don't understand what would be different about my case than yours, @ayezioro .  You have it in the DIVA folder and I don't but I feel that should not make a difference.
-Chris

**Comment by ayezioro** [comment]
Hi Chris,
Can you check your PATH for Radiance\bin or just check in command window "where evalglare" (without quotes).?
I'm suspicious that even though the utility is in the right folder the path to find it is not right.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

The paths where I have it are:
C:\Radiance\bin\evalglare.exe
C:\DAYSIM\bin\evalglare.exe

When I type "where evalglare" into a command window, I get "INFO: Could not find files for the given pattern(s)".

-Chris

**Comment by ayezioro** [comment]
Hmmm ...
So we now know the illness. Is not the version but the fact that the program is not found on the path.
If you were someone else i would ask: Are you sure evalglare is in (at least) one of those locations on your PATH? Maybe the name is not correct?
Weird.
Mostapha: Any words of wisdom here?
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
Yes, I can confirm that the program not being found on the path is also the reason why the component is failing (I have looked at the line of code that is trying to call evalglare).
As further proof to myself that I am not going crazy, I have posted images showing the locations of the two evalglare files:
![evalglare1](https://cloud.githubusercontent.com/assets/5567574/9111812/84ba3d3e-3c18-11e5-97ea-0a85cb808b6e.PNG)
![evalglare2](https://cloud.githubusercontent.com/assets/5567574/9111880/e23a697a-3c18-11e5-98a8-b1de83c8977b.PNG)

If it was just me that was having this problem, I would think that it was an anomaly but an entire class of 30 students experienced the exact same thing (only 2 students who had already had evalglare installed from a few months ago got it to work).  Let me know if my images differ at all from yours @ayezioro .
-Chris

**Comment by chriswmackey** [comment]
@ayezioro ,
I will report an update that did not fix the problem but is still significant.  I noticed that the evalglare files had been blocked on my machine and I have unblocked them.  This has still not fixed the problem but it might point us towards some other limiting feature of Windows that is stopping me from running the exes.
-Chris

**Comment by jacoposartore** [comment]
@chriswmackey,

one year ago, when I was tutoring in a workshop about Ladybug and Honeybee, most of the 30 students had troubles with daylighting simulation component not finding the radiance folder.

I then made sure that everyone checked their PATH variables under System Properties -> Advanced -> Environment Variables and, in case, add the missing paths.

See these pictures (they are in italian, sorry). Hope this helps.

![image](https://cloud.githubusercontent.com/assets/8501837/9112381/85614ecc-3c4e-11e5-88fe-a24052135b61.png)


![image](https://cloud.githubusercontent.com/assets/8501837/9112271/fce3df10-3c4d-11e5-8ba5-1c76c6210a11.png)


![image](https://cloud.githubusercontent.com/assets/8501837/9112176/5345cf7c-3c4d-11e5-81a9-da5887bbba62.png)

**Comment by ayezioro** [comment]
Chris, I was about to check the block thing. Maybe it is ReadOnly?
Check also the readability of the containing folder ... maybe is not the child but the father?
Check also in the file properties the security permissions. At least the read & execute should be checked. 

One detail that rings some bell for me is the date of your file. Mine is 29.1.2013 and yours 8.5.2015. I downloaded from the link above.
@jacoposartore: Chris has the Path OK for Radiance/Daysim stuff. Which is the weird thing.

I'm sure it is a silly thing. We will say that AFTER it is solved.
-A.

**Comment by ayezioro** [comment]
Forgot to say. Yes, your images are like mine.

**Comment by jacoposartore** [comment]
@ayezioro my evalglare.exe's dates are

C:\DAYSIM\bin  08/01/2013
C:\Radiance\bin  29/01/2013
C:\DIVA\DaysimBinaries 30/01/2013

All of the same size: 313.145 bytes

Chris's evalglare date is strange: evalglare.exe downloaded from Faunhofer's website is dated 29/01/2015.

**Comment by ayezioro** [comment]
Just to be all in the same page. This is the version i downloaded and installed:
https://www.dropbox.com/s/3fduthw366lixby/evalglare_v1.11_windows.zip?dl=0
It is version 1.1 from 2013.
-A.

**Comment by mostaphaRoudsari** [comment]
Hi all. Sorry for being so late to reply to this discussion. I believe it's an issue with path. @chriswmackey I just committed a new component. Can you please check and let me know if it works fine?

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Your new component fixed the issue!  Thank you!

@ayezioro ,
Thanks so much for the support with this it seems your intuition was right about the PATH.  I tried every other thing on your list before trying out the new component Mostapha committed.  I am still at a loss to explain what had changed over the last few months as I remember being able to run the glare analysis fine in March.
In any case I am glad that this is fixed now and I will close out the issue.

-Chris

**Comment by jtyow** [comment]
I'm having the same, using the latest glare component from Github. I've checked my paths and can't find the issue. thoughts?

**Comment by chriswmackey** [comment]
@jtyow ,
Are you using the version of the component that is from August 28th?  If so, can you send a screenshot of the error?  It might be the case that some systems want to have the Rad Path while others do not.
Hopefully, we can get to the bottom of this.
-Chris

**Comment by jarjarven** [comment]
Hi, all,
Comment from 2019. I am having a similar issue when I run the glare analysis, which warned me to download evalglare.exe from the link first. However, the link did not valid anymore. Could anyone share the evalglare.exe with me, please?
-Jarven

**Comment by mostaphaRoudsari** [comment]
Evalglare is now part of the official Radiance distribution. Try to download the latest version of Radiance.

**Comment by jarjarven** [comment]
@mostaphaRoudsari Thank you for your quick reply! I tried and it does work now!
