### ISSUE TITLE
Shading with Daysim has no .ill files out of the daylight simulation component

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#362]
@mostaphaRoudsari  ,

I will admit that I am not sure if this is just me not understanding how to run the components (so feel free to change the label or close the issue if its a simple explanation).

When trying to run a Daysim annual simulation with blinds, I am never able to get daylight autonomy values.  First, it would be great to know if this is the correct way to take into account dynamic shades in the Daysim annual simulation:
![dynamic shade](https://cloud.githubusercontent.com/assets/5567574/9027650/9e74f560-392b-11e5-8174-f7d5fe91ca8f.PNG)

If this is correct, I would like to know why I am not getting any .ill files out of the daylight simulation component.  I can see that I get .ill files in the study folder:
![no ill files from component](https://cloud.githubusercontent.com/assets/5567574/9027783/849d49e4-3930-11e5-9840-e74f49af0af5.PNG)

Is it just that I am only supposed to use the study folder and that I do not get the .ill files out of the daylight simulation component? If so, is there a currently-implemented method for understanding this data tree of results and paring it into DLA and cDA?  Plugging the data tree into the readAnnualResult component does not seem to work and gives me the following warning:
![annualanaylsis with shading_nodla](https://cloud.githubusercontent.com/assets/5567574/9027791/ca2c449c-3930-11e5-9b46-7de7e469a2e9.jpg)

Here is the GH file that I am using:
https://www.dropbox.com/s/p1cgdczisyr9im0/CantGetDynamicShadeToWork.gh?dl=0

Once I understand this, I am going to start working towards integrating the dynamic shading of Daysim with the dynamic shading in E+ (which will have a whole set of new features that @ayezioro  has been waiting for).

-Chris

**Comment by ayezioro** [comment]
Hi Chris,
Tried your file with no success but i also get this:
![capture](https://cloud.githubusercontent.com/assets/7526023/9032232/1dc2a3a0-39c5-11e5-9be3-420c7902a7cb.PNG)
It happens 2-3 times in the same run.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
Thanks for testing this out on your machine.  Something certainly seems to be matter.

@mostaphaRoudsari ,
Please let us know if you have any suggestions.  I get the sense that you would be able to explain this issue WAY faster than it is going to take me to figure out.  I can also help edit the components once I understand what is supposed to be happening.

-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey I will take a look at this soon [=early next week]. The workflow should work. Branch checking warning is a bug that I think happened once I get it fixed for advanced dynamic blind simulation with daysim. In general you probably don't want to use the conceptual Daysim's blind anyways. It's very simplified.

Abraham's issue is a famous Daysim's issue/bug that hasn't been solved for a long time now. Not much that we can do about it.

Let's talk about the integration of Daysim and EnergyPlus. I wonder if using Radiance's 3-Phase method is what we really should consider for the next steps of integration. Daysim has so many limitations and even after all the flexibility that Honeybee provides you can't go that far. Rob has already implemented this for OpenStudio which we can use as a great reference. 

I will meet Rob in Radiance's workshop next week and will ask him and Andy couple of questions that I have about the process. I should be able to get 3-Phase implemented for Honeybee afterwards.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

Thanks for the response and I definitely agree that using radiance functions directly instead of having to go through Daysim would be ideal.  That famous Daysim bug seems to be the clearest indication to me that Daysim is not keeping up on its bug-fixes and compatibility.  How long has this famous bug been around?  

I am very anxious to hear what you find out from Andy and, if you have any idea of a time frame in which such capability might be implemented after you talk, it would help me to decide when and how I should implement integration of these daylight results with E+ dynamic shades and OpenStudio.

I will hold off on the development of this until after you talk so that we can make the best decision.
-Chris

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I don't intend to have 3-phase implemented by the next stable release but I think that we should do something to address this clear bug for this release (even if it means taking out the Daysim shading components for the release until we get 3-phase working).
I am adding it to the milestone for this reason and let me know what course of action you would recommend.
-Chris

**Comment by chriswmackey** [comment]
I should also note that the general 3-phase implementation referenced in this issue is covered here:
https://github.com/mostaphaRoudsari/Honeybee/issues/290

**Comment by mostaphaRoudsari** [comment]
@chriswmackey this is fixed now. It was two mistakes in checking the number of result files and sorting the outputs. You may want to read [here](http://daysim.ning.com/page/daysim-header-file-keyword-simple-dynamic-shading) to understand how conceptual dynamic shading in Daysim works. Back to EnergyPlus integration OpenStudio is definitely the way to go. Rob has already figured it out so unless we find a limitation there I would say we should make or workflows on top of his work.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Awesome.  Thanks for fixing this and for the info.  Very excited for the fusion of HB with OpenStudio that seems immanent.
-Chris
