### ISSUE TITLE
Add an input to let users name glazing surfaces

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#363]
This can be added to addGlzSrf component. Check this discussion: http://www.grasshopper3d.com/group/ladybug/forum/topics/how-to-specify-a-new-for-a-glazing-surface?commentId=2985220%3AComment%3A1340839&xg_source=msg_com_gr_forum

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I agree that this would be super-useful!  I just had someone ask me about this the other day.
-Chris

**Comment by mostaphaRoudsari** [comment]
![image](https://cloud.githubusercontent.com/assets/2915573/10925048/f5df97e4-8258-11e5-86ea-bf732b6a2aa0.png)
