### ISSUE TITLE
Checking Surface Normals Is not Working

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#365]
@mostaphaRoudsari ,

I have been at this problem for 8 hours and I imagine that you could probably fix it in one as you know all of the code you wrote to check surface normals much better than I.  I have finally realized that this is the bug behind some huge inaccuracies that I have been experiencing with the solar calculation and, right now, this seems to me to be the biggest threat to people considering Honeybee simulations accurate.

What is boggling my mind is that, even though the surface normals are being correctly defined for the HBSurfaces, they are not being written correctly into the IDF, which makes me think that there is something wrong with the function that checks to be sure that vertices are written counter clockwise into the IDF.

Here is am image showing the normals as defined by HBSrf.normalVector:
![correct hbsrfs](https://cloud.githubusercontent.com/assets/5567574/9297375/965dc3ec-446c-11e5-8a23-587022ddac25.PNG)

And here is an image of a re-imported IDF after it has been created by the Run Simulation component:
![badnormals](https://cloud.githubusercontent.com/assets/5567574/9297378/9ae83b72-446c-11e5-8857-6194ec5a29f1.PNG)

As you can see, one of the surfaces is not being written into the IDF correctly.  This results in huge inaccuracies of the solar calculation, changing from an incorrect 141 kWH of annual solar to a correct 486 kWh.  I have noticed that, if I flip the geometry before plugging it into the createHBSrfs component, I can write the file correctly into the IDF.  But this defeats the entire point of checking the normals of surfaces.  If we can't get this to work, I feel that we should do away with automatically checking normals for people as it will lead to some dangerous cases otherwise.

A GH file that explains the problem is here:
https://www.dropbox.com/s/19zrcayz59nyw8l/CheckNormalsBug.gh?dl=0

When you get the chance, @mostaphaRoudsari , please help me out.  This one has been a huge thorn in my side for a long time that I just can't seem to figure out.

-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey I ran a quick test and it looks to be an issue only when you create the zone surface by surface. I guess this is just a bug with the initial check normal in create HB Zones from surfaces, and not with point sorting function. otherwise it should have produced wrong results for all cases. Will check and try to fix it tomorrow. Thanks for reporting.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey I needed to flip the baseplane for HBSurface when flip the surface itself. I added the line. If you check the latest Honeybee it should work fine.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
You are awesome.  Thank you for fixing this.
Now that we have the simple geometry case fixed, I am going to try to address one for more complex geometry unless you get to it first.  The current normal-checking function fails whenever you have an L-shaped zone that is shallow enough that the volume centroid lies inside the L.  I have been exploring a couple of ways to fix this case (either doing a quick ray-tracing check or using McNeels functions that check to ensure closed solids have normals facing the right direction).  Once I have decided which method is more reliable and fast, I will implement it.  Let me know if you have any other ideas to address this case in the meantime.
-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey thanks. That sounds good to me. I'm really not sure what is the best way to address the issue. While you're thinking about this an interesting somehow related issue is handling non-convex surfaces (e.g. L shaped surfaces). It would be great if we catch them and break them down in convex surfaces.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
The normals bug has finally been fixed.  Now, this L-shaped case that would have failed previously:
![oldnormalbug](https://cloud.githubusercontent.com/assets/5567574/9459103/6e38f9a4-4ac5-11e5-9901-46f45a770330.JPG)

Is checked and corrected:
![normal bug fixed](https://cloud.githubusercontent.com/assets/5567574/9459107/7323f0a4-4ac5-11e5-9879-84c931aac39f.JPG)

While I was at it, I also fixed this normal-checking function for curved geometry, although it still seems difficult to get the meshing function to obey this normal down the pipeline (it seems this curved geometry support is a task for another day).

I looked through the E+ Input/Output reference and it seems that the E+ solar distribution function does not support any non-convex zones (not non-convex surfaces as you seem to be implying here).  Here is the page from the E+ v 8.1 Input/Output reference that describes it:

It's page 64 of the whole document. Let me know if I am misunderstanding you.
![convexzonesinputoutputref](https://cloud.githubusercontent.com/assets/5567574/9459101/67f54728-4ac5-11e5-9258-17f47c13bba2.JPG)

-Chris

**Comment by mostaphaRoudsari** [comment]
Nice! I need to give it a try. Back to your question based on this discussion it is both: https://unmethours.com/question/1326/non-convex-surfaces-in-energyplus/

Spliting a non-convex zone to a convex zone can be tricky though. I can also see it as [a wish](https://energyplus.uservoice.com/forums/258860-energyplus/suggestions/9314436-calculate-interior-solar-distribution-for-concave) on EnrgyPlus's user voice website. Maybe we should leave this to EnergyPlus team to get it solved from the core and vote up the wish on the website.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I agree that this is something that E+ team really should fix if they want people to use it.  I voted for the wish and, hopefully, they come through in the near future.
-Chris
