### ISSUE TITLE
Issue with custom schedules for AddEarthtube 

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Honeybee#367]
This was previously working but now it is not has something been changed in Run Energy Simulation?
@mostaphaRoudsari  @chriswmackey

**Comment by antonszilasi** [comment]
Solved

**Comment by mostaphaRoudsari** [comment]
@antonszilasi what was the issue?

**Comment by antonszilasi** [comment]
Dont worry just my own stupidity nothing to worry about wasnt using most up to date components
