### ISSUE TITLE
Add Component to Re-Evaluate Zone Geometry

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#373]
As per this discussion:
http://www.grasshopper3d.com/group/ladybug/forum/topic/show?id=2985220%3ATopic%3A1356815&xg_source=msg

**Comment by mostaphaRoudsari** [comment]
I added my comments here: http://www.grasshopper3d.com/group/ladybug/forum/topics/modeling-high-rise-buildings-in-hb?commentId=2985220%3AComment%3A1359669&groupId=2985220%3AGroup%3A658987

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I remember you said on the GH group topic that you would give this component a shot. Given this and that you probably understand how to do this better than I, I am transferring the issue assignee to you.  If the issue is not addressed within a few more months, I will tackle it myself.
-Chris
