### ISSUE TITLE
Finish the Export to LBNL THERM

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/honeybee#382]
I just wanted to create this issue to that we have a forum to discuss how I am building out the connection form Honeybee to THERM.  Here is the description of the workflow and the accompanying image:

![generalthermworkflow](https://cloud.githubusercontent.com/assets/5567574/10265139/869c40a0-69f1-11e5-80ce-a98f5c9ecf74.JPG)

You will draw closed polygons and polylines for boundary conditions in Rhino, assign materials and temperatures/filmCoeffs to them with Grasshopper components that I am developing, and then plug them all into a component that writes out a THERM XML that is ready to simulate.  This XML-writing component will also do a thorough check on your geometry so that you know if it is incorrect before you go over to THERM (thereby allowing you to avoid THERM's difficult drawing interface completely).

The other big efficiency gained through this workflow (other than avoiding the THERM drawing interface) will be coordination of THERM materials with materials used in EnergyPlus simulations.  In the attached image, you see that I am assigning materials to the THERM polygons from the OpenStudio material library (using the Honeybee component in the upper-right corner). I am also planning to write a couple of components to read the default THERM library into grasshopper and a component that allows you to easily create THERM materials from scratch.  If you have any other libraries that you would recommend I import to Grasshopper (I remember you mentioning that there are libraries in WINDOW), please let me know.

Finally, there will be a component to read results back into Rhino/Grasshopper from THERM after the simulation has been run so that you can do customized analysis and visualization of these results in Rhino/GH.  I was hoping to keep the whole interface in Rhino/GH and avoid the THERM GUI altogether but I would need their API to automatically run the THERM file that I am planning to write and this API is not free yet.

**Comment by Kristoffernegendahl** [comment]
Hey Chris. This is amazing. Just updated the HB objects and saw the WIP Therm polygon module. The final objective to completely bypass the THERM GUI is fantastic. Until now I have avoided THERM because of the many frustrations of the drawing GUI. But using GH/Rhino as an exporter with quality check is just making me wanting to use therm in all projects. Looking forward to see the implementations. Also I've asked here at my University if we've got any other material libraries. We probably have a few "new" materials such plastic composites and some special glazing units. I will try to add the to the library when it's ready. Also when the results can be fed back to the GH-environment it would be fantastic to implement the two different methods to calculating U-values. (American/EU-standards) e.g.  https://www.researchgate.net/publication/268288709_COMPARISON_OF_CALCULATIONS_OF_THERMAL_TRANSMITTANCE_OF_WINDOWS_USING_TWO-AND_THREE-DIMENSIONAL_MODELS#full-text

**Comment by chriswmackey** [comment]
This issue finished a long time ago and I'm happy to say that all of your suggestion has been implemented @Kristoffernegendahl !  I'm closing out the issue for now.
If you manage to consolidate your material library into a CSV, feel free to post it here and I will work it into the Honeybee THERM Library.

**Comment by TheodoreGalanos** [comment]
Hi @chriswmackey This is pretty cool! Don't want to reopen the issue just wanted to ask if this will involve (in the future) the connection to Energy models.

I seem to remember you saying it's a bit tricky to connect therm materials to E+ simulations. Do you think that can be possible? Additionally, if we can now calculate the construction U value, what would be the best way to connect this information to the Energy model (given that the no mass materials might not offer the higher accuracy)?

Hope I made sense. Thanks a lot in advance.

Kind regards,
Theodore.

**Comment by chriswmackey** [comment]
@TheodoreGalanos ,
This example file shows the current means of integrating THERM results with a Honeybee Energy Simulation:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Thermal_Bridging_with_THERM_and_EnergyPlus&slide=0&scale=1&offset=0,0
Admittedly, I think the process might be streamlined a bit more but the way I would recommend is by either just plugging in a calculated window U-Value into an E+ simple glazing material or by adjusting the thickness or conductivity of an insulation layer in the case of opaque wall/roof/floor constructions.
-Chris

**Comment by TheodoreGalanos** [comment]
@chriswmackey Thanks a lot! I hadn't tried that cabapility nor seen the example file.

Will give it a shot.

Kind regards,
Theodore.
