### ISSUE TITLE
Remove Window by name functionality added to Honeybee_remove Glazing and some questions

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Honeybee#383]
@mostaphaRoudsari 
@chriswmackey 
Mostapha,Chris

I've added functionality to Honeybee remove glazing so that you can remove a window just by its name. Its in my latest pull request.

The users can get the name of the windows from the component LabelSurfaces. However I noticed (Please see the screenshot), that in the case of child surfaces the names given in the component createHBsrfs are re-assigned in the component addHBGlz.

Is there a reason for this? Can I rework the code so that the names are kept throughout?

Anton,

![namesofsurfaceschanged](https://cloud.githubusercontent.com/assets/8773483/10316292/1d54216c-6c4e-11e5-8c0b-1b47a5a0dbce.PNG)

**Comment by antonszilasi** [comment]
@mostaphaRoudsari @chriswmackey 

After doing some beta testing with Nick Novelli I'd like to remove the srfIndex and Pattern inputs on the component Honeybee remove window. As we found that these inputs can be very confusing and unclear and it makes more sense to simply have the option to remove windows by window name.

Let me know what you think,

Anton
![1](https://cloud.githubusercontent.com/assets/8773483/10344946/b6457d22-6d15-11e5-82c9-9b77066622e8.PNG)

**Comment by chriswmackey** [comment]
@antonszilasi ,
I could see this as a good idea. Perhaps you can sense whether a given input is an integer and, if not, search for the name. This way, you can keep both functionalities.

As far as the naming of glazing goes, EnergyPlus needs trapezoidal widows to be broken up into two triangles and this may be one reason for the renaming. Another reason might be related to this issue:

https://github.com/mostaphaRoudsari/Honeybee/issues/363
-Chris
