### ISSUE TITLE
Come up with a better default naming convention for HBZones when multiple Mass2 Zone components are used

### ISSUE THREAD

**Issue by gdemichele** [mostaphaRoudsari/Honeybee#388]
Got all the zones (with same orientation) one on the other. See the discussion at the following link
http://www.grasshopper3d.com/group/ladybug/forum/topics/problem-with-the-solve-adjacencies-component?commentId=2985220%3AComment%3A1379925&xg_source=msg_com_gr_forum

**Comment by chriswmackey** [comment]
@gdemichele ,

I am changing the name of this issue to be more specific about the conclusion that came out of the grasshopper discussion (which is that Honeybee needs better default names for zones).

We will hopefully address this soon,
-Chris

**Comment by gdemichele** [comment]
That's perfect Chris, I am not so familiar with "bug reporting" so any advice is welcome.

Good work,
Giuseppe

**Comment by chriswmackey** [comment]
@gdemichele ,
I had addressed this issue with a commit:
https://github.com/mostaphaRoudsari/Honeybee/commit/e01ab83c5a1fe6bc39be8dd8c5cdd012c4d70465
Now, you won't end up with duplicate zone names if you take the default.
-Chris
