### ISSUE TITLE
Assigning new construction fails in OpenStudio component

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#392]
See [this](http://www.grasshopper3d.com/group/ladybug/forum/topics/unable-to-re-assign-constructions) discussion.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

I had to fix this bug for work anyway.  Closed:
https://github.com/mostaphaRoudsari/Honeybee/commit/57d8e42c1a71f46336d5451bd934beb8a40ee5e3

**Comment by mostaphaRoudsari** [comment]
Thanks @chriswmackey!
