### ISSUE TITLE
Can't Figure Out How to Get the Airside Economizer to Reduce Cooling Energy

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/honeybee#393]
@chiensiTB ,

I have been trying for 3 hours now to get the airside economizer to reduce the cooling electric energy used by a chiller but it inevitably increases the cooling by a small margin no matter what I do toyour component.  I am working in San Francisco, which I know is supposed to be a good climate for economizers.  You can see my file that is giving me the issue here:
https://www.dropbox.com/s/ema3uqvsr6jdcnb/NatVentPatientRoomEnergyModel.gh?dl=0

Whenever I connect up your details with an economizer attached, the cooling jumps from 189 kWh to ~200 kWh. I notice that the economizer is also increasing the fan energy, as expected, but I would also expect to see this accompanied by a decrease in cooling.

I have watched your video twice and I still can't figure out what is going on.

Please help.
-Chris

**Comment by chriswmackey** [comment]
I should also mention that any knowledge shared here will be written into the component descriptions and our new gitbook documentation that @mostaphaRoudsari put together. This way others will hopefully be able to avoid this problem in the future.

**Comment by chiensiTB** [comment]
Hi Chris-

I'm going to take a look at this now.

**Comment by chriswmackey** [comment]
Awesome. Thank you. IT may just be an issue with the control s that I have not been able to crack yet.

-Chris

**Comment by antonszilasi** [comment]
@chiensiTB  Hi Chien Si are you available to discuss your Open Studio components over Skype? I am trying to finish them off where you left off. If you are please add me on Skype - anton.szilasi. Oh and by the way I hear we are co-workers at P+W ; ).

**Comment by chiensiTB** [comment]
Hi Anton-

Sure, we can do that.  Thanks for reaching out.  I'm not working at P+W by
the way, I'm just helping Ben out to get his project underway.  Is there a
good time to reach you?

Cheers,
Chien Si

**Comment by chriswmackey** [comment]
@antonszilasi and @chiensiTB ,

Let's plan a time to meet together.  Chien Si, in case you don't have it, my skype name is mackeyarchitecture.  I can do any time after work on Wednesday or Thursday of this week.  Otherwise, Saturday is good.

-Chris

**Comment by chiensiTB** [comment]
Hi guys-

That sounds fine to me.  I can only do Wednesday night or Saturday.

**Comment by chriswmackey** [comment]
@chiensiTB  and @antonszilasi ,
Now that I am looking at how busy tomorrow is, let's go for Saturday.  Shall we say Saturday morning for the sake of Anton in Portugal?
-Chris

**Comment by chiensiTB** [comment]
Saturday morning is fine for me, not a problem.

**Comment by antonszilasi** [comment]
@chiensiTB @chriswmackey  Could we shoot for Saturday morning your time. That would be best for me. I'm on GMT time. Thanks guys! Also Chien Si your TerraBuild email isn't working.

**Comment by chriswmackey** [comment]
@chiensiTB  and @antonszilasi ,

Shall we say Saturday morning at 10:00AM EST over skype?

Also, my original reason for making this post has now been fixed.  So, once we all decide on the time, let's close out the issue.

-Chris

**Comment by antonszilasi** [comment]
@chriswmackey @chiensiTB  Sounds good to me although I think ChienSi is in LA so that would be early for him.

**Comment by chiensiTB** [comment]
I'm in New York, so it is fine with me.

**Comment by antonszilasi** [comment]
@chiensiTB  I sent a invitation to your terrabuild email for 10 am EST.

I'm thinking discussion points are:

- Chris's economizer question 
- A discussion regarding what you intended for the AirhandlerDetail component and what remains to be coded. I'm starting to get my head around the OS SDK so if you point me in the right direction I should be able to finish this component for you.
- A brief outline of what remains to be coded in the other OS components so I can have a crack at finalizing these as well.

**Comment by chiensiTB** [comment]
From now on, please use my gmail account.  I am switching domains and hosts
so that email will be down indefinitely.

Guys, I'm happy that we're doing this.

I think generally the approach is good.  See you at 10!

**Comment by chriswmackey** [comment]
Gosh, this was an old issue.  Thanks to Honeybee HVAC, this is all addressed now and I pretty much always see savings when using an economizer on an all-air system.
