### ISSUE TITLE
Wish - Add wall cavity and exterior naturally vented cavity

### ISSUE THREAD

**Issue by jacoposartore** [mostaphaRoudsari/Honeybee#394]
Hi there,

I was wondering whether the evaluation of opaque ventilated façades will be implemented in the future. I read that's actually done in EP, respectively, by creating a Material:AirGap with thermal resistance and by adding the "SurfaceProperty:ExteriorNaturalVentedCavity" to the related surfaces.

**Comment by chriswmackey** [comment]
@jacoposartore ,

EnergyPlus can model trombe walls and ventilated cavities this way but I have always preferred to model such cavity spaces as separate zones, which I feel does a better job modeling the ventilation and the solar distribution calculation.  You can use the setEPAirflow component to naturally ventilate the cavity to the outdoors (assuming that you use the custom stack and wind object on the cavity and set the wind discharge coefficient to 0).  You can also use air walls and a mixing schedule on the SetEPAirflow component to model when such a cavity might be open to the interior.

Let me know if this sounds good or if you find there is some benefit to modeling the vented cavity in the way that you specify that I am not aware of.

-Chris

**Comment by jacoposartore** [comment]
Thank you @chriswmackey, this seems a clever and more detailed alternative.
So do you basically add another zone with the thickness of the cavity? Could you provide a simple example file?

What about unventilated cavity wall? I read that this could be implemented by creating an air space layer like it's done currently with window's air cavities (http://bigladdersoftware.com/epx/docs/8-0/input-output-reference/page-010.html#materialairgap).

**Comment by chriswmackey** [comment]
@jacoposartore ,
I apologize that the file is so large but you can find an example of a ventilated double-skin facade here:
https://www.dropbox.com/s/vz2e1jxk5i1qinh/VentedCavityExample.gh?dl=0

If you understand it, please close out the issue.
-Chris

**Comment by jacoposartore** [comment]
@chriswmackey,
I used your file as a reference to create a new one from scratch to simulate the impact of both the unventilated and the ventilated wall cavities.
Here it is (https://www.dropbox.com/s/llodsxxojfwmlqb/EPUn-VentilatedWallCavityREV1.gh?dl=0).

I used this paper (http://porto.polito.it/2517736/1/BSA_2013_Corrado_et_al.pdf) and this presentation (www.e3lab.org/upl/website/publication111/ventfacade.pdf), which explain what I wanted to model, to adjust the coefficients Cw (0,25) and Cd (0,65).

Could you please check if the file seems ok to you? Thank you.

**Comment by chriswmackey** [comment]
@jacoposartore ,

I apologize for getting back so late.  I checked your file and things are looking great and there are only 2 changes that I would make:

1) I am guessing that you do not get any wind-driven ventilation (aka. cross ventilation) through these air cavities.  As such, you should just set the wind discharge coefficient to 0.

2) Your stack discharge coefficient is correct but I should also clarify that the area in this case of two openings should be an effective between the two openings and not the total area of the two.  When you have two equal-sized openings, your area should just be the area of one of the openings.  When they are of two different sized openings, you have to calculate an effective area using this formula:
![effectivearea](https://cloud.githubusercontent.com/assets/5567574/11007253/a797f438-8496-11e5-93d4-1893dc59fcb0.JPG)

Here's my old formula cheat sheet of all these formulas from MIT in the event that it is helpful
https://www.dropbox.com/s/jge9v7pavm6j7jr/Architects%20Guide%20-%201.pdf?dl=0

Once you change those two things, everything should be good.  And I should also say well done.  You are the only other person I know who has used Honeybee for this type of ventilated area scenario other than myself.

Stay awesome,
-Chris
