### ISSUE TITLE
Finish Implementing Zone-Level Airflow Rates for OpenStudio

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#396]

**Comment by chriswmackey** [comment]
@antonszilasi and @chiensiTB ,

After realizing that the specifications of outdoor air and recirculated air really need to be assigned on the zone level and not the overall system level, I have now ensured that the outdoor air specifications on the "Set Zone Loads" component will influence the functioning of the OpenStudio HVAC systems:
https://github.com/mostaphaRoudsari/Honeybee/commit/d96f55ce0835b298ed124bece4adf83bef2d0c93

I have also added a "recirculatedAir" input to this component, which is usually set to 0 but can be bumped up for things like hospitals and clean rooms.

This takes some of the burden off of the Air Handler component to assign the Air Flow and Outdoor Air Flow, which I realized gets really tricky when you have central systems.  I see this also as a general strategy that the OpenStudio HVAC components will handle just the stuff related to systems over the whole building.

I will post an example file showing how this works soon.
-Chris

**Comment by antonszilasi** [comment]
@chriswmackey 

Is this something that I can do?

**Comment by chriswmackey** [comment]
@antonszilasi ,

For now, I think that the best we can do is try to apply the components to a number of cases to understand the best way of organizing zone vs system level inputs (or at least understand what needs to be a zone level input and what needs to be a system level input).  Right now, it is a bit of a redundant mess between the two.  I am gaining some clarity as I apply them to projects at my office for the 7 - VAV system.  If you give me a little more time with this, I think that I will understand the best way of organizing this and I can make this organization a reality for the 7- -VAV system.  Then, we can combine any insights that you might gain from experimenting from the systems and we can develop a consistent template that we apply to all systems.

-Chris

**Comment by antonszilasi** [comment]
@chriswmackey completely agree. Let me know when you're ready to chat about a consistent template at the moment it seems like its a big mess. I'll just go through the code bit by bit with Chien Si and try to understand it. Then when you are ready all 3 of us can chat about a consistent template.

**Comment by chriswmackey** [comment]
I think that all that we need to assign on the zone level is the airflow rates and this will be done through the set Zone Loads component.  So there will be no need for an additional component.

-Chris

**Comment by chriswmackey** [comment]
This has been addressed with the new implementation of ASHRAE Baseline systems.  Everything is assigned on the zone level and, in the event that we need recirculated air, I automatically, hard size some elements of the HVAC system to make sure that we get enough.
