### ISSUE TITLE
Read EP Result not showing the airHeatGainRate output

### ISSUE THREAD

**Issue by jacoposartore** [mostaphaRoudsari/Honeybee#399]
Hi there,

I updated the components with the latest release this morning (terrific update, by the way) and I wasn't able to get that output anymore, even starting from a fresh definition as shown here.
![image](https://cloud.githubusercontent.com/assets/8501837/10881046/fb1abff8-815f-11e5-898b-3698510297b3.png)
![image](https://cloud.githubusercontent.com/assets/8501837/10881068/1ac0bbe6-8160-11e5-95aa-ce305d1d7101.png)
https://www.dropbox.com/s/axl8xboajuqeam2/ReadEPResultMissingOutput.gh?dl=0

**Comment by chriswmackey** [comment]
@jacoposartore ,

Thank you so much for posting this issue.  It was a bug that resulted from a change I made to include fan/pump energy from OpenStudio  runs.  You can find your fixed file here:
https://www.dropbox.com/s/pyvcqfbpdo1gsks/ReadEPResultMissingOutput_CWM.gh?dl=0

-Chris

**Comment by jacoposartore** [comment]
Great, thank you!
