### ISSUE TITLE
Release Notes!

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#406]
Thank you @chriswmackey!

**Comment by chriswmackey** [comment]
@mostapharoudsari ,

I can have this ready to go within a day. If you have time to skim over what I put together shortly after I finish, we can publish the release notes closer to when we update the food4rhino links. Let me know if this sounds like a good idea or if you would rather wait until the weekend as we discussed.

-Chris

**Comment by mostaphaRoudsari** [comment]
Thanks @chriswmackey! Let's take it easy and post it during the weekend? 1. You won't get burnt out. 2. We will have a grace period for knowing about any potential major bugs for the new release. I will use the latest version this weekend which will be another place to make sure everything works as expected.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
Great.  The plan makes sense and you are right that I appreciate the extra time.
