### ISSUE TITLE
unknown checkIfTransformed error thrown

### ISSUE THREAD

**Issue by moethu** [mostaphaRoudsari/Honeybee#409]
Hi Mostapha,
I tried to traceback this error but I cannot find the Library where the checkIfTransformed method is in.
The geometry hasn't been moved or modified.
Thanks for your help.
 
![capture](https://cloud.githubusercontent.com/assets/8201465/10967007/4fbc6cd6-83af-11e5-9719-1c941de73a0f.png)

**Comment by mostaphaRoudsari** [comment]
Hi Max! This is in Honeybee_honeybee. The class name is Honeybee_Hive. I just landed. Will take a look as soon as I can. Thanks.

**Comment by mostaphaRoudsari** [comment]
I can't recreate the issue. What are your units and tolerance? The code probable needs to be more forgivable bit to catch cases like this.

**Comment by mostaphaRoudsari** [comment]
@moethu I made the check less restrict (032c3027ba65580cd172c23704c4af3285f4c24f). Can you please update Honeybee_Honybee component and try again. Let me if the issue persists.
