### ISSUE TITLE
global name 'north_' is not defined

### ISSUE THREAD

**Issue by elsamullin** [mostaphaRoudsari/Honeybee#410]
Hi mostapha, I'm trying to connect epw file to the updated annualDaylightSimulation component and have a "global name 'north_' is not defined" error in the updated component.

It looks like the older version of the component had the lines below, and they are not in the new script. Could this be the issue?

def main():
    north_ = 0

Thanks!

![capture3](https://cloud.githubusercontent.com/assets/15670175/10967457/b95374ca-83b2-11e5-8c58-207f27d8e029.PNG)

**Comment by mostaphaRoudsari** [comment]
Hi @elsamullin. I removed the line as now it's implemented and you can set north direction for annual analysis. Re-insert the component from Honeybee tab to solve the problem.

**Comment by elsamullin** [comment]
@mostaphaRoudsari  thank you!
