### ISSUE TITLE
Get Zone EnergyPlus Loads calculation error

### ISSUE THREAD

**Issue by jacoposartore** [mostaphaRoudsari/Honeybee#411]
Hi there,

I have used this component and when comparing the results with the older Get EnergyPlus Loads component there are discrepancies due to the conversion ft^2-to-m^2, that is no longer needed.
![image](https://cloud.githubusercontent.com/assets/8501837/10972223/8e1c04cc-83d8-11e5-844a-24d7613548ae.png)

**Comment by mostaphaRoudsari** [comment]
Thanks @jacoposartore for reporting this. I assume you're using the updates json library? Is that right?

**Comment by jacoposartore** [comment]
Yes, it's the one you updated 3 days ago..

**Comment by mostaphaRoudsari** [comment]
Great. Just wanted to make sure. That means that all the values in the new OpenStudio_Standard.json are in SI and not in IP anymore. @macumber can you confirm this?

**Comment by mostaphaRoudsari** [comment]
My bad! OpenStudio file is still the same. New Zone load components don't need the conversation as it has already being made under the hood. I will get this fixed now.

**Comment by jacoposartore** [comment]
Great, thank you @mostaphaRoudsari.

**Comment by mostaphaRoudsari** [comment]
Thanks @jacoposartore! Should be fixed now.

![image](https://cloud.githubusercontent.com/assets/2915573/10972953/8005f264-83a9-11e5-94ec-f5140a75eb8e.png)

**Comment by macumber** [comment]
I believe the standards are still in IP, the repo is here if you are interested:  https://github.com/NREL/openstudio-standards

@asparke2 is the main contact for the standards
