### ISSUE TITLE
addHBGlz child surface issue

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#412]
Hi,
Just before the official release i think there is a bug in the HB_addHBGlz.
Connecting multiple surfaces to the _childSurfaces input i'm getting the following:
1. Solution exception:'tuple' object has no attribute 'isPossibleChild'
I was updating one of the examples in Hydra.
-A.

**Comment by mostaphaRoudsari** [comment]
Hi Abraham! I thought I just fixed the issue this morning! http://www.grasshopper3d.com/xn/detail/2985220:Comment:1395481

What's the date of the component that you're using?

**Comment by ayezioro** [comment]
Hi Mostapha,
First of all you can close this one.
I updated the file and somehow it get the Nov 5 version. Now i updated again and it is 7 Nov and it is working.
So probably i get something between the cracks of the update.
Sorry and thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
Great and thank YOU!
