### ISSUE TITLE
Radiance library materials issue

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#413]
Hi,
Hoping again i'm doing something wrong ...
I'm having issues using the HB_callFromLibrary. It turns red with the following:
1. Solution exception:'dict' object has no attribute 'type'
All components are updated to Nov_07. The HB_HB says that 27 materials were loaded from library, but still i can't get materials from library.
Moreover, in the same case i defined a glass material with the HB_radGlassMaterial, connect it's output to the HB_addHBGlz -- RADMaterials and i get the following red error:
1. Solution exception:void glass glass_material
0
0
4 0.436 0.436 0.436 1.520
 can't be find in library
I added it to the library, but still no use.
Those files used to work. But for now i'm linking the hydra https://www.dropbox.com/s/a0zyr8vvfpsqwko/Mutiple_constructions_and_names_for_windows_AY.gh?dl=0 with the addition of radiance materials.
Appreciate your help and insights.
-A.

**Comment by mostaphaRoudsari** [comment]
![image](https://cloud.githubusercontent.com/assets/2915573/11022659/18b9b4e8-8632-11e5-8a14-b22e61486ce9.png)

**Comment by ayezioro** [comment]
Great!
Thanks.
-A.
