### ISSUE TITLE
Question on Integrated Daylight and Energy simulation Example file

### ISSUE THREAD

**Issue by agusHariyadi** [mostaphaRoudsari/Honeybee#416]
@mostaphaRoudsari 
about your example on Integrated Daylight and Energy simulation, in http://hydrashare.github.io/hydra/viewer?owner=mostaphaRoudsari&fork=hydra_1&id=Integrated_Daylight_and_Energy_simulation
this example was very interesting for me..
When I see the result, the reduce of lighting energy was very dramatically, more than 99%.
Correct me if I am wrong..
But when I see the zone program, It was apartment which people usually use in the night, this result was too good to be true..
then I compare the result with the my modification using the native  daylight control from energy plus (I usually done in open studio legacy and now I added to your grasshopper definition), the result is very different, the reduce is around 40%.
Then I try to figure out what happen with the lighting schedule, It seem that when we use annual profile from Daysim result, the schedule became very strange (I think) if we use as lighting schedule because when there is no sun, it become zero or off, so the light only on from around 4 PM until 6 PM when the light is not sufficient for the target illuminance, and some days are off 24 hours.
I think maybe this Daysim approach is better to simulate daylight efficiency than native daylight control but It should be combine with the schedule when there is no sun.
What do you think?
https://www.dropbox.com/s/k5zbh3ndecx9nlj/Integrated_Daylight_and_Energy_simulation_DCEP.gh?dl=0

**Comment by mostaphaRoudsari** [comment]
Hi @agusHariyadi. I agree that the schedule generated by daysim is strange. I used different schedules as the occupancy schedule and I get very different results. I will check your file and let you know the conclusion. Thanks.

**Comment by mostaphaRoudsari** [comment]
Hi @agusHariyadi. I ended up checking the source code to find why this is happening. As far as I can see in the source code Daysim can't handle partial occupancy which EnergyPlus does indeed support. This creates multiple limitations in the way daysim calculates the schedule. Here is the comparative results after the final modifications of the code.

![image](https://cloud.githubusercontent.com/assets/2915573/11161594/0703b444-8a4f-11e5-9824-7159f25d4014.png)

On the other hand, EP's daylight sensor is not reliable but It can be useful for test runs. We have an open issue for that and your file is a great start. In case you are willing to develop it further my suggestion is to take the sensor component out so you can create multiple sensors and add them to a zone using another component (addDaylighSensor?)

Once we have OpenStudio's daylight measure in place that would be the best path to address this issue.

**Comment by agusHariyadi** [comment]
@mostaphaRoudsari  Thank you for checking this issue, I would love to develop this further, but I am still learning phyton so I`ll do the best I could.
btw where is the open issue that you mention about EP`s daylight sensor?
As far as I know, the limitation of this daylight sensor is the number of sensor only limited up to 2 sensor and working as one system in one zone which It will be confusing to place the sensor in the zone that have multiple windows direction unless we divide into multiple zone.

**Comment by mostaphaRoudsari** [comment]
@agusHariyadi the open issue is here: https://github.com/mostaphaRoudsari/Honeybee/issues/118
The main issue is the accuracy of the results. Here you can find more information about daylight:controls in EnergyPlus: http://bigladdersoftware.com/epx/docs/8-0/input-output-reference/page-016.html
