### ISSUE TITLE
setEPAirflow component error

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#417]
http://www.grasshopper3d.com/group/ladybug/forum/topic/show?id=2985220%3ATopic%3A1399294&xg_source=msg

@chriswmackey it looks like a bug to me. Let me know if you want me to have a look.

**Comment by chriswmackey** [comment]
It is Fixed:
https://github.com/mostaphaRoudsari/Honeybee/commit/5c46abd15994eb2c9372b1a59aee46a72a5edc5a
