### ISSUE TITLE
Radiance Glass_Material component

### ISSUE THREAD

**Issue by jramsden271** [mostaphaRoudsari/Honeybee#418]
If no name is inputted, the RADmaterial output is null. However, this is not obvious to the user. The component should return an error if no name is inputted. Otherwise, the user may continue to model with a 'null' material, which can alter analysis results.

**Comment by mostaphaRoudsari** [comment]
@jramsden271 I added input check to all material components. It now gives a warning if any of required inputs is missing.

**Comment by chriswmackey** [comment]
Also, @jramsden271 ,

This issue will be addressed across all LB+HB components once we implement the new graphic standards for the next stable release in January:

https://github.com/mostaphaRoudsari/ladybug/blob/master/resources/Ladybug%20Grahpic%20Standards.md

https://github.com/mostaphaRoudsari/ladybug/issues/196

-Chris
