### ISSUE TITLE
climateMap analysisPeriod doesn't support reversed periods

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#427]
@chriswmackey it happens since you're checking the range by assuming the first item on the list is the smallest HOY in the range however in cases with reverse months it is not the case and will give an error. I don't know enough about the component to suggest the easiest fix.

![image](https://cloud.githubusercontent.com/assets/2915573/11509829/6e468d2e-982e-11e5-86f3-13e643b62ac6.png)

Let me know if you have a quick fix for it or otherwise I can try to find a solution as my students will need it for their final project.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
This capability should have been be present and I believe that I have fixed it with this commit:
https://github.com/mostaphaRoudsari/Honeybee/commit/c8e7dd3978594e742ed8dccdb0fdf61696f1ebc6

Here is the working GH file:
https://www.dropbox.com/s/eq84pcvrnrtlu4g/Comfort_Autonomy_CWM.gh?dl=0

-Chris
