### ISSUE TITLE
Add shading Control with a defined setpoint to EP blinds

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#428]
Hi @chriswmackey. Check [this discussion](http://www.grasshopper3d.com/group/ladybug/forum/topics/shading-control-with-a-defined-setpoint?commentId=2985220%3AComment%3A1413081&xg_source=msg_com_gr_forum) for the details. @antonszilasi has already gave it a try and looks it's very close.

**Comment by chriswmackey** [comment]
Full support of set points is now online!
https://github.com/mostaphaRoudsari/Honeybee/commit/180bac5d289e46c148ecbe61809e0c26324c301f

**Comment by mostaphaRoudsari** [comment]
Reported by Claudio: http://www.grasshopper3d.com/group/ladybug/forum/topics/shading-control-with-a-defined-setpoint?commentId=2985220%3AComment%3A1431076&groupId=2985220%3AGroup%3A658987

**Comment by chriswmackey** [comment]
Bugs have been addressed:
http://www.grasshopper3d.com/group/ladybug/forum/topics/shading-control-with-a-defined-setpoint?commentId=2985220%3AComment%3A1431076&groupId=2985220%3AGroup%3A658987
I think that the second error might have resulted from Claudio adding old components with new ones.  If not, I will re-open this issue.
-Chris

**Comment by ayezioro** [comment]
Hi,
Not a bug but something that need to be clarified. The new HB_EPWindowShades requires the shadeCntrlType_ input to work. If not provided it will turn red (1. Solution exception:KeyError). This input doesn't appear as compulsory. Other inputs appear as compulsory but thay aren't (numOfShds for instance).
This is cosmetic so no need to rush fixing it.
Thanks,
-A.
