### ISSUE TITLE
Weird Annual Daylight Error

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#432]
I got some weird behavior for the run daylight simulation component that I have not yet been able to understand:
1. Solution exception:HybridMapping is full

Even though Daysim is still running, GH has responded and given an error for the Run Daylight analysis component.  Here's and image with an error and the file that generated the error:
![image](https://cloud.githubusercontent.com/assets/5567574/11701002/0e58dd40-9e9b-11e5-9757-5121430fb428.png)

https://www.dropbox.com/s/m0rm3v64wjozfy7/BasementDaylightStudyFile2.gh?dl=0

Note that the file took a long time to run.
-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey which line is the error? I should probably rewrite isStudyOver function.

**Comment by chriswmackey** [comment]
@mostapharoudsari ,
This may be something weird on my system. I will have a clearer idea tomorrow once another attempt at this simulation finishes. I will post back here then if I am able to re-create the error.
-Chris

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I have been unable to re-create the error and I also see that you have re-written the isStudyOver function:
https://github.com/mostaphaRoudsari/Honeybee/issues/424
In light of this, I will close out the issue but we at least have a record of this error here on the github in case anyone ever manages to encounter it in the future.

-Chris
