### ISSUE TITLE
ASE and the Fifth phase for the 5-Phase Method for Annual Daylighting Simulations.

### ISSUE THREAD

**Issue by sariths** [mostaphaRoudsari/Honeybee#435]
Hi Guys, 

I have finished writing a beta-implementation of the phase 5 of the 5-phase method for my research. In plain-speak, it is the part that involves subtracting out the direct sun component generated through Reinhart/Perez skies from calculations and substituting that with a more accurate calculation. In my case I am using the dxAnalemma to do the direct sun calculations. Dxanalemma, which we've have tested fairly extensively at  Penn State, will eventually be a part of the official Radiance repository (http://www.radiance-online.org/community/workshops/2015-philadelphia/presentations/day1/STADICUtilities-Radiance%20Workshop2015.pdf, slide 18-20).

Since direct sun is what is required for ASE calculations, a similar workflow is applicable for calculating ASE as well. This workflow is independent of Daysim completely and runs somewhat faster than the standard daylight coefficient method. The steps required for ASE calculations, in order, are : Dxanalemma, some python scripting, Rcontrib, Dctimestep, Rcollate, Rcollate, Rcalc, Rcollate, again some python scripting. If you guys are interested in implementing this in Honeybee, please let me know. I wrote it as a hack for my own work. Making it work with Honeybee might require some coordination and an additional Recipe or something similar.

(I don't want to crap all over the github commenting/reporting format, but I did not know where to post this thing. It definitely doesn't fit in on the Ladybug forum. So, I am posting this here.)

Sarith

**Comment by chriswmackey** [comment]
@sariths ,
This is definitely the right place for this, although it sounds like this might merit two issues (one for ASE and another for 5-Pahse).  Both you and @mostaphaRoudsari are way deeper into the daylight stuff than I and so I think we should hear Mostapha's  thoughts before deciding how to integrate this into Honeybee.
It looks like you did some really intense research and scripting to get it to this point.  Congratulations on all of the hard work!
-Chris

**Comment by sariths** [comment]
@chriswmackey ,

Thanks. For my research its still a "A journey of thousand miles....." kind of situation. My colleagues are implementing a similar workflow for ASE in STADIC(https://github.com/Architectural-Lighting-Simulation/STADIC) although the coding environment there is C++. I agree that ASE and 5-Phase method are two separate issues. I will start a separate issue for the ASE calcs after discussing with @mostaphaRoudsari . 

Sarith

**Comment by mostaphaRoudsari** [comment]
Here is the conclusion after our discussion:

1. ASE component is almost ready to be shared. We need to also ship STADIC dependencies with Honeybee. It's already following Honeybee workflows and should be pretty easy for users to understand and use.

2. I will create a prototype of honeybee-core and honeybee-grasshopper as the starting point for integrating 3-5 phase methods to Honeybee.

@sariths I think we can open two separate issues for each of these and close this one.

**Comment by sariths** [comment]
@mostaphaRoudsari Agreed. I will open an issue for ASE within a few days.
