### ISSUE TITLE
Daysim Occupancy Generator issue

### ISSUE THREAD

**Issue by boris-p** [mostaphaRoudsari/Honeybee#436]
hey, maybe I just got something wrong but could it be that the occupancy generator produces wrong results in relation to weekend days?
I've plotted the occupancy schedule to get a better look and the results seem suspicious - 
![occupancy](https://cloud.githubusercontent.com/assets/3728381/11807826/b24d1256-a31c-11e5-94f7-b1324b9baef3.jpg)

The input for weekend days was a list- 1,2 and the results were the same when leaving the default values.
Looking at the code I stumbled upon this line - if not int(DOY%7) + 2 in weekendDays:
this - int(DOY%7) + 2 will always be more than 1, so if I change the input list to [2,3] or change the line to +1 instead  the results seem to make sense - 
![occupancy2](https://cloud.githubusercontent.com/assets/3728381/11807916/5b98ddae-a31d-11e5-9bd3-cc1d962995c1.jpg)

or am I missing something?

**Comment by chriswmackey** [comment]
@boris-p ,
I had a look at the situation and you are right that it was a bug:
https://www.dropbox.com/s/29tkabmohz8zkmd/FixedDaysimOccGenerator.gh?dl=0

I have fixed it with this commit:
https://github.com/mostaphaRoudsari/Honeybee/commit/9dce3df26099c3a6c96c213541d84768bc3caa42

Thanks for finding this one!
-Chris
