### ISSUE TITLE
Thermal Autonomy Analysis bug

### ISSUE THREAD

**Issue by ocni-dtu** [mostaphaRoudsari/Honeybee#437]
Hey again

I don't know if you fixed this,  but I couldn't find a post about it. 
I found one or two bugs in the Thermal Autonomy component. 

![taa](https://cloud.githubusercontent.com/assets/16247318/11915245/049356c2-a69e-11e5-8f4c-a5ba1212dbe4.PNG)

In line 270 and 280 the names are not the same. 
In the else case I put a [ in front of; a checkData5 statement seems to be missing. It works when I set checkData5= True in the "if len(values) == 8760:" case, but I don't know if that is correct.

**Comment by chriswmackey** [comment]
@ocni-dtu ,
Awesome job!  Thanks for finding this.  Your corrections are spot-on and I fixed the error here:
https://github.com/mostaphaRoudsari/Honeybee/commit/abf92c217ff9a7737e291a44a5b0bb31b16a746b

Many future users thank you!
-Chris
