### ISSUE TITLE
Find a Way to Stop HB_HB from Over-writing Materials/Constructions in Memory

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#446]
I have realized that this issue seems to confuse the great majority of the user base:
http://www.grasshopper3d.com/group/ladybug/forum/topics/therm-example?commentId=2985220%3AComment%3A1429638&xg_source=msg_com_gr_forum
http://www.grasshopper3d.com/group/ladybug/forum/topics/problem-setting-energy-plus-fields-in-honeybee?commentId=2985220%3AComment%3A1261028&groupId=2985220%3AGroup%3A658987

@mostaphaRoudsari , I feel that we have to find a solution to this and my initial gut is just to put a check in HB_HB to see if there is a previous object in:
sc.sticky ["honeybee_constructionLib"]
sc.sticky ["honeybee_materialLib"]
sc.sticky ["honeybee_windowMaterialLib"]
sc.sticky["honeybee_thermMaterialLib"]
..and, if so, just take that library.  A slower alternative could have us check for any discrepancies between the current libraries in memory and those loaded from the idf and csv files and make a "super library" but this seems unnecessary as whatever HB_HB flies first will load in everything from these files.

Let me know your thought on this soon.  I will implement the first option within a few days unless you say otherwise.
-Chris

**Comment by mostaphaRoudsari** [comment]
Hi @chriswmackey,
I thought I have already fixed this but probably not >
(https://github.com/mostaphaRoudsari/Honeybee/blob/master/src/Honeybee_Honeybee.py#L8011-L8032) Let me check this again. I have probably made a made a mistake.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey it was my bad but since the code was already there it was an easy fix. Should be fixed now.

**Comment by chriswmackey** [comment]
Oh, man.  I can't believe that I went for so long not realizing that this was a bug.  Thank you for fixing it so quickly!

**Comment by ayezioro** [comment]
You are the BEST!! Both of you :-)
