### ISSUE TITLE
IES Components for Honeybee

### ISSUE THREAD

**Issue by sariths** [mostaphaRoudsari/Honeybee#447]
Hi @mostaphaRoudsari and @chriswmackey,

I was creating an example for the IES components when I realized that I have some tiny scripts in my workflow that aren't a part of Honeybe/Ladybug. I can get rid of most of them, however, I am not aware of anything that can put multiple filepaths on to the canvas. Is it possible to do something like  https://www.youtube.com/watch?v=c1vP5DL3tqg&feature=youtu.be in Honeybee ?

Lighting designers almost always iterate through multiple IES files before they decide on a particular luminaire (light fixture). So, I am pretty sure that we would need a functionality of this sort.

Secondly, I have a design/best-practice related question. Right now, unless the user explicitly specifies a `_radDir_` all the Radiance files created for the .ies file get placed in a folder called ies in the same location as the original .ies file. Is there a better place for this ? It occurred to me last night when I was using the MSH2RAD component that the mesh gets placed in the honeybee folder directly. Is there a way that I can do that as well ?

![1-4-2016 4-17-51 pm](https://cloud.githubusercontent.com/assets/10361848/12100773/0069f8ae-b2ff-11e5-985d-1ce50e2cbc8e.jpg)

**Comment by mostaphaRoudsari** [comment]
Hi @sariths! The answer is yes and no. There is an openEpw component that does something similar to what you have in the video but it's only for epw files but we don't have it for every file type. **Human** plugin has a component that does it though. Also there are so many other ways to copy the path into Grasshopper so it's not critical to have component for that. At the same time if you think it's critical in your process to avoid having multiple components we can add it to LookUp component. It already loads epw files and we can add ies files as one more output?

I would suggest to create a specific folder for your files. We currently do this also for skies. We don't currently have it made but at some point we should have some components to package the study folder and having all the files under Honeybee folder can make it much easier. You can always access the default Honeybee folder from sticky:
```python
hb_folders = sc.sticky["honeybee_folders"]
hb_RADPath = hb_folders["RADPath"]
hb_RADLibPath = hb_folders["RADLibPath"]
```

**Comment by sariths** [comment]
@mostaphaRoudsari I know that openEpw component does something similar. My script was almost 90% inspired/copied from your component. I just tweaked it a bit.

Anyways, I think this.....**At the same time if you think it's critical in your process to avoid having multiple components we can add it to LookUp component. It already loads epw files and we can add ies files as one more output?"**....is a good idea. Can you write that it in before I create an example file ?

Regarding the folders, I figured that one out from a reply that Chris had given to a query of mine. I added a couple of lines that will create a folder called ies inside Ladybug default folder and create all the files there. Is that fine ?

**Comment by mostaphaRoudsari** [comment]
Here you go >
![image](https://cloud.githubusercontent.com/assets/2915573/12106816/54bd7f8e-b331-11e5-8d30-a13d0d6e5a09.png)

Sounds great to me!

**Comment by sariths** [comment]
That was quick. Thanks !

**Comment by sariths** [comment]
Hi @mostaphaRoudsari  @chriswmackey 

Here is a very basic example of IES components being used in an Indoor electric lighting simulation:


https://www.dropbox.com/s/xqxwsql0s4r2axs/LightingBasic.zip?dl=0 . (The folder inside the zip file should be placed on c: )

https://www.youtube.com/watch?v=7Y4tIAW3odg&feature=youtu.be   (Not a how to video, just a screencap)

I couldn't get Hydra to display the example.. https://github.com/sariths/hydra/tree/ElectricLighting/IES_indoor_Electric_Lighting

**Comment by mostaphaRoudsari** [comment]
> I couldn't get Hydra to display the example..

@sariths thanks! It's easy to make it work on Hydra. You just need to move the files under the master branch. It's under ElectricalLighting branch right now.

**Comment by sariths** [comment]
@mostaphaRoudsari Thanks, I think it is working now. I watched a 10 minute video about Github yesterday so I feel like an expert now. What is your opinion on using branches to push files to the main Honeybee-master ? The reason I am asking is that if I commit something to my master and then push it your repository I am ahead of you even after syncing my fork. So, is it okay if I use a branch to develop and issue pull requests ?

**Comment by mostaphaRoudsari** [comment]
@sariths we won't have this problem with Hydra since you don't have ever to send a pull-request. The main Hydra page loads the files directly form your fork. You can consider it as a distributed file sharing system. As you can see in the [Hydra repository](https://github.com/HydraShare/hydra) there is no example file. It all live inside forks. Does it make any sense?

**Comment by sariths** [comment]
@mostaphaRoudsari Yup, thanks. I think I managed to mess it up anyway ! Do you have to remove this http://hydrashare.github.io/hydra/viewer?owner=sariths&fork=hydra&id=Indoor_Electric_Lighting manually ? I deleted that example because it was a duplicate. It seems like the page and the link are still there however.

**Comment by mostaphaRoudsari** [comment]
@sariths that's fine. The link will be removed in 15 minutes. Hydra caches the data from all the forks every 15 minutes. Thanks for getting it fixed.
