### ISSUE TITLE
Add RAD Material and EP Construction to the Glazing Based on Ratio Component

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/honeybee#449]
This is definitely something that is needed and probably should have been put in long ago (as raised by this discussion: http://www.grasshopper3d.com/group/ladybug/forum/topics/hb-glazingbasedonratio-component?commentId=2985220%3AComment%3A1430919&xg_source=msg_com_gr_forum)

I will try to implement this soon.  My only point of deliberation is that adding these two extra inputs is going to make the component fairly large for a component that gets used so often.  As a result, I am thinking of taking out the skylight inputs on this component and putting them into another one that is only for skylights based on a ratio.  I imagine that people usually want to assign different constructions to skylights than to windows on walls anyway and separating them into two components would facilitate this while also allowing us to use the "divide based on cardinal direction" property for window constructions, which I imagine being useful for a number of cases.

If anyone disagrees with the plan above, please express your concern here.

**Comment by mostaphaRoudsari** [comment]
:+1:

**Comment by chriswmackey** [comment]
This is done!
https://github.com/mostaphaRoudsari/honeybee/commit/76c67ebac812e213093918bc4ed3281656f04f19
