### ISSUE TITLE
Path issue in gridBasedSimulation

### ISSUE THREAD

**Issue by sariths** [mostaphaRoudsari/Honeybee#450]
Hi @mostaphaRoudsari ,

I was trying to create a grid based-simulation on my G: drive and found that the octree doesn't get written. The batch file tries to set the path to c: when it should be setting it to g:.(see lines 2-3 below) Is it required that HB/LB simulations be run from the C: drive ?

    SET RAYPATH=.;C:\Radiance\lib
    PATH=C:\Radiance\bin;$PATH
    c:
    cd G:\lighting\unnamed\gridBasedSimulation\
    oconv -r 2048 -f G:/lighting/unnamed/gridBasedSimulation//material_unnamed.rad G:/lighting/unnamed/gridBasedSimulation/10000_lux.sky G:/lighting/unnamed/gridBasedSimulation/unnamed.rad  > unnamed_RAD.oct

**Comment by mostaphaRoudsari** [comment]
Looks like a bug! I will check and report back.

**Comment by mostaphaRoudsari** [comment]
It was a bug which is fixed now. Thanks for reporting.
