### ISSUE TITLE
MSH2RAD swallows a modifier from the material definition for complex materials.

### ISSUE THREAD

**Issue by sariths** [mostaphaRoudsari/Honeybee#451]
Hi @mostaphaRoudsari , 

I tried using a complex material with MSH2RAD and this happened (see the first line in both screenshots). This might be a bug.

![1-6-2016 6-33-34 pm](https://cloud.githubusercontent.com/assets/10361848/12158018/41cfb968-b4a4-11e5-902d-7335611fe3f4.jpg)
![1-6-2016 6-33-44 pm](https://cloud.githubusercontent.com/assets/10361848/12158024/44a04c98-b4a4-11e5-8e56-428176362fdc.jpg)

**Comment by mostaphaRoudsari** [comment]
Hi @sariths! Looks like a bug. How do you apply the material? Do you connect the whole material definition to the component?

**Comment by sariths** [comment]
@mostaphaRoudsari Yes, I connected the whole material definition to the component. I think the error is occurring somewhere inside the Honeybee_Honeybee ( ie main) component. The self.RAD attribute gets written properly. The error occurs after that where you are constructing the string.

**Comment by mostaphaRoudsari** [comment]
@sariths I can't recreate the issue. Can you share an example with me?

![image](https://cloud.githubusercontent.com/assets/2915573/12224525/2047b67c-b7c1-11e5-9631-6651f5c57b4b.png)

**Comment by sariths** [comment]
Hi Mostapha,

I think the issue only seems to arise in case of improper formatting. See:
![1-11-2016 11-10-38 pm](https://cloud.githubusercontent.com/assets/10361848/12254654/e4172e00-b8b8-11e5-8362-2283709e056c.jpg)
![1-11-2016 11-10-51 pm](https://cloud.githubusercontent.com/assets/10361848/12254655/e41e6e90-b8b8-11e5-9778-3b0393900fe1.jpg)
![1-11-2016 11-11-18 pm](https://cloud.githubusercontent.com/assets/10361848/12254656/e420f336-b8b8-11e5-82df-894b0eeeb08d.jpg)

See : https://www.dropbox.com/s/jpgxq169sx895ea/Msh2rad.gh?dl=0

**Comment by mostaphaRoudsari** [comment]
@sariths in general materials should be fairly structured to be imported by MSH2RAD.

![image](https://cloud.githubusercontent.com/assets/2915573/12255523/9ce5d522-b8c2-11e5-8798-61879a9b6441.png)

Honeybee can handle less structured materials but MSH2RAD has a slightly different workflow. For now I fixed the issue for the first case.

![image](https://cloud.githubusercontent.com/assets/2915573/12255506/75b0fe32-b8c2-11e5-8554-3776f0a56473.png)

**Comment by sariths** [comment]
@mostaphaRoudsari  Okay, thanks! I think I will stick to creating materials through the Honeybee library components. It's just one extra component.
