### ISSUE TITLE
OpenStudio csv schedule bug

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#455]
From [this discussion](http://www.grasshopper3d.com/group/ladybug/forum/topics/openstudio-give-me-error-warning?commentId=2985220%3AComment%3A1436554&xg_source=msg_com_gr_forum):

>after I update the input HBZones with modified lighting schedule generated by Daysim, the electric lighting consumption from Openstudio Component turns to "0". EnergyPlus Component seems working correctly. Any thoughts?

It looks like a bug to me w/o checking the file.

**Comment by mostaphaRoudsari** [comment]
one more here: http://www.grasshopper3d.com/xn/detail/2985220:Comment:1437718

@chriswmackey let me know if you want me to take a look at this.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

Man, I did not expect people to be using this feature so quickly. I will take a look at it in a couple of hours.

-Chris

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,
I'll admit that my implementation of this csv capability was originally a bit hacky.  I guess that a workaround for a feature that should be present in OpenStuido is bound to be hacky by nature.  In any case, hopefully what I wrote this time should be more resilient to different cases:
https://github.com/mostaphaRoudsari/Honeybee/commit/43c2587024a7e7a739cdfc6d02eb32cf06a10480
-Chris

**Comment by mostaphaRoudsari** [comment]
Thanks @chriswmackey! I think @macumber said they will officially add it to OpenStudio at some point this year.

**Comment by macumber** [comment]
Might be this year but no promises :-)

**Comment by mostaphaRoudsari** [comment]
Thanks :)

**Comment by TheodoreGalanos** [comment]
Hi,

Does it make sense that I experience this once again after all this time? I've updated to the latest HB/LB, using OS 1.12 I believe.

Kind regards,
Theodore.

**Comment by chriswmackey** [comment]
OpenStudio has not implemented it yet on their latest stable version (1.14). The honeybee workaround that writes the schedule after translating to an IDF is still there.
