### ISSUE TITLE
Open Studio returns PINVOKE Execption

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Honeybee#469]
@mostaphaRoudsari  @chriswmackey 
I know there was an issue already open on this but I can't find it. I'm opening a new issue here.  Mostapha since I couldnt solve this issue through your advice. Should we get the Open Studio developers on board here?

![capture](https://cloud.githubusercontent.com/assets/8773483/12735147/4dbd3f72-c93d-11e5-9b8a-df434fad7456.JPG)

**Comment by mostaphaRoudsari** [comment]
@antonszilasi can you share the full error report?

**Comment by antonszilasi** [comment]
@mostapha,bizzarely it just started working again and I have no idea why.

**Comment by mostaphaRoudsari** [comment]
@antonszilasi not sure if I should be happy or sad about this one. Have you made any changes? Let's close this issue then for now.
