### ISSUE TITLE
Honeybee Openstudio csv schedules issue

### ISSUE THREAD

**Issue by jasbour** [mostaphaRoudsari/Honeybee#470]
Hi there,
I have this issue that the "honeybee_export to openstudio " component outputs the following, once i assign a custom schedule on my HB zone, using the "Create CSV Schedule" component: " _Failed to find DEFAULTCSVPLACEHOLDER in the Honeybee schedule library._"
Is there a possible workaround? I am posting the script if someone can check:
https://www.dropbox.com/sh/5a5drumpm14nen7/AABy7DZNtUzrmj4FwI3V0h6Sa?dl=0

thank you!

**Comment by chriswmackey** [comment]
@jasbour ,
This is a duplicate issue that has already been addressed. Follow the instructions that I give in this GH dsicussion to get csv schedules working for you.
http://www.grasshopper3d.com/group/ladybug/forum/topics/lighting-schedules-for-energyplus?commentId=2985220%3AComment%3A1437718&groupId=2985220%3AGroup%3A658987

...and keep in mind that this is a work-around until OpenStudio team implements the ability to assign CSV schedules in osm files so it's a bit hacky at present.
https://github.com/mostaphaRoudsari/Honeybee/issues/455
-Chris

**Comment by jasbour** [comment]
ok got it!
thank you for the link,
i was able to solve it as explained in the GS forum!
