### ISSUE TITLE
indoor view factor calculator" takes a long time to "settle down" with new input conneccted

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#475]
@chriswmackey FYI!
http://www.grasshopper3d.com/group/ladybug/forum/topic/show?id=2985220%3ATopic%3A1448265&xg_source=msg

**Comment by chriswmackey** [comment]
This is not a bug and just a misunderstanding of how the component works.  I have responded to Grasshope here:

http://www.grasshopper3d.com/group/ladybug/forum/topic/show?id=2985220%3ATopic%3A1448265&xg_source=msg#

-Chris
