### ISSUE TITLE
"Illegal charecter in weather file path"  HB EP simulation epw error in newer version 

### ISSUE THREAD

**Issue by Omidmr** [mostaphaRoudsari/Honeybee#476]
Hi,
I updated HB & LB components returns this error in EP simulation epw  file path.
![123](https://cloud.githubusercontent.com/assets/11173265/12873993/612cfe38-cde0-11e5-9ade-03023836ae19.JPG)

TNX.
-Omid

**Comment by mostaphaRoudsari** [comment]
You need to load the weather file a different path with no *&*. EnergyPlus will fail to run the analysis with illegal character in path. ImportEPW is different from EnergyPlus.
