### ISSUE TITLE
Error in run energy simulation

### ISSUE THREAD

**Issue by AhmedToutou** [mostaphaRoudsari/Honeybee#478]
hello guys:
it is my first trial to run energy simulation by honeybee. i used your example file   "@chriswmackey " to be a guide for me but unfortunately there was an error.  

https://drive.google.com/file/d/0ByMBlrZixe-1MjNQTUs5dW9fUTQ/view?usp=sharing
https://drive.google.com/file/d/0ByMBlrZixe-1d2c4YXUwTy1jRkk/view?usp=sharing

**Comment by mostaphaRoudsari** [comment]
@AhmedToutou you need to send questions like this to [Ladybug forum](http://www.grasshopper3d.com/group/ladybug/forum). Github is for development discussions. Thanks! :)

**Comment by AhmedToutou** [comment]
Thank you :)
