### ISSUE TITLE
surface.IDs of honeybee surfaces are being reset and Honeybee PV can no longer work

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Honeybee#487]
@mostaphaRoudsari @chriswmackey 

I've discovered that now Honeybee generators are not working as for some reason each time a surface is called from the Honeybee hive the .ID attribute of the surface is reset.

Honeybee generators rely on this .ID attribute remaining constant all the time

I believe this is due, to this line of code.

HBObject.resetID()

In the method addToHoneybeeHive. I think this was added recently? I couldn't work out how to find when it was added and by who is github.

Flying tomorrow see you both soon!

**Comment by mostaphaRoudsari** [comment]
This is my fault. Sorry! I did this as a better solution to generate IDs for surfaces for the next release and also make export/import components to work. Can you tell me how do you use the IDs? Is there a way that we can address both?

**Comment by antonszilasi** [comment]
@mostapha How about I just make a surface.ID just for Honeybee generator objects and call it .HBGID? Maybe its not the cleanest but it will solve the problem

**Comment by mostaphaRoudsari** [comment]
Thanks @antonszilasi! I agree that it won't be clean and it also won't work with import, export process.

My understanding is that you're collecting the data in sticky but you don't really need to if you save the data in surface level. Is there a way to add the data in the level of HBSurface so you can check it without accessing the id? Similar to what we do for HVAC systems and almost everything else?

```python
HBSrf.isGenerationSurface:
    #get the data
    data = HBSrf,generationData
```

**Comment by antonszilasi** [comment]
@mostaphaRoudsari  that might just be the trick

**Comment by antonszilasi** [comment]
@mostaphaRoudsari When you say it won't work with import and export what do you mean?

**Comment by mostaphaRoudsari** [comment]
@antonszilasi as discussed please add reference to code that you're using ID for generators and I will suggest some solutions based on that. Thanks.

**Comment by antonszilasi** [comment]
@mostaphaRoudsari 

There are three checks for which I need consistent HB surface IDs across components.

1. I use the ID of each honeybee surface to identify if there is a duplicate surface in the dictionary of Honeybee surfaces or not (each surface should only be added to the dictionary once).

https://github.com/antonszilasi/Honeybee/blob/master/src/Honeybee_Generator_PV.py#L276-L317

2. I also use the ID of the honeybee surface to ensure that for ensure non-context surface connected to the Run E+ component the HB zone which that surface belongs to is also connected to the E+ component.

https://github.com/antonszilasi/Honeybee/blob/master/src/Honeybee_%20Run%20Energy%20Simulation.py#L1807-L1824


3.  Lastly I use it to check that there are no duplicate surfaces with PV mounted on them

https://github.com/antonszilasi/Honeybee/blob/master/src/Honeybee_%20Run%20Energy%20Simulation.py#L1952-L1963

Let me know if you need anything else
