### ISSUE TITLE
Question about reconstructing geometries in Grasshopper and Honeybee surface.extractPoints()

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Honeybee#494]
@mostaphaRoudsari 
@chriswmackey 

I discovered that when I use the vertices of a surface to decompose and reconstruct the surface like so.

1. Decompose the brep into vertices/points
brepVertices = []

for HBZone in HBZonesFromHive:

    for vertice in HBZone.geometry.Vertices:
    
          brepVertices.append(vertice.Location)

2. Enter the brepVertices into the vertices of the construct mesh component .

![constructmesh](https://cloud.githubusercontent.com/assets/8773483/13356810/db5e9cd0-dc6c-11e5-9a95-ac56fe4a9f33.PNG)

I sometimes get a mesh with a weird shape seen below because, the order of the points is wrong.

![drawing points wrong order](https://cloud.githubusercontent.com/assets/8773483/13356540/5f03e61e-dc6b-11e5-8f39-92c67a62467d.PNG)

Mostapha I noticed with your surface.extractPoints this is never the case. I tried to understand your code. But I can't quite understand what piece of code prevents this from happening. I would appreciate it if you could shed some light on the issue because I'd love to understand it! Thanks!

**Comment by mostaphaRoudsari** [comment]
@antonszilasi honeybee has a number of extra checks for the points to make sure they are sorted correctly. [Take a look here](https://github.com/mostaphaRoudsari/Honeybee/blob/master/src/Honeybee_Honeybee.py#L6072-L6078)

**Comment by chriswmackey** [comment]
Even more checks were added in with [this commit](https://github.com/mostaphaRoudsari/Honeybee/commit/7ad0041298674795711a7e4826eaf37bfc27b21a#diff-c2ecdd14851cd387b1d939828dbec897R6135).

Now, you can specify what start point you want.  Direction is always anticlockwise.
