### ISSUE TITLE
Reading non-Honeybee ill files with the Annual Daylights component. (Question)

### ISSUE THREAD

**Issue by sariths** [mostaphaRoudsari/Honeybee#496]
Hi @mostaphaRoudsari , 

I was trying to debug the project posted [here](http://www.grasshopper3d.com/group/ladybug/forum/topics/read-annual-result-error) when I ran into an exception over the fileName : "Can't sort .ill files based on the file names. Make sure branches are sorted correctly." 

Is there a way that I can explode all the branches in pts files and visualize all the points as one single mesh ? ( I mean I know the flatten part, I am wondering if it is possible/allowed within Honeybee).

**Comment by mostaphaRoudsari** [comment]
@sariths I assume you have already solved this. In any case.

The key is to merge ill files and not the points. Points are only used for grafting the results.

**Comment by sariths** [comment]
@mostaphaRoudsari , I think I tried a different approach. Anyways, I haven't looked into that project since then. I am going close this issue for now. I will let you know if I run into this again.

**Comment by sariths** [comment]
@mostaphaRoudsari I guess I [figured this out](http://www.grasshopper3d.com/group/ladybug/forum/topics/read-annual-result-error) without knowing that I figured this out..I had some questions regarding the file arrangement and parsing inside that results component that I couldn't get. I will check with you once I find the time to read that code again.
