### ISSUE TITLE
EPShadeMat - reflectance + transmittance lower than 1

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#498]
Hi,
As for this discussion:
http://www.grasshopper3d.com/group/ladybug/forum/topics/perforated-screen-energy-simulation?page=1&commentId=2985220%3AComment%3A1499719&x=1#2985220Comment1499719
I suggest to add those lines after line 93:

    checkData4 = True
    if (reflectance + transmittance) > 0.99: #!< 1:
        checkData4 = False
        print "reflectance_ + transmittance_ must be lower than 1"
        ghenv.Component.AddRuntimeMessage(gh.GH_RuntimeMessageLevel.Warning, "reflectance_ + transmittance_ must be lower than 1.")
    
    if thickness_ == None: thickness = 0.00025
    else: thickness = thickness_
    
    if conductivity_ == None: conductivity = 221
    else: conductivity = conductivity_
    
    
    if checkData1 == True and checkData2 == True and checkData3 == True and checkData4 == True: checkData = True
    else: checkData = False

When the reflectance + transmittance are NOT lower than 1 it will crash the E+ simulati wit a severe error.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
Thanks for the suggestion and the code.  I whole-heatedly agree and it is done:
https://github.com/mostaphaRoudsari/Honeybee/commit/d6ba21e2a9828ba68ac626db52f9d68c3a511784

-Chris
