### ISSUE TITLE
 'Honeybee_Glazing based on ratio' is very slow after solve adjacency 

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/honeybee#499]
> 1. While testing different options for generating windows with 'Honeybee_Glazing based on ratio', I noticed that the component is really fast if I use it before applying 'Honeybee_Solve Adjacencies'. I would guess about a thousand times faster. Why might this be? The downside is that I get windows on all the interior walls...
>    Any thoughts on how I could streamline these workflows? Any thoughts on further development of these components from the development team?

Read more here: http://www.grasshopper3d.com/group/ladybug/forum/topics/massing-studies-with-honeybee-speed-of-zone-and-window-creation

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

We can look back now and realize why this issue was the way that it is.  I'm so glad that we fixed that memory bug!
