### ISSUE TITLE
EnergyPlus and OpenStudio Components Giving Different Transmitted Solar Energy

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#503]
Looks like a bug with the OpenStudio component. Read more [here](http://www.grasshopper3d.com/group/ladybug/forum/topics/energyplus-and-openstudio-components-giving-different-transmitted).

**Comment by antonszilasi** [comment]
@mostaphaRoudsari a bug within the open studio component? Or a bug within open studio itself?

**Comment by mostaphaRoudsari** [comment]
@antonszilasi I'm not sure which one is the case. I haven't take a look. As I suggested in the discussion the first step is to make sure the idf file which is exported from the component looks as expected. I assume this is an issue with the exporter and not OpenStudio.

**Comment by antonszilasi** [comment]
@mostaphaRoudsari Ok I'll take a look at this

**Comment by JShultz89** [comment]
I saw a behavior that maybe the OpenStudio component is not properly rotating when a different north angle is given. I did not get the chance to investigate further but the numbers made sense for the north (0 rotation) but not when rotating the file to East (90 degree).

**Comment by mostaphaRoudsari** [comment]
Thanks @JShultz89 for reporting. Good catch. That was it! The north value in OpenStudio file was in Radians. It's fixed now.
