### ISSUE TITLE
AppData

### ISSUE THREAD

**Issue by moethu** [mostaphaRoudsari/Honeybee#504]
Hi @mostaphaRoudsari,

Duncan realized the other day that some of your scripts are accessing the AppData folder the following way: C:\User\%UserName%\AppData... could you change this to %AppData% entirely? We changed our usernames differing from the user folder name, so this path doesn't work for us anymore.
Its not really best practice, but well, we cannot change that at the moment.

Thanks, Max

**Comment by mostaphaRoudsari** [comment]
Hi @moethu! I should have already changed it to os.getenv('APPDATA'). Can you try the code on your machine and let me know if it returns the correct path. I will update the code once you confirm that it will work.

```python
import os
os.getenv('APPDATA')
```

**Comment by mostaphaRoudsari** [comment]
@moethu this should solve the problem. Let me know otherwise.
