### ISSUE TITLE
Small issue with getEPFolder 

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Honeybee#505]
@mostaphaRoudsari 

I've had a problem with the OpenStudio component refusing to run due to the getEPFolder returning None. This was because instead of EnergyPlus, it was EnergyPlus V. Is this a bug? Im using the component from 4th of April.

https://github.com/mostaphaRoudsari/Honeybee/blob/1ea348290aee2de0b11bfe8eef2a5a3783a0cb4c/src/Honeybee_Export%20To%20OpenStudio.py#L2173

**Comment by mostaphaRoudsari** [comment]
This is what it is supposed to be. Here is the folder structure for EnergyPlus under openstudio folder:

![image](https://cloud.githubusercontent.com/assets/2915573/14443486/9f6f3062-000d-11e6-98fd-5fa4e4aac48e.png)

**Comment by antonszilasi** [comment]
@mostaphaRoudsari 

Ok so the question is, why isn't my folder structure like this? Should I put a 2nd method in the code so that this kind of issue can be accounted for?

**Comment by mostaphaRoudsari** [comment]
Unless OpenStudio has changed their installation routines I think we should not. Which version of OpenStudio do you have and what is the structure of the folder?
