### ISSUE TITLE
Honeybee PMV ComfRecipe+AdaptComfRecipe Runtime+Error in newer Version.!

### ISSUE THREAD

**Issue by Omidmr** [mostaphaRoudsari/Honeybee#508]
Hi every one.
I used  latest version of (LB 0.0.62 & HB 0.0.59) of this components (VER 0.0.59\APR_12_2016) returns this error:
"1. Solution exception:expected float, got NoneType"

![25](https://cloud.githubusercontent.com/assets/11173265/15218626/091a9bb6-1876-11e6-8945-675145bb043d.PNG)

TNX
-Omid

**Comment by chriswmackey** [comment]
@Omidmr ,
Can you post a link to the GH file with the error?  I can't recreate it on my machine and everything is working well for me:
![workingpmv](https://cloud.githubusercontent.com/assets/5567574/15271969/25d481ec-1a31-11e6-89f4-f3ea87a8443d.JPG)


https://www.dropbox.com/s/l4qyi4fodovdotb/Indoor_Microclimate_Map.gh?dl=0
-Chris

**Comment by mostaphaRoudsari** [comment]
@Omidmr I'm closing this as it has been addressed in the newer version. Feel free to re-open it if the issue still exists.
