### ISSUE TITLE
Question: Radiance solar radiation values when using gendaylit

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Honeybee#509]
This is a question regarding the Honeybee generate sky components that use gendaylit I noticed in the code that the input for gendaylit -O, please see: https://www.radiance-online.org/learning/documentation/manual-pages/pdfs/gendaylit.pdf

Is hardcoded to 0, that is the output is W/m2/sr visible radiation. I am correct in assuming that all radiation studies using these components are considering only visible radiation and not the entire solar spectrum?

**Comment by mostaphaRoudsari** [comment]
@antonszilasi honeybee [modifies the sky](https://github.com/mostaphaRoudsari/Honeybee/blob/master/src/Honeybee_Honeybee.py#L1290-L1313) for radiation analysis and changes -O 0 to -O 1 [if necessary](https://github.com/mostaphaRoudsari/Honeybee/blob/master/src/Honeybee_Honeybee.py#L1280-L1282).

**Comment by mostaphaRoudsari** [comment]
@antonszilasi I'm closing this as it is already addressed.

**Comment by antonszilasi** [comment]
@mostaphaRoudsari Thanks Mostapha I see that for a radiation analysis -O is changed to 1 which is W/m2/Sr

**Comment by antonszilasi** [comment]
@mostaphaRoudsari 
Just for my own reference here when the study is set to simulation type 1 on the _simulationType_ input on the grid analysis -O is changed to one see: (https://www.radiance-online.org/learning/documentation/manual-pages/pdfs/gendaylit.pdf )and Radiance will return W/m2/Sr over the entire solar spectrum.

This is why there is no weighting in readRadiationResult see here:
