### ISSUE TITLE
HB_extrudeWindows normal inconsistency

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#510]
Hi,
I've found inconsistencies when using the HB_extrudeWindows component. Sometimes the extruded surfaces are done inwards.
I made some checkings extracting the normals of the windows calculated inside the component and i see that they point to the wrong direction.
Attached an example showing this. Also with some changes in the component just to isolate a case, but don't know how to fix.
Thanks,
-A.
![canvas at 01 13 08](https://cloud.githubusercontent.com/assets/7526023/15591860/3f62325a-23a8-11e6-8005-27fd8ca794a9.png)

[extrudeWindows_Issue.zip](https://github.com/mostaphaRoudsari/Honeybee/files/285431/extrudeWindows_Issue.zip)

**Comment by sariths** [comment]
Hi @ayezioro, thank you for reporting. It has been while since I visited this component. @chriswmackey , we were planning to include this component in other component as per a discussion before (I can't find it here). Is that still happening ?

**Comment by mostaphaRoudsari** [comment]
Hi Abraham! Thank you for reporting. It was happening because input type was set to surface and Grasshopper was changing normal directions. It's fixed.

![image](https://cloud.githubusercontent.com/assets/2915573/15618968/1e1300d0-241f-11e6-8212-015e0352f2cb.png)

**Comment by ayezioro** [comment]
Great Mostapha,
Thanks!!
-A.

**Comment by sariths** [comment]
That was quick !
