### ISSUE TITLE
input _sightLineToGlzBottom_ on component importWINDOW not working

### ISSUE THREAD

**Issue by benmo1** [mostaphaRoudsari/Honeybee#518]
Honeybee Version: 0.0.59
Windows: Windows 7. 
Grasshopper: Version August-27 2014
Rhino: Version 5 SR12 64-bit

The importWINDOW component has an input called _sightLineToGlzBottom_ which doesn't seem to do anything. The component still works and produces an output at thermPolygons which can be used to export to THERM. However, changing the input doesn't affect the shape of the polygons in any way.

Thanks so much for looking into this.

**Comment by chriswmackey** [comment]
@benmo1 ,
The _sightLineToGlzBottom_ does change the output.  It's just subtle.

It changes the placement of the "edge" boundary condition that comes out of the indoorBCs output of the component.  For example, here is the edge Boundary with the default 0 value for _sightLineToGlzBottom_:
![0cm](https://cloud.githubusercontent.com/assets/5567574/16472491/651e817a-3e32-11e6-9fce-38bdae8ec336.JPG)
And here is the edge boundary with 5 cm input to _sightLineToGlzBottom_:
![5cm](https://cloud.githubusercontent.com/assets/5567574/16472494/68badf5e-3e32-11e6-8501-38fe0dd25b71.JPG)


-Chris

**Comment by benmo1** [comment]
Thanks Chris for your prompt reply, 

However, I think there is still a bug but the nature is different. The reason that I thought it didn't do anything is because it doesn't respond the same way to the inputs as THERM does. Let me explain:

It seems that in therm: 

1) The 'glaze system height' sets overall height. 
2) The 'spacer height' variable removes some height from the cavity. (creating a problem where the visible portion of window isn't the same as the 'glaze system height' because some of it is now hidden inside the frame with the spacer.
3) The 'sight line to glaze bottom' variable adds some length onto the cavity and the glaze together to compensate for this.

In contrast, the honey bee component sets the total object height as equal to the 'glaze system height parameter'. This is probably more intuitive, however it isn't consistent with therm, which might be expected. When I compared it with therm, it seemed like it didn't do anything, because in therm it actually effects the heights of the components.

Please refer to my images for examples.

![glaze settings 1](https://cloud.githubusercontent.com/assets/2217144/16481859/337727da-3ea5-11e6-9699-2af2d851d517.png)

![glaze result 1](https://cloud.githubusercontent.com/assets/2217144/16481866/3992ab08-3ea5-11e6-8c45-3c7134a12754.png)

![glaze settings 2](https://cloud.githubusercontent.com/assets/2217144/16481869/3c7f6e46-3ea5-11e6-8059-5d79eb83cfae.png)

![glaze result 2](https://cloud.githubusercontent.com/assets/2217144/16481871/3e97f19e-3ea5-11e6-9e40-5c26dde64e7c.png)

The rhino script on the other hand:

![rhino gh counter example](https://cloud.githubusercontent.com/assets/2217144/16482338/3576f11c-3ea7-11e6-92d2-8a63cfefc489.png)

What do you think?

Blessings,

Ben

**Comment by chriswmackey** [comment]
@benmo1 ,

Thanks for pointing this out.  I must have mis-interpreted how THERM was working when I wrote the component.  My intention was to match the THERM importing process and I'll take a look at this later today.

-Chris

**Comment by chriswmackey** [comment]
@benmo1 ,

Thanks again for clarifying.  I fixed the Import WINDOW component to work the same way that THERM does.  The updated component is here on the github and I have updated [this example file](http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Import_Glazing_System_from_LBNL_WINDOW&slide=0&scale=1&offset=17.254472609197023,-1.2397322390536374) as well.

-Chris
