### ISSUE TITLE
latest updated of Honeybee EP Run simulation "Solution exception:too many values to unpack"

### ISSUE THREAD

**Issue by Omidmr** [mostaphaRoudsari/Honeybee#520]
Hi every one.
using latest updated of Honeybee EP Run simulation returns this error:
"Solution exception:too many values to unpack"
Runtime error (ValueErrorException): too many values to unpack
Traceback:
  line 1432, in main, "<string>"
  line 2200, in script
![image](https://cloud.githubusercontent.com/assets/11173265/16546781/e3c1440a-416a-11e6-8bb3-ee94f279d00e.png)

TNX
-Omid

**Comment by chriswmackey** [comment]
@Omidmr ,
Thanks for finding this and reporting.  The bug resulted from a small change I made yesterday for the OpenStudio workflow.  I just fixed it now:
https://github.com/mostaphaRoudsari/Honeybee/commit/3ba0d6616a955f5a8d2428ea3b209edd1f92ac2c

Thanks gain,
-Chris
