### ISSUE TITLE
Figure Out Why I Keep Getting Adjacent Surface Constructions not Matching with OpenStudio

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#521]
In my use of the OpenStudio component over the last few months, I keep getting this re-occurring error from EnergyPlus in various different forms:

   ** Severe  ** GetSurfaceData: Construction EXTERIOR WALL 3 of interzone surface ZONE_0_SRF_3 does not have the same number of layers as the construction INTERIOR WALL of adjacent surface ZONE_1_SRF_1

The odd thing about this error is that it goes away if I recompute the canvass and I never get this error when I use the "Run Simulation" IDF component with the exact same zones.  As a result, I am sure that this has to do with an extra check on the "Run Simulation" component that is not present on the "Export To OpenStudio" component.

I can definitely get to the bottom of this but I don't know where to start looking for the checks on adjacent surfaces.  @mostaphaRoudsari , if you could point me towards the spots in the code where the adjacent surface construction checking happens, it would save me an enormous amount of time digging through the code.

Thank you,
-Chris

**Comment by chriswmackey** [comment]
I have one other update, once I run the "Run Simulation" component with the exact same zones, the OpenStudio component works fine.  So the check must be changing something about the zone properties stored in memory.

**Comment by chriswmackey** [comment]
Here's an example file:
https://www.dropbox.com/s/1q5mxdbm20u2wl9/OSBug.gh?dl=0

There's a quirk with it, though.  It will only show the bug the first time that you open the file.  The second time you try to run OpenStudio component, the bug vanishes.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey, this is a very strange one! Surfaces look fine before using the component. Also it runs fine using the energyplus component. Let me take a look to the results of reEvluateZones and if that is also fine then it has to do something with the OpenStudio component.

![image](https://cloud.githubusercontent.com/assets/2915573/16548152/ba2499ba-4153-11e6-8140-b58d07bac54a.png)

**Comment by mostaphaRoudsari** [comment]
It doesn't look to be the reEvaluteZones too. Here is the construction after reEvaluateZones.

![image](https://cloud.githubusercontent.com/assets/2915573/16548210/18bb9266-4155-11e6-8d10-70d5872738fe.png)

**Comment by mostaphaRoudsari** [comment]
At least now I can see where the issue happens:
![image](https://cloud.githubusercontent.com/assets/2915573/16548324/f88d91b6-4158-11e6-89d7-b03e39ade816.png)

hopefully next update is the fix.

**Comment by chriswmackey** [comment]
Awesome!! Thank you, Mostapha!
