### ISSUE TITLE
Add VRF System Template to Honeybee OpenStudio Systems

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#522]
This is that last system that I want to implement before the next release.  From what I have seen in the measures so far, the system isn't too complex so I'll hopefully be able to get it in soon.

**Comment by chriswmackey** [comment]
This is done.
https://github.com/mostaphaRoudsari/Honeybee/commit/86d4df626a837c1f670eb3ac311fda6cb2669ba9

I am officially done with all HVAC edits for the release.  At this point all that I need to implement is dynamic blinds/shades/

**Comment by arif-hanif** [comment]
@chriswmackey @mostaphaRoudsari  awesome job with the HVAC system, i am not a grasshopper user so was never involved with this project but as you guys are porting to Dynamo I can definitely help out. I am getting familiar with your code base now. Can we get on a call to see how I can lend a hand. I have some ideas to expand whole building simulation.
