### ISSUE TITLE
Read simulation unmet hours

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Honeybee#523]
@mostaphaRoudsari @chriswmackey 

Folks I was thinking that since Chris has added all this awesome HVAC stuff, I would like to know the unmet hours of my simulation this is especially useful for ASHRAE 90.1.

I would like to add it to the read EP HVAC results component (to work only with the OpenStudio component, since the write E+ file component will soon be redundant) Chris where is the best place to implement this?

Thanks,

Anton

**Comment by chriswmackey** [comment]
@antonszilasi ,
Here's the method:
1) Run a simulation and open the folder with theIDF.
2) Open the .rdd file and search through the hundreds of outputs to find the unmet hours output.
3) Add this output to the Generate EP Output component's HVACParams.
4) Edit the Read EP HVAC Result component to bring in the output after simulation is run.
-Chris

**Comment by chriswmackey** [comment]
This has now been implemented.  Closing out the issue.
