### ISSUE TITLE
VER 0.0.59 createThermPolygons doesn't recognize cavityModel_ Material Property

### ISSUE THREAD

**Issue by benmo1** [mostaphaRoudsari/Honeybee#524]
VER 0.0.59 createThermPolygons doesn't seem to recognize cavityModel_ Material Property. If you create a component in Rhino and manually assign a cavity type to the material, then open the .thmx file in THERM 7.4, the material type will have switched from 'Solid' to 'Frame Cavity' correctly, but the 'Cavity Model' will always be 'ISO 15099'.

The output of the ThermMaterial component is correct. It shows that the cavity model number has been taken into account, however, either the createThermPolygons or the writeTHERM component does not take this into account and the information gets lost.

[cavity type bug.zip](https://github.com/mostaphaRoudsari/Honeybee/files/349750/cavity.type.bug.zip)

Windows 10
Rhino 5

Thanks so much for reading,

Ben

**Comment by chriswmackey** [comment]
@benmo1 ,

Thank you for finding and reporting the bug!

Now it is fixed:
https://github.com/mostaphaRoudsari/Honeybee/commit/faa721dc96d1041b46b5a517ec28af7b1dbc83a9

Enjoy!
https://www.dropbox.com/s/zu5wfvvvzu6l6ox/example_CWM.gh?dl=0

-Chris
