### ISSUE TITLE
ThermMaterial doesn't handle colors correctly

### ISSUE THREAD

**Issue by benmo1** [mostaphaRoudsari/Honeybee#529]
ThermMaterial, and therefore createThermPolygon doesn't handle colors correctly. Some grasshopper colors output as special names rather than RGB components.

For example, set a layer in Rhino to color Chartreuse
Reference an object from that layer in GH
Go to Human > Reference > Object Attributes 
hover your mouse over the col output and it will read Chartreuse

However, set a layer in Rhino to color SeaGreen
and the output will read 63,191,127

Anything that GRASSHOPPER gives a color name doesn't translate correctly into THERM when used as a ThermMaterial input. Using components to rearrange the color into a hex code before inputting it doesn't work either because ThermMaterial doesn't accept text at the RGBColor_ input.

However, the component function for any RGBColor_ input where GH doesn't give it a special name. It doesn't matter whether Rhino gives it a special name as long as GH doesn't. 

Thanks so much for reading,

Ben

**Comment by chriswmackey** [comment]
@benmo1 ,

This seems to be an issue with the Dot NET color translating function that I use to take RGB colors in GH and turn them into the Hex code that THERM likes. It looks like I should add in another check for color types. I'll try to do this soon. In the meantime, if you could post a link to an example file that shows the issue, that would save some time and help me address this faster.

-Chris

**Comment by benmo1** [comment]
Here is the example file as requested. I look forward to the fix, this will make our project much more intuitive for users.

[general color bug.zip](https://github.com/mostaphaRoudsari/Honeybee/files/393432/general.color.bug.zip)

Thanks so much for your time,

Ben

**Comment by chriswmackey** [comment]
@benmo1 ,

I apologize for taking so long to address this issue.  The past month was very busy and there were several features that had to be cleaned up in the OpenStudio components.  Thanks for posting the example file and I will try to get this fixed this afternoon.

-Chris

**Comment by chriswmackey** [comment]
@benmo1 ,

This is now fixed.

https://github.com/mostaphaRoudsari/Honeybee/commit/1c7533a1934792b82903f99b00c7068501a5744e

https://www.dropbox.com/s/1j1yvwnwhy0dnkc/ThermColorFix.gh?dl=0

Thanks again fro reporting the bug!
-Chris

**Comment by benmo1** [comment]
Thanks so much, no worries about the time delay. I was switched onto another project for 2 weeks so I only just came back to it. Thanks so much,

Ben
