### ISSUE TITLE
Phase out "Set Ideal Air Loads Parameters" and Have E+ Component use the HVAC Components to Set these Parameters

### ISSUE THREAD

**Issue by jacoposartore** [mostaphaRoudsari/Honeybee#531]
Hi there,

After updating an old definition containing the Set Ideal Air Loads Parameters (which I used to account for no outdoor air coming to the zone, typical of fan coils installed in rooms without duct air systems), I figured out that this component is causing a severe error that stops the simulation, as in the picture below. I guess that it has been abandoned because of the upcoming switch to OpenStudio.

I was wondering if there is a way to model such a condition within OpenStudio, maybe it could be added to the airDetails component?

![image](https://cloud.githubusercontent.com/assets/8501837/16833432/a0c1e63a-49af-11e6-8899-d2a83624b78c.png)

**Comment by mostaphaRoudsari** [comment]
I think @chriswmackey has already mentioned this in some other issue which I can't find now. I'm sure Chris will get back to you on this issue. I just wanted thank you for doing all the comparisons and keeping us the posted about the bugs. It's very helpful! Thanks. :100:

**Comment by jacoposartore** [comment]
You're welcome, but it's me that should thank you for all the efforts you put into Ladybug and Honeybee and your careful answer toward user's suggestions and opinions :+1: .
P.S. Can't wait to see Butterfly in action! :100:

**Comment by chriswmackey** [comment]
@jacoposartore ,

Thanks for opening this issue.  The "Set Ideal Air Loads Parameters" component is about to be retired in the next release and you will instead assign these parameters with the components in the Energy HVAC tab.  I have not yet put these capabilites into the Run Simulation component and I will post back here once I do so.

For now, I would recommend you use the ideal air system with the OpenStudio component and this will give you access to all of the features that have historically been present on the "Set Ideal Air Loads Parameters" component (use the airdetails, coolingdetails and heating details components).

Thanks gain,
-Chris

**Comment by jacoposartore** [comment]
@chriswmackey ,

thanks for the explanation!

**Comment by chriswmackey** [comment]
@jacoposartore ,

I am renaming the issue to reference the new workflow for assiging the ideal air loads parameters.  I should hopefully be able to address this tomorrow.

**Comment by chriswmackey** [comment]
@jacoposartore ,
I just finished implementing this:
https://github.com/mostaphaRoudsari/Honeybee/commit/a6b1bc2db1f4da25ceae479f7822dbe7015f85c9
You can find an example file showing how to set the parameters of the ideal air system here:
https://www.dropbox.com/s/ssuh6mie1precyn/AssignIdealAirParams.gh?dl=0

Cheers,
-Chris

**Comment by jacoposartore** [comment]
@chriswmackey,

Thank you for the update!
I can't find the "outdoorAirReq" or an air recirculation option, any chance to have it back?

**Comment by chriswmackey** [comment]
@jacoposartore ,
Air re-circulation is still there and is on the 'Set EnergyPlus Zne Loads' component.
I can add back the 'outdoorAirReq' but it should be assigned on the zone level (I am thinking the "Set EnergyPlus Zone Thresholds" component).  I'll repoen the issue until I can implement it.

The cooling/heating capacity is much more difficult to bring back as it is not as easily generalizable to all of the HVAC systems that Honeybee now has.  Any one component of a complex HVAC system can limit the capacity and it is not as simple as assigning one value in watts for the whole system.  I can put in an option to change the sizing factor of the HVAC system, which will scale all of the components of the system accordingly.  Would that satisfy your current use of the ideal air loads capacity inputs?

-Chris

**Comment by jacoposartore** [comment]
@chriswmackey,

adding the "outdoorAirReq" to the "Set EnergyPlus Zone Thresholds" component would be perfect. Now I see the air recirculation! Thank you for both.

The scaling for the whole HVAC system seems a good compromise, once it's ready I can test it.

**Comment by chriswmackey** [comment]
@jacoposartore ,
I added back the outdoor air requirement:
https://github.com/mostaphaRoudsari/Honeybee/commit/7c2c361b5ccde2dc3a19eda54e6bd7844be3b517
I'll add in the sizing factor soon and post back here once I am done.
-Chris

**Comment by chriswmackey** [comment]
@jacoposartore ,
The sizing factor has been implemented on the 'Energy Simulation Par' component:
https://github.com/mostaphaRoudsari/Honeybee/commit/961207ec8703c0f22e0966c8eb41e007649511d3
  It seems to be working fine for me and let me know if you get to test it.  I am closing out this issue as it looks good from my end.
-Chris

**Comment by jacoposartore** [comment]
@chriswmackey,

thank you for the updates, I will test them soon.
