### ISSUE TITLE
Default outputs for export to OpenStudio component not the same as Run Energy Plus

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/Honeybee#535]
@chriswmackey 
I have added default outputs for the OpenStudio component in my latest commit as previously there weren't any.

I am writing this issue as even with the same default outputs as the Run Energy Plus component, I am not getting the same outputs. See the code on https://github.com/antonszilasi/Honeybee/blob/master/src/Honeybee_Export%20To%20OpenStudio.py#L3447 and the pictures below

![original run energyplus with defaults](https://cloud.githubusercontent.com/assets/8773483/16966904/4e042e82-4dcc-11e6-9996-a1899ec9a183.PNG)
![openstudio with defaults](https://cloud.githubusercontent.com/assets/8773483/16966906/50c697c2-4dcc-11e6-8041-eb023b2e66e4.PNG)

The outputs are appearing in the csv file but I am believe that they are not being read properly, let me know your thoughts maybe the default outputs of the export to Open Studio should not be the same?

**Comment by chriswmackey** [comment]
@antonszilasi ,
I had to clean up your code a lot:
https://github.com/mostaphaRoudsari/Honeybee/commit/6fbaffeaabb4bc307d8df61d9343ddc3eb10e93d
https://github.com/mostaphaRoudsari/Honeybee/commit/7770f0b29d50adfd4db03bfa3b65f874ea065ec1
but this is now taken care of.
-Chris
