### ISSUE TITLE
createThermBoundaries upgrade broke component

### ISSUE THREAD

**Issue by benmo1** [mostaphaRoudsari/Honeybee#543]
This report is actually about 2 bugs. I found one while investigating the first and so they are both in the same example file. 

Firstly it works with the old createThermBoundaries component (vintage Jan_26_2016) but the Jul_12_2016 createThermBoundaries component causes the writeTHERM component to fail.

I am not sure why this is. I actually discovered this as the result of investigating another issue, which still manifests. The Jan_26_2016 version creates the boundaries correctly but they don't have any color.

[boundary color example.zip](https://github.com/mostaphaRoudsari/Honeybee/files/399290/boundary.color.example.zip)

All the best and thanks so much for the continued great support,

Ben Morris

**Comment by chriswmackey** [comment]
@benmo1 ,

I was not able to re-create the case of the writeTHERM component to failing.  However, I was getting the ThermBoundaries component failing in your file and I [added an extra line such that this does not happen in the future.](https://github.com/mostaphaRoudsari/Honeybee/commit/302103f938b710dc059ea6d9f33d496ad84fcacf)

I was able to recreate the color issue and it was the same as in the previous issue.  I just forgot to fix if for the boundary curve color at the same time that I fixed the thermPolygons issue.  I have fixed this as well:
https://github.com/mostaphaRoudsari/Honeybee/commit/3fba84adc23908305b3e9615456a284df8191d5b

If you could check whether everything is working on your end, that would be great.  I tested a bunch of colors on my end that all seem to work.  If all is good, feel free to close out this issue.

-Chris

**Comment by chriswmackey** [comment]
@benmo1 ,

I checked the issue again and it all seems fine.  As such, I am closing out the issue.  Feel free to reopen if you find the error again.

-Chris
