### ISSUE TITLE
Adding HBZone.HVACSystem as a NamedTuple Broke LoadHBObjects

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/honeybee#544]
@mostaphaRoudsari ,

You mentioned to me a while back that I should change the HBZone.HVACSystem to a namedTuple.  However, this has broken the "Load HB Objects" component causing it to constantly return the following error:
1. Solution exception:No module named namedtuple_HVACSystem

I was thinking to turn the HVAC System object back to a list, dictionary or a class to fix this but I wasn't sure if you knew of a way to fix this on the "Load HB Objects" component without me having to change it.  It appears to be a limitation of cPickle as I understand it.

Once you let me know what you think, I can take appropriate action.

-Chris

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

Simply adding the namedtuple import did not fix the issue.  You can see a simple example reproducing the error here:
https://www.dropbox.com/s/dq4fcqaho38w2z9/NamedTupleError.gh?dl=0

Let me know if you get the chance to look at it.  Otherwise, I can take another crack at it in a few days.
-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey [it seems to be a bug in NamedTuple](http://stackoverflow.com/a/33797905). There seems to be workarounds but maybe we should just create a class instead of using NamedTuple?

**Comment by chriswmackey** [comment]
A class it is!
I will implement it soon.

**Comment by chriswmackey** [comment]
I forgot to close out this issue after changing the HVAC systems to be their own class.  All is good now.
