### ISSUE TITLE
Working directory in drive other than C:

### ISSUE THREAD

**Issue by gperonato** [mostaphaRoudsari/Honeybee#546]
I am running a grid-based analysis using a directory in D drive.
The files are written in the correct location, but the batch files cannot run as the cd command does not work if the project directory is not in C:

```
SET RAYPATH=.;c:\radiance\lib
PATH=c:\radiance\bin\;$PATH
c:
cd D:\mypath
```

If I change the third line to D: it works correctly.

**Comment by mostaphaRoudsari** [comment]
Hi @gperonato,
Which version of Honeybee are you using? I just checked the code again and we have already fixed this issue: https://github.com/mostaphaRoudsari/Honeybee/blob/master/src/Honeybee_Honeybee.py#L2088

**Comment by gperonato** [comment]
Sorry, I had an older version installed. It works with 0.0.59!
Thanks!
