### ISSUE TITLE
Set Default HB Natural Ventilation to Not Have Wind

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/honeybee#547]
The E+ wind driven object is really only meant for cases when you have windows on opposite sides that are roughly equal area.  Because I am realizing that many users do not immediately recognize this, I have been considering making the default to have no wind-driven ventilation.  This is both to be more conservative with airflow rates and because I am realizing that so many buildings these days do not support cross ventilation.  Along these lines, I think I will simplify the options for wind driven flow so that you either have it and it is driven by wind direction or you do not.  At the moment, there is an option to set a custom wind discharge coefficient, which ignores the wind direction and, for this reason, is not really used.

I think I will also set the default stack Discharge Coefficient to be for a single window with an insect screen.

**Comment by chriswmackey** [comment]
I think that I should also give a warning if the component senses that the zones have air walls.  It should say that that the component isn't really build to handle the calculation of effective area with interior surfaces and that you have to use a custom windandstack object for this.

**Comment by chriswmackey** [comment]
Also, this example file should not have any interior partitions in it:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Natural_Ventilation&slide=0&scale=1.0000000000000027&offset=60.38919750775841,26.411682806353127

**Comment by mostaphaRoudsari** [comment]
@chriswmackey I believe you have done this already and this can be closed.

**Comment by chriswmackey** [comment]
Yes, this is done!  Closed!
