### ISSUE TITLE
Honeybee "Simulation par" component Doesn't Have Default Value!

### ISSUE THREAD

**Issue by Omidmr** [mostaphaRoudsari/Honeybee#549]
Hi,
Dear @mostaphaRoudsari and @chriswmackey , 
When we connect HB sim par to Run EP simulation, the energy simulation run fail.
Because Honeybee "Simulation par" component Doesn't Have Default Value of "Heating Sizing Factor" (1.15) and "Cooling Sizing Factor" (1.25).

![hh](https://cloud.githubusercontent.com/assets/11173265/17834118/9c5966c6-6747-11e6-9f22-02789c1aa262.PNG)

![cooling](https://cloud.githubusercontent.com/assets/11173265/17834098/15f0ff18-6747-11e6-84b1-2c8ec399a85f.PNG)

We need to set the values of these input. 

Regarding to the tool tips:
![coolll](https://cloud.githubusercontent.com/assets/11173265/17834162/24b9e1e8-6749-11e6-93f1-8ce48c3291b4.png)
![hea](https://cloud.githubusercontent.com/assets/11173265/17834163/251c1912-6749-11e6-8b98-fa33f72bb6bb.png)

Best regards;

-Omid

**Comment by chriswmackey** [comment]
@Omidmr ,
Thanks for reporting.  This is fixed:
https://github.com/mostaphaRoudsari/Honeybee/commit/a7dffe472e20a96fb441aaf9c729def3b71e4f0c
