### ISSUE TITLE
Small fix for Lighting Density Per Area Calculator

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#551]
Hi Chris,
I'm asking for this here since it will be quicker to do than me dealing with github ... :-)
I've found that there is a small fix inn the HB_Lighting Density Per Area Calculator component. 
Line 152 should be:
    lightLoad = (lightLevel / luminousEfficacy) / (1 - efficiencyCoefficient)
instead of:
    lightLoad = (lightLevel / luminousEfficacy) / efficiencyCoefficient
The reason is that efficiencyCoefficient (= maintenanceFactor * coefficientOfUtilization) gives you how much of the load should be discounted from the full load.
Hope this makes sense for you.
Thanks,
-A.

**Comment by ayezioro** [comment]
Hi again,
Checking more thoroughly ... doesn't makes sense. So i close the issue.
Luckily you didn't get here ... sorry.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
Glad to hear it's all worked out and I agree that it's nicer to interpret the efficiency coefficient as efficiency rather than the reciprocal of it.
-Chris
