### ISSUE TITLE
Default design day sizing runs in Honeybee

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/honeybee#552]
@mostaphaRoudsari  @chriswmackey 
I just realized,

According to G3.1.2.2.1 of ASHRAE 90.1 

"Sizing Runs: Weather conditions used in sizing runs to determine baseline equipment capacities may be based on either on hourly historical weather files containing typical peak conditions or design days developed using 99.6% heating design temperatures and 1% dry bulb and 1% wet bulb cooling design temperatures"

From what I can read from the code 

https://github.com/antonszilasi/Honeybee/blob/master/src/Honeybee_%20Run%20Energy%20Simulation.py#L322-L327

We are using 0.4% drybulb and wet bulb cooling design temps, shouldn't we align our code with ASHRAE?

**Comment by chriswmackey** [comment]
@antonszilasi ,

Thanks for posting.  What version of ASHRAE is this from?  I have a sense that they may have changed this a few times over the last few years.  If that comes from the most recent version of ASHRAE 90.1 (which I think is 2013), I could see good grounds for changing it.  = Also, do you know what they say about all 7 of the design days that we use to size systems in OpenStudio:
![all design days](https://cloud.githubusercontent.com/assets/5567574/18228287/ec259660-7215-11e6-90d0-f768fd429096.JPG)

-Chris

**Comment by chriswmackey** [comment]
@antonszilasi ,

I am closing out this issue because I am pretty sure that the defaults of OpenStudio would be following ASHRAE.  Let me know if you think this is wrong.

-Chris
