### ISSUE TITLE
exportToOpenStudio and zone program definition bug

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#555]
Hi,
I've found a bug when using the HB_exportToOpenStudio while applying a zone program to the zones.
The error says:
> 1. Solution exception:'NoneType' object has no attribute 'lower'
and it happens in:

> Runtime error (MissingMemberException): 'NoneType' object has no attribute 'lower'
> Traceback:
>   line 660, in getOSSchedule, "<string>"
>   line 2454, in setDefaultSchedule, "<string>"
>   line 3609, in main, "<string>"
>   line 3762, in script
> 

If i disconnect the definition of the programs the error dissapears.
See file in: https://www.dropbox.com/s/e7uyza039becqlg/Export2OS%2BZoneProgramBug.gh?dl=0

Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,

Very good catch and thanks for reporting.  It seems we did not realize that there were zone programs  (like corridors) that don't have any equipment or people.

I just fixed this:
https://github.com/mostaphaRoudsari/Honeybee/commit/13eb55fedd740f7103dcbd917d1dc74e85706073

Thanks again!
-Chris

**Comment by orcunkoraliseri** [comment]
Hi, 

I still have same problem about building function corridor. 

How did you solve it?

Instead of using corridor, I connected office:stair as building function and it did it worked.
