### ISSUE TITLE
Filename bug and Type B photometry for IES components.

### ISSUE THREAD

**Issue by sariths** [mostaphaRoudsari/Honeybee#556]

**Comment by sariths** [comment]
Errors/bugs to fix:
1. Not sure why iron-python isn't catching these, but [251](https://github.com/mostaphaRoudsari/Honeybee/blob/master/src/Honeybee_IES%20Luminaire.py#L251) and [253](https://github.com/mostaphaRoudsari/Honeybee/blob/master/src/Honeybee_IES%20Luminaire.py#L253) are wrong. Negative indexing inside formatted strings are not supported.

2. https://github.com/mostaphaRoudsari/Honeybee/issues/540#issuecomment-243595368

**Comment by mostaphaRoudsari** [comment]
@sariths what about [len(0) - 2] as you would do it in JS?

**Comment by sariths** [comment]
Yup. I was thinking something similar. This is a trivial issue which
occurred because I was trying something too fancy with the new style string
formatting!

**Comment by mostaphaRoudsari** [comment]
@sariths should we close this issue?

**Comment by sariths** [comment]
@mostaphaRoudsari Um..yeah, let's close it for now. The thing is that I wanted to implement Type B photometry. I tried and failed once and then got bored (in that order). I will open this later when I get to it again. This is actually not a major issue anyway because if someone wants to do Type B they can still do that by converting the photometry online.
