### ISSUE TITLE
Explanation for "heating" on Read EP Result component may need to be revised

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#557]
See this: http://www.grasshopper3d.com/group/ladybug/forum/topics/words-in-the-explanation-for-heating-on-read-ep-result-component

**Comment by chriswmackey** [comment]
Fixed:
https://github.com/mostaphaRoudsari/Honeybee/commit/fb3c7f8794a22aa192f56c0fb9f57e3f66edc69f
