### ISSUE TITLE
Code not working for honeybee with Generate Colors and Display.ByGeometryColor(node)

### ISSUE THREAD

**Issue by yenhsuanho** [mostaphaRoudsari/Honeybee#559]
hello @mostaphaRoudsari ,

I followed the steps of tutorial video,
(SFDUG July 2016: LadyBug | A Parametric Environmental Plugin for Dynamo)
but now I am getting the error below in Generate Colors and Display.ByGeometryColor(node).

(As shown in the attached file)

[Generate Colors]

ERROR: 
interation over non-sequence of type StackValue.
If you think this is a bug submit an issue on github.
https://github.com/ladybug-analysis-tools/honeybeex/issues

[Display.ByGeometryColor]

Warning: One or more of the input types are not matching.
Couldn't find a version of ByGeometryColor that takes arguments of type (__array,string)

How can I achieve this? Can you teach me how to do it? 
Thank you very much! 

Finally, I found the ladybug&honeybee can not be used in the Chinese version of Revit. thanks=)

![analysis](https://cloud.githubusercontent.com/assets/22050885/18420150/54fd9208-789e-11e6-9c53-974a72ac7207.png)
![step2](https://cloud.githubusercontent.com/assets/22050885/18420154/596c442e-789e-11e6-845c-7ad6cbbf6d86.jpg)

**Comment by mostaphaRoudsari** [comment]
Hi @yenhsuanho, What are the values generated by the component after running the analysis. As far as I can see Honeybee doesn't pick up window geometries correctly.

**Comment by mostaphaRoudsari** [comment]
I just checked the first image again. In Run Radiance Simulation honeybee objects are missing!
![image](https://cloud.githubusercontent.com/assets/2915573/18420835/440299ca-784a-11e6-9f5c-e27ddfd8110f.png)
