### ISSUE TITLE
Runtime error Honeybee run EnergyPlus Component

### ISSUE THREAD

**Issue by Omidmr** [mostaphaRoudsari/Honeybee#560]
Hi @chriswmackey ,

Runtime error (KeyNotFoundException): honeybee_ExtraConstrProps
Traceback:
  line 2153, in main, "<string>"
  line 2374, in script
![image](https://cloud.githubusercontent.com/assets/11173265/18614373/8f75d90a-7da2-11e6-84d1-6abab9fab67d.png)

-Omid

**Comment by chriswmackey** [comment]
@Omidmr ,

Ji had also posted this here:
http://www.grasshopper3d.com/group/ladybug/forum/topic/show?id=2985220%3ATopic%3A1601436&xg_source=msg

It is fixed now:
https://github.com/mostaphaRoudsari/Honeybee/commit/752565a33ad925754c2d9d4c9c7f37266a19300a

-Chris

**Comment by Omidmr** [comment]
Thank you @chriswmackey .
