### ISSUE TITLE
exportToOpenStudio checkSubSurfAzTiltNorm error

### ISSUE THREAD

**Issue by saeranv** [mostaphaRoudsari/Honeybee#561]
Hey guys, getting an error where certain geometries, relatively simple, are failing to run an energy analysis in the exportToOpenStudio: "Simulation has not run because of this severe error: checkSubSurfAzTiltNorm: Outward facing angle of subsurface differs more than 90.0 degrees from base surface"

Currently am trying on DIVA to see if it's something wrong with my geometries. 

I made a GH file with this error reproduced here: https://github.com/saeranv/bibil/blob/master/src/reference/gh_files/toronto_yonge_eglinton/srf_issue_gh.gh

**Comment by mostaphaRoudsari** [comment]
Hi @saeranv, do you get the same error with runEnergyPlus component?

**Comment by chriswmackey** [comment]
@saeranv ,

Here is what is going on:
Your input geometry is 3,000 kiolmeters from the rhino origin, which essentially means that your model is about 1/2 of a continental US away from where it should be.  Normally, Rhino is ok with large distances but, in this case, the enormous number of digits in the vertices is actually brushing up against how Rhino stores floating point numbers, causing a whole range of tolerance issues (not just a failed export to OpenStudio):
![3000kmaway2](https://cloud.githubusercontent.com/assets/5567574/18693710/e25fb30e-7f71-11e6-91ac-4ef2b00c72a2.JPG)

For example, when I finally manage to run a successful simulation, here is what the label zones component produces (notice the crazy font):
![3000kmaway](https://cloud.githubusercontent.com/assets/5567574/18693713/e708f4a6-7f71-11e6-9d5b-5ee46acf110c.JPG)

Interestingly, the E+ component is able to overcome the tolerance issue in this particular case while the OS component is not.  However, moving it a bit further out will cause E+ component to fail as well.

So, the moral of the story is to stay within a reasonable distance of the Rhino model origin (~500 km or no more than the same range that you should source materials for your building.

-Chris

**Comment by saeranv** [comment]
Ah, thanks @chriswmackey! Sorry, I thought this might be a bug, but guess it's just a newbie mistake on my part.

**Comment by sariths** [comment]
@chriswmackey I didn't have a dog (bug ?) in this fight but this was some interesting bit of sleuthing!
