### ISSUE TITLE
outdoorAirReq selection "None" not affecting simulation results

### ISSUE THREAD

**Issue by jacoposartore** [mostaphaRoudsari/Honeybee#562]
Hello,

by changing the input of this parameter, the simulation runs fine but the energy used for heating or cooling if "None" is selected is the same as "Sum", whereas usually full air re-circulation gives smaller energy consumption.
Here are some pictures (see also the mechVentilationEnergy value):

"Sum = 0"
![image](https://cloud.githubusercontent.com/assets/8501837/18844137/42d64f32-841c-11e6-8052-430236996f82.png)
Here the mechVentilationEnergy value is fine

"Maximum = 1"
![image](https://cloud.githubusercontent.com/assets/8501837/18844123/2fe494e2-841c-11e6-878d-3edd77796764.png)
Here the mechVentilationEnergy value is consistent with what we expect (smaller than the first)

"None = 2"
![image](https://cloud.githubusercontent.com/assets/8501837/18844107/1ceb9502-841c-11e6-854f-6756650089fd.png)
Here the mechVentilationEnergy value should be around zero, so here is maybe something not working fine.

Here is my definition:
[outdoorAirReq Error.zip](https://github.com/mostaphaRoudsari/Honeybee/files/493679/outdoorAirReq.Error.zip)

**Comment by chriswmackey** [comment]
@jacoposartore ,

Thanks for finding this.  I never encountered this bug as I don't usually run simulations without ventilation requirements (or I do so by setting ventilationPerArea and ventilationPerPerson to 0).  It seems that, for full Ideal Air Systems like the one the OpenStudio component uses, we are not supposed to say that the Outdoor Air Method is  'None' but we are just supposed to leave the Outdoor Air object out of the file.  It's a bit different for the template Ideal Air system that the older E+ component uses.  I have fixed this here:
https://github.com/mostaphaRoudsari/Honeybee/commit/bbc1ab959397467c46f9ba0b1905143dc86dfee9
![nooutdoorair](https://cloud.githubusercontent.com/assets/5567574/18933439/c58df448-85a2-11e6-9f91-48c59a063f0d.JPG)


Thanks again,
-Chris

**Comment by jacoposartore** [comment]
@chriswmackey,

Thank you, everything is working great now!
