### ISSUE TITLE
BSDF Files Not Supported in Annual Simulation

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/honeybee#563]
I had a guess for the answer to this and I figured that I should ask it here so that others are aware of the answer.  I noticed that I was not able to run an annual simulation with a BSDF material and I wanted to ask whether this is a limitation of DAYSIM or RADIANCE?  In other words, can we expect the new version of Honeybee that is independent of DAYSIM to be able to run annual simulations with BSDF materials?

I also recognize the possibility that this is a HB error but, judging by the error, this seems to be more of a limitation of the engine.  Here's a file that shows the error and a corresponding BSDF file if anyone wants to recreate it:
https://www.dropbox.com/s/glbfw88hzysk676/2-OfficeDaylightAnnualSim.gh?dl=0
https://www.dropbox.com/s/cxrqxoi8p52coyh/Okalux_Kapipane_20_klems.xml?dl=0

-Chris

**Comment by sariths** [comment]
Hi @chriswmackey, BSDFs are already implemented, admittedly in a shaky manner at present, with the Three Phase Method in the new Honeybee. See [#113](https://github.com/ladybug-analysis-tools/honeybee/blob/master/scripts/ThreePhaseImage.py#L113) in the [Three Phase script](https://github.com/ladybug-analysis-tools/honeybee/blob/master/scripts/ThreePhaseImage.py).

We should be able to run annual simulations with BSDF material inDaysim by specifying the BSDF directly in the scene (if my assumptions about Daysim are correct). I am going to try and get your file to work over the weekend and will let you know how to goes.

**Comment by chriswmackey** [comment]
@sariths ,

You are awesome.  Just knowing that this is working in the new 3-Phase method makes me incredibly happy.  Thank you and keep rocking the daylight world!

-Chris

**Comment by sariths** [comment]
Hi @chriswmackey , with regards to the file that you posted, the BSDF material in itself appears to be  getting defined properly. However the geometry it is supposed to be modify (i.e. the window polygon) is not getting written to disk. I haven't used HB enough to know my way around childSurfaces etc. , however, a quick hack might be to define the window separately (with BSDF material and geometry) and include it in the simulation using the additionalRadfiles input as we do for electric lights...

**Comment by chriswmackey** [comment]
@sariths ,

The issue does not seem to be with child surfaces as I get the same error when I define the geometry using only HBSrfs:
https://www.dropbox.com/s/voci901x9hah16t/2-OfficeDaylightAnnualSim_SrfBySrf.gh?dl=0

Still, defining windows this way has made me realize that there are some major bugs with defining different RadMaterials for different windows of a HBZone.  From what I have found, there doesn't seem to be any way to specify different Rad Materials for the different windows if I'm using the HBZone method and assigning the BSDF to one window assigns it to all future windows of the zone.  I feel pretty bad because I misrepresented this in a presentation last week.  I will try and correct for it now.

-Chris

**Comment by chriswmackey** [comment]
Actually, I am going to take the bug label off of this issue and open up a separate issue for the HBZone workflow:
https://github.com/mostaphaRoudsari/Honeybee/issues/565

The HBZone issue is clearly a HB bug but this annual simulation one is unknown still.  In other words, this issue should just be devoted to figuring out how to run annual simulations with BSDF.

**Comment by chriswmackey** [comment]
@sariths ,

I am trying the additionaRadFiles method now but without success. Can you confirm that this is the correct type of addidionalRadFile that I should be adding?
https://www.dropbox.com/s/k100iebbjenbwcn/OkaStuff.rad?dl=0

-Chris

**Comment by sariths** [comment]
@chriswmackey, I haven't run the file with HB yet, but it appears to me that the issue is that your modifier definition is below the geometry. 

Changing this ... 
```
#GENERATED BY HONEYBEE
0kaLux polygon 9fca9cc0ddac4588a697_0
0
0
12
-8.9611  -9.1440  2.0574
8.9611  -9.1440  2.0574
8.9611  -9.1440  2.8551
-8.9611  -9.1440  2.8551


# start of material(s) specific to this study (if any)
void BSDF 0kaLux
6 0.000 C:/ladybug/Okalux_Kapipane_20_klems.xml 0.010 0.010 1.000 .
0
0
```

to this should make it work.
```
# start of material(s) specific to this study (if any)
void BSDF 0kaLux
6 0.000 C:/ladybug/Okalux_Kapipane_20_klems.xml 0.010 0.010 1.000 .
0
0


#GENERATED BY HONEYBEE
0kaLux polygon 9fca9cc0ddac4588a697_0
0
0
12
-8.9611  -9.1440  2.0574
8.9611  -9.1440  2.0574
8.9611  -9.1440  2.8551
-8.9611  -9.1440  2.8551



```

**Comment by chriswmackey** [comment]
Actually, a part of Andy's presentation here caught my eye:
![image](https://cloud.githubusercontent.com/assets/5567574/19018311/ba4266a8-8829-11e6-8546-f2285ad461c4.png)

http://www.radiance-online.org/community/workshops/2014-london/presentations/day1/McNeil_BSDFsandPhases.pdf

He states that the DAYSIM implementation is "nearly complete."  Perhaps there isn't full support yet.

-Chris

**Comment by sariths** [comment]
Aha, okay ! I wasn't quite sure of the development of Daysim as I stopped using it a couple of years ago. So, I gather you can't make BSDFs work with Daysim even when they are added to the scene using additionalRadFiles ?

**Comment by chriswmackey** [comment]
@sariths ,

I tried reversing the order of the .rad file without success.  I feel 80% sure that it's an issue with DAYSIM as none of the BSDF files are working no matter what I try but they all work with the straight-to-radiance simulations.

I feel ok leaving this issue the way it is knowing that it will work in your new 3-Phase implementation.  I will leave it open just so that people know the current status.

-Chris

**Comment by sariths** [comment]
Hi @chriswmackey, thanks for testing this out. I had no idea that BSDFs weren't ported into Daysim yet. The BSDF primitive became [a first class citizen of Radiance](https://www.radiance-online.org/community/workshops/2011-berkeley-ca/presentations/day2/GW5_BSDFFirstClass.pdf) back in 2011, so I assumed that by now the BSDF functionality was supported in Daysim as well.

**Comment by mostaphaRoudsari** [comment]
Hi @chriswmackey and @sariths. If I'm not mistaken BSDF was never supported by Daysim4 and the earlier versions. 

For anyone who may read this discussion later. Th implementation is done in the newer version of Honeybee which is not yet publicly released for Grasshopper.

**Comment by chriswmackey** [comment]
Now that we know that annual BSDF simulations aren't a part of DAYSIM and we have support for annual BSDF simulations in HB+, I'm closing this issue out.
