### ISSUE TITLE
Can't Model BSDF Skyights

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/Honeybee#564]
I have tried about 3 different ways to specify a BSDF skylight and none of them are affecting the final Illuminance result:
https://www.dropbox.com/s/cfwsk758uw8utt7/CantSpecifyBSDFSkylights.gh?dl=0
https://www.dropbox.com/s/cxrqxoi8p52coyh/Okalux_Kapipane_20_klems.xml?dl=0

The geometry is written into Radiance correctly and it definitely has to do with the material because, once I change it to a non-BSDF material, I get light in the test box.  It's possible that there is just something wrong with the material.  Does anyone have another sample BSDF file that I could run to check if it is the BSDF file causing the issue?

-Chris

**Comment by sariths** [comment]
Hi @chriswmackey, try these: https://www.dropbox.com/sh/3zu3pxvm9zgz4x0/AADBaWdtaJFIu4D4eUQySnaYa?dl=0

Two of those (ven0 and ven45) are venetian blinds, however, that really shouldn't matter as far as the troubleshooting aspect of the simulation goes.

**Comment by sariths** [comment]
![10-1-2016 9-33-34 pm](https://cloud.githubusercontent.com/assets/10361848/19017977/ce2dcc80-881e-11e6-993f-536022d32d10.png)

Hi @chriswmackey , the culprit was an incorrectly assigned hemispherical sampling parameter for the BSDF material. See the part highlighted through red ellipses above..

**Comment by chriswmackey** [comment]
@sariths ,

You are awesome.  Let me see if I can fix this now.  Am I correct in understanding that these 3 numbers should correspond to the normal direction of the HBSrf that they are being applied to?

-Chris

**Comment by chriswmackey** [comment]
I can also verify that it is working correctly on my system for all of the BSDF files once I change the  hemispherical sampling parameter.

**Comment by sariths** [comment]
@chriswmackey, Actually any direction that isn't parallel to the normal direction of the surface should work. In your case the directional-normal of the skylight was either facing upwards or downards. So the simulation wasn't working with the original 0 0 1. Changing that to 0 1 0 or -1 0 0 etc. will make it work.

**Comment by chriswmackey** [comment]
@sariths ,

Understood.  I just ran the material with a few different hemispherical sampling parameters and I got fairly similar results.

Can I ask one final question then: Does Radiance know the direction that the cells (or blinds) that my material is facing based on the orientation of the rad mesh faces?  If so, I think that I might just change this sampling parameter to be something that will pretty much never be in the plane of a surface (like a set of random decimal numbers).

Thanks again.
-Chris

**Comment by sariths** [comment]
@chriswmackey 

> Does Radiance know the direction that the cells (or blinds) that my material is facing based on the orientation of the rad mesh faces? 

I had posed a similar question to the creator of Radiance when I was working at LBNL this summer.  His answer to that was pretty much along the same lines as what you mentioned above. I think if you were to ensure that the plane specified by those three numbers are never in the same plane as the the normal, it will work in almost all cases. 

Things might get interesting, however, if someone tries to model a  tessellated hemisphere or something with BSDFs !

**Comment by chriswmackey** [comment]
@sariths ,

Thank you very much for the response.  I am realizing that the reversing of the hemispherical sampling parameter has the same effect as flipping the direction of the HBsurface and I get similar results as long as the parameter is a vector in the same hemisphere about the HBSrf normal plane.  So it's ok if the vector isn't perfectly in the plane of the HBSrf.  It just has to be +/- 90 degrees of being correct.  Moreover, I don't need to worry about this parameter much if the BSDF is symmetrical about the plane of theHBSrf plane (so 0 degree Venetian blinds are ok with anything except a perfectly parallel vector but I have to be careful with 45 degree Venetian blinds because this parameter affects whether it's 45 deg up or down).

Very cool stuff.  I am going to write this into the description of the input and put in a better devault now.

-Chris

**Comment by chriswmackey** [comment]
Done!

https://github.com/mostaphaRoudsari/Honeybee/commit/721d817844c11b2cf94c1bbbf82431828a2c6d09
