### ISSUE TITLE
HBzones Can Only Have One Type of Window RadMaterial

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/honeybee#565]
@mostaphaRoudsari ,

This seems to be a bug with the way that the HBZone2Rad workflow happens.  I am trying to assign two different RadMaterials to two different windows of a zone and I use the same workflow that I would use for the E+ workflow:
![image](https://cloud.githubusercontent.com/assets/5567574/19017931/bfe81636-881d-11e6-99b9-1a53a674e677.png)

However, the Run Simulation Component is writing both windows as the same material:
![image](https://cloud.githubusercontent.com/assets/5567574/19017935/d35612fe-881d-11e6-84e4-cf9805e5653b.png)

Here is a file that demonstrates the issue:
https://www.dropbox.com/s/pxlv8dmwoen93af/HBZonesCanOnlyHaveOneWindowRadMaterial.gh?dl=0

-Chris

**Comment by mostaphaRoudsari** [comment]
@chriswmackey this looks like a bug. As a workaround, you can connect both openings and materials to the same component, which should work fine.  Thanks for reporting.

**Comment by NENEN** [comment]
@mostaphaRoudsari, do you mean to plug in the two openings together in one list, and the two materials together as a separate list?

**Comment by chriswmackey** [comment]
@NENEN ,
Yes, this is what @mostaphaRoudsari means.  Plug in a list of geometries and a corresponding list of materials in the same component.
-Chris

**Comment by chriswmackey** [comment]
I encountered this issue again today for which it was difficult to use the workaround.  I'd say that this is the last major bug in the project and it really should be fixed soon.

**Comment by chriswmackey** [comment]
I finally couldn't stand this bug any longer.
Fixed.
https://github.com/mostaphaRoudsari/honeybee/commit/0621e54740237c0016b5f8ef648185b528d7d455

**Comment by mostaphaRoudsari** [comment]
@chriswmackey thanks for getting this fixed!

**Comment by NENEN** [comment]
@chriswmackey I will definitely take advantage of this. Thanks!
