### ISSUE TITLE
Minor bugs in EPWindowShades for vertical shades and glzParam input parameters 

### ISSUE THREAD

**Issue by saeranv** [mostaphaRoudsari/Honeybee#566]
Hey guys, I recently started using this component while working on a project, and have run into a couple of issues when: (a) using the vertical option for the horOrVertical_ input and (b) using certain combinations of the glzParam component. 

I've been rewriting it as needed, here's my revised code (from the 'VER 0.0.60\nSEP_17_2016'):
https://github.com/saeranv/Honeybee/commit/08d42c35cb6fe12e0fcb0da3d75521e2c5930cfd

And sample file, with my revised/working component: 
https://drive.google.com/file/d/0B1aL4rZ85UMSMzliLWNaX1k0S0k/view?usp=sharing

Bugs that I've addressed:
1. Component fails when vertical option chosen and _numOfShds is one.
![ep_shade_vertical_fin_false](https://cloud.githubusercontent.com/assets/1685956/19126110/a47f7442-8b07-11e6-8daf-b13d4a7b98b3.JPG)

2. Component fails when glzParam component is set to zero for certain orientations, for vertical shades.
![ep_shade_vertical_fin_glzparams_conflict](https://cloud.githubusercontent.com/assets/1685956/19126334/7afe7d2e-8b08-11e6-8a33-ccf8f7979343.JPG)

3. Component produces no output if you try and set different combinations of vertical/horizontal shades by the distBetween option, and the horizontal shades by the _numOfShds option. 
![ep_shade_vertical_fin_glzparams_conflict_distbtwn](https://cloud.githubusercontent.com/assets/1685956/19126400/c560974e-8b08-11e6-9c0c-2432af6ad971.JPG)

Let me know my edits look!

**Comment by chriswmackey** [comment]
@saeranv ,

Sorry for the late response and thank you so much for fixing these issues!  I checked out your file and your commit and everything looks great.  SEP 17 is still the last version of this component so, if you are able to fix your pull request, you should be able to send it without overwriting any work.

Sending a pull request would really be the best way of bringing in your fixes.  It ensures that you get credit for the contribution in the github record and helps us all keep track of how the edits were made.  I know that it can be a mess sometimes, though as this comic would tell you:
https://xkcd.com/1597/

Still, I think you should be able to get it working in the following way:
1) Revert your current commit.
2) Make a pull request from the master branch under mostapha's account to your branch
3) Re-Commit your changes to this component on your branch.
4) Send a pull request to the main Mostapha branch and we will merge it in!

Keep me posted when you are able to give this a shot.
-Chris

**Comment by saeranv** [comment]
Thanks @chriswmackey . While I understand steps 3,4, I don't understand 1,2. Are these steps done in order to sync my fork of the repository to keep it up-to-date with the upstream repository? 

It sounds easier than using git bash for sure, but I'm not sure I understand how it achieves this. Aren't pull requests used to merge changes back to the master? How can I make a pull request from the master branch to my branch... ? I've tried google but haven't been able to find anything on this.

**Comment by chriswmackey** [comment]
@saeranv ,

Pull requests are used both to bring your changes into the master branch and to sync your branch with the master branch.

In your usual workflow that you would use to send a pull request to the master branch, you can hit the button that says "switch the base" to set up a pull request in the opposite direction.

Let me know if this works or if you need more information.

-Chris

**Comment by saeranv** [comment]
@chriswmackey,  

Thanks for explaining that, I always have issues syncing branches using the command line. This is much better.

I just did it, and it looks like my fork is up to date with Mostapha's. So, I think we're ready to merge. 

FYI I did make some additional changes since the last post, finding some additional edge cases where my modifications failed. Fairly minor adjustment, and I tested everything over again. Example file is here if you'd like to take a look: 

https://drive.google.com/file/d/0B1aL4rZ85UMSMzliLWNaX1k0S0k/view?usp=sharing

**Comment by chriswmackey** [comment]
@saeranv ,

I'm glad that you were able to navigate the perils of github pull requests. Everything looked good and so it's been merged in.  In the future, you should also remember to update the date on the component whenever you produce a newer version.  I updated the date on the component here:
https://github.com/mostaphaRoudsari/Honeybee/commit/bb42065dd2b8e30e890d6e3ff9d2abdbcc0a0be2

I think we're ready to close out the issue.  Thanks again for all of the fixes, @saeranv !
-Chris
