### ISSUE TITLE
Add in Honeybee Support for OpenStudio 2.0

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/honeybee#567]
OpenStudio 2 is introducing some major changes to how OpenStudio works. Some of them are good news but some about the API makes me nervous. I hope the basic workflow just works fine with the new version and we will figure out the rest (e.g. measures, etc) as we go.

**Comment by mostaphaRoudsari** [comment]
1. Importing C# library in IronPython threw 'OpenStudio.OpenStudioModelCorePINVOKE'
https://github.com/NREL/OpenStudio/issues/2371

2. Installation doesn't include Radiance and Perl. If this is a final decision it will affect our workflows for next releases of honeybee.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

This is good to know.  Once we get past the PINVOKE issues, I can put some time into addressing any API changes.  We'v always known that the measures components would have to be revised when formats became more established and, if certain API features are not working at first, we will hopefully get errors that will point us towards fixing them.  I am far less nervous about API revisions and changes to measures than things like PINVOKE.

-Chris

**Comment by chriswmackey** [comment]
Reading through the list of changes, we might have to make two separate OpenStudio components: one for the older version and another for 2.0.

It looks like most of the changes in the API are NOT in areas that we are using but, if this proves to not be the case, it might be best to try and support both versions for a little bit.

Let's get past the PINVOKE first.

**Comment by mostaphaRoudsari** [comment]
@chriswmackey , now that the PINVOKE issue is solved, I checked and the component works fine for a simple model. The only caveat is that `RunEPlus.bat` is not shipped with OpenStudio anymore. We need to use EnergyPlus CLI to run the analysis.

**Comment by chriswmackey** [comment]
@mostaphaRoudsari ,

Woohoo!  Glad that it's resolved!  Switching to the CLI seem do-able.  Perhaps we can deal with the two ways of running the IDF using duck typing and that will hopefully avoid the need for a whole new OpenStudio component.

-Chris

**Comment by arif-hanif** [comment]
@mostaphaRoudsari @chriswmackey i am going through same challenges will be sure to share anything i learn as well

**Comment by chriswmackey** [comment]
Now that the OpenStudio team has addressed both the PINVOKE error and the IDF/gbXML Translators, I'm changing the title of this issue to implement version 2.0 once it's released.

**Comment by antonszilasi** [comment]
@mostaphaRoudsari  @chriswmackey  Hi guys, I'm wondering what the status is here, is the current OpenStudio component code going to work with the OpenStudio component?

**Comment by mostaphaRoudsari** [comment]
See this: https://github.com/mostaphaRoudsari/honeybee/commit/8748a4b6b9f52c11e37de4941b3e40813324f2cb

**Comment by chriswmackey** [comment]
We now support all versions of OpenStudio 2.x.  Closed!
