### ISSUE TITLE
Evalglare v1.31 in Radiacne v5.0.a.12 is not working with Honeybee glare analysis component

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/honeybee#568]
Check [this discussion](http://www.grasshopper3d.com/group/ladybug/forum/topics/evalglare-v1-31-in-radiacne-v5-0-a-12-is-not-working-with).

**Comment by mostaphaRoudsari** [comment]
not a honeybee bug apparently:
http://www.radiance-online.org/pipermail/radiance-dev/2016-October/001645.html

**Comment by chriswmackey** [comment]
Since this is not a HB bug, we can close out this issue.

**Comment by mostaphaRoudsari** [comment]
Just for the reference it has been solved in the new release of Radiance.
