### ISSUE TITLE
Honeybee_Set Energyplus Zone Thresholds. Missing inputs

### ISSUE THREAD

**Issue by devngc** [mostaphaRoudsari/Honeybee#574]
Hi @chriswmackey,

In Honeybee_Set Energyplus Zone Thresholds component, there are three inputs in the code named, daylightIllumSetPt_, daylightCntrlPt_ and, daylightCntrlFract_. However, the same are not there as inputs for the components. Can you please take a look? I believe, it just needs adding back those inputs with list access.

Thanks,
Devang

**Comment by mostaphaRoudsari** [comment]
You just need to update Honeybee and take the component from the tab.

![image](https://cloud.githubusercontent.com/assets/2915573/20776382/2b6e65ce-b72e-11e6-818d-d794e05eb28d.png)
