### ISSUE TITLE
Window shade generator - ShadingHeight issue

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#576]
Hi,
As for this discussion:
http://www.grasshopper3d.com/group/ladybug/forum/topics/window-shade-generator-sometimes-won-t-output-hb-object?page=2&commentId=2985220%3AComment%3A1637339&x=1#2985220Comment1637339
i can't understand the limitation of shadingHeight to 1 mt, so beyond this no HBObjects are created.
Can this be explained?
Thanks,
-A.

**Comment by saeranv** [comment]
@chriswmackey 

For further clarification @ayezioro is talking about this line: https://github.com/mostaphaRoudsari/Honeybee/blob/master/src/Honeybee_EnergyPlus%20Window%20Shade%20Generator.py#L898  - which I found to be stopping the production of an HBObject in the linked GH post. 

Is my interpretation correct? 

S

**Comment by chriswmackey** [comment]
@ayezioro and @saeranv ,

I have added a response on the GH group, which should explain the issue.  As such I'm closing out this one but feel free to open it again if you feel the explanation is not complete.

-Chris
