### ISSUE TITLE
Tunred HB HVACSystems Into a Class - ISSUE

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#577]
Hi Chris,
A recent change (as in the subject) leads to a bad function of the HB_runEnergySimulation component (the HB_exportToOpenStudio works fine so far).
It complains about:

> Runtime error (TypeErrorException): 'EPHvac' object is not subscriptable
> Traceback:
>   line 2229, in main, "<string>"
>   line 2360, in script
I assume this error is related to the change, since it was working before.
I'll apreciate fixing this one since i'm in the middle of some simulations ...

Thanks,
-A.
![capture](https://cloud.githubusercontent.com/assets/7526023/20485389/fb6c6ab4-b003-11e6-8c3b-ca026cc0c7f2.JPG)

![Uploading Capture.JPG…]()

**Comment by chriswmackey** [comment]
@ayezioro ,

Thank you for reporting this. I will fix it once I get off the train that I am on right now.

-Chris

**Comment by chriswmackey** [comment]
@ayezioro ,

Sorry this took a while.  The issue is fixed:
https://github.com/mostaphaRoudsari/Honeybee/commit/c7e8aa0742f4c1b005d1a57315d14a979e610291

-Chris

**Comment by ayezioro** [comment]
Thanks Chris!!
