### ISSUE TITLE
OpenStudio component fails to read the header of epw file

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/Honeybee#578]
http://www.grasshopper3d.com/group/ladybug/forum/topics/openstudio?commentId=2985220%3AComment%3A1650027&groupId=2985220%3AGroup%3A658987

**Comment by chriswmackey** [comment]
This issue is fixed!
https://github.com/mostaphaRoudsari/Honeybee/commit/c54e4b5137fe584b99de6704ec24284afc8b595f
