### ISSUE TITLE
HBZones before and after HB_IndoorViewFactor - Differences

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/Honeybee#579]
Hi,
Per this discussion, Mostapha recommends to open an issue here:
http://www.grasshopper3d.com/group/ladybug/forum/topics/hbzones-before-and-after-hb-indoorviewfactor-differences?commentId=2985220%3AComment%3A1650143&xg_source=msg_com_gr_forum
Thanks,
-A.

**Comment by chriswmackey** [comment]
I put a response on the GH group because the issue seems like more of a request for an explanation than a bug.  If it is a bug, we can pick up the discussion here.

**Comment by chriswmackey** [comment]
This issue was solved on the GH forum
