### ISSUE TITLE
itegrating light to E+ thermal analysis for multiple zones

### ISSUE THREAD

**Issue by THEtantaarchitect** [mostaphaRoudsari/Honeybee#581]
hi guys
thank you so much for your continuous support 

how can we do this integration for multiple zones at the same run
http://hydrashare.github.io/hydra/viewer?owner=mostaphaRoudsari&fork=hydra_1&id=Integrated_Daylight_and_Energy_simulation&slide=0&scale=1&offset=0,0

your help is very appreciated 
thanks
anas

**Comment by antonszilasi** [comment]
@THEtantaarchitect if you want to create a series of runs with daylighting and energy analysis on each run use the Ladybug fly component and connect it up to all the sliders that you are changing, it will iterate through each configuration until all the runs are complete. 

Be sure to record your results to excel though, using the flux components is a good way to do this!

**Comment by THEtantaarchitect** [comment]
@antonszilasi thank you for your reply 
but the thing is i have a 4 storey building with almost 20 zones i used honeybee masstozones components so there are no sliders to change  and i'll do this for other iterations so your comment will be helpful then 
but i thought there might be a way to do the same building's 20 zones at one run if possible

**Comment by antonszilasi** [comment]
@THEtantaarchitect  I'm not really sure what you mean. If you want to post a description on the Grasshopper forum with pictures with a detailed file we will be able to help. You can link your post here.

**Comment by THEtantaarchitect** [comment]
http://www.grasshopper3d.com/group/ladybug/forum/topics/lighting-integration-for-multiple-zones?xg_source=activity

thank you

**Comment by mostaphaRoudsari** [comment]
@THEtantaarchitect see this discussion: http://www.grasshopper3d.com/group/ladybug/forum/topics/pick-sensor-for-annual-dl-analysis-in-multiple-zones?xg_source=activity

By default honeybee generates a separate lighting schedule for each list of points in a separate branch. These schedules can be then used to set up the lighting schedule for each zone. You should only make sure that the input for test points is grafted correctly and is not flattened. If you connect multiple zones to generatePoints component it does the grafting by default.
