### ISSUE TITLE
About Path 

### ISSUE THREAD

**Issue by yenhsuanho** [mostaphaRoudsari/Honeybee#585]
hello @mostaphaRoudsari ,

I followed the steps of tutorial video,
(SFDUG July 2016: LadyBug | A Parametric Environmental Plugin for Dynamo)
but now I am getting the error  about "Run radiance simulation" 

(As shown in the attached file)
How can I achieve this? 
Thank you very much!

![w1](https://cloud.githubusercontent.com/assets/22050885/21456669/d3fe14b2-c964-11e6-88e8-44068eee2fa6.png)

**Comment by mostaphaRoudsari** [comment]
@yenhsuanho if you read the error message you can see that the component fails to create the folder since you typed an illegal path. try: `c:\12ladybug` instead of **:** c\12ladybug. The **:** is in the wrong place.

**Comment by yenhsuanho** [comment]
thank you @mostaphaRoudsari 
but still not work 
![w1](https://cloud.githubusercontent.com/assets/22050885/21457226/8e1afa9c-c968-11e6-9cbc-84a23a4f02e0.png)

**Comment by mostaphaRoudsari** [comment]
Do you have Radiance installed in c:\radiance? It's not currently part of the installation and you have to install it separately.

**Comment by mostaphaRoudsari** [comment]
Also please post issues related to dynamo to https://github.com/ladybug-analysis-tools/honeybee-plus/issues
Thanks!

**Comment by yenhsuanho** [comment]
oh .. I did not install radiance
Where can I download this ?
Thank you very much!

**Comment by mostaphaRoudsari** [comment]
https://github.com/NREL/Radiance/releases/download/5.0.a.12/radiance-5.0.a.12-win64.exe

Make sure to install it to c:\radiance and not c:\Program Files\radiance which is the default installation path. You may also need to recreate the recipe so it picks up the new path.

**Comment by yenhsuanho** [comment]
I  installed radiance ,but still not work 
can you check it for me ?  thanks you  
![default](https://cloud.githubusercontent.com/assets/22050885/21458185/6af1dd04-c96f-11e6-817d-77f9d7f07ad9.png)

![w3](https://cloud.githubusercontent.com/assets/22050885/21458132/03d53b48-c96f-11e6-8a58-75e325640a2b.png)

**Comment by mostaphaRoudsari** [comment]
Hmmm. My best guess is that radiance path is not added to your system, so the radiance run fails and you don't get the results.

Sorry for all the issues. Honeybee for Dynamo is pretty beta at this point. All of these issues will be addressed in the next release. You need to add c:\radiance\bin and c:\radiance\lib to PATH and RAYPATH. Radiance installation should do it for you by default but seems it has failed to do it on your machine. You can set them under Environment Variables in Windows System Properties > Advanced.

**Comment by yenhsuanho** [comment]
thank you for your help @mostaphaRoudsari  
I'll try again

**Comment by yenhsuanho** [comment]
hello @mostaphaRoudsari ,
I succeeded in the step you told me thanks so much! And one more question, 
Is it possible to put the illumination(lux) into the Excel, which means to export the result to Excel form?
Hope to hear from you soon !
![11](https://cloud.githubusercontent.com/assets/22050885/21466254/cf430362-c9fd-11e6-9494-4f9e65cb35d0.png)

**Comment by mostaphaRoudsari** [comment]
@yenhsuanho, nice!
yes. you can. Just take the values from run daylight analysis node and write them to excel. You can both use Dynamo nodes or one of the available packages for Dynamo to write it to excel.
