### ISSUE TITLE
CreateHBSrfs Nov_04_16 doesn't accept BREPs

### ISSUE THREAD

**Issue by hwoehrle** [mostaphaRoudsari/honeybee#586]
Hi Mostapha,

when i connect CreateHBSrfs Nov_04_16 with a brep i get an error "You need a newer version...". Honeybee is updated with the update-tool.

if i replace the userobject with version  Aug_10_2016 everything works as expected.

Best regards,
Heiko
![error_createhbsrfs](https://cloud.githubusercontent.com/assets/22678487/21887271/98124800-d8bf-11e6-89d4-9627d537e435.png)

**Comment by hwoehrle** [comment]
sorry, my fault. I did not realize that i have to replace the honeybee_honeybee component after running an update...

**Comment by chriswmackey** [comment]
@hwoehrle ,
Glad that you see how the component warnings are intended to work. You can also set a True boolean to the updateThisFile_ option on the Honeybee_Update Honeybee component to sync all of your components on the canvass with the github.
-Chris

**Comment by hwoehrle** [comment]
Great, thanks for this hint. I already started to replace the components manually... :-)
