### ISSUE TITLE
HB_ThermalAutonomy - _totalThermalEnergy_ input

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/honeybee#595]
Hi,
I've found a small bug in the ThermalAutonomy component.
As it is now it complains about:
> 1. Not all of the connected _totalThermalEnergy_ data is for total thermal energy.

Changing lin3 347 from:
    if _totalThermalEnergy_.BranchCount > 0: checkData3, checkData4, totEnergyUnits, totEnergyHeaders, totEnergyNumbers, totEAnalysisPeriod = checkCreateDataTree(_totalThermalEnergy_, "_totalThermalEnergy_", **_"Total Thermal Energy"_**)

to:
    if _totalThermalEnergy_.BranchCount > 0: checkData3, checkData4, totEnergyUnits, totEnergyHeaders, totEnergyNumbers, totEAnalysisPeriod = checkCreateDataTree(_totalThermalEnergy_, "_totalThermalEnergy_", **_"Total Thermal Load"_**)

fixes the issue (Or changing the output name on the readEPResult from totalThermalLoad to totalThermalEnergy)
Thanks,
-A.

**Comment by chriswmackey** [comment]
Thank you @ayezioro ,
This must have been a bug from several months ago.  I've just fixed it now:
https://github.com/mostaphaRoudsari/honeybee/commit/d68ac5eb02d1444410c2bf76fda210dad7002226

-Chris
