### ISSUE TITLE
Honeybee Runtime error Invalid integer literal

### ISSUE THREAD

**Issue by Omidmr** [mostaphaRoudsari/honeybee#598]
Hi @mostaphaRoudsari  and @chriswmackey,

I got this error after update.
Runtime error (ValueErrorException): Invalid integer literal
Traceback:
  line 9049, in <lambda$223>, "<string>"
  line 9049, in script

![new text document](https://cloud.githubusercontent.com/assets/11173265/22563356/7b0b6cd2-e995-11e6-8469-9edb3a4b69db.PNG)

King regards,
-Omid

**Comment by mostaphaRoudsari** [comment]
@Omidmr can you try the new version? I just made a modification in the method that finds OpenStudio installation version.

**Comment by Omidmr** [comment]
@mostaphaRoudsari, yes. I reinstalled the new version of Honeybee and update that.
Without any change. The error persists yet.
Thanks.

**Comment by Omidmr** [comment]
@mostaphaRoudsari ,
Update: I reinstalled the OpenStudio. The error was fixed!
for But I do not know why did it happen?
many thanks for taking the time to answer.

Please reopen this issue if another issue exists.

King regards,
-Omid

**Comment by mostaphaRoudsari** [comment]
Hi @Omidmr! Thank you for checking. Can you tell me where was OpenStudio installed initially before you re-install it? I'm trying to understand how does the script fail to find the version.
At the minimum we need to have an exception for this error.

**Comment by Omidmr** [comment]
Hi @mostaphaRoudsari, You're welcome.
That locate the same path and same version before and after.
In this path:  C:\Program Files\OpenStudio 1.14.0
It was a little strange. For solving the problem that was necessary to refresh the OpenStudio(Uninstall and Install).
Thanks,
King regards,
Omid
