### ISSUE TITLE
Daylighting controls with conditioned and nonconditioned zones

### ISSUE THREAD

**Issue by antonszilasi** [mostaphaRoudsari/honeybee#600]
@mostaphaRoudsari 

I found that daylight controls only appear when zones are conditioned: See the code here: 
https://github.com/mostaphaRoudsari/honeybee/blob/master/src/Honeybee_Export%20To%20OpenStudio.py#L3808-L3811

Wouldn't it make more sense for the controls to appear regardless of the whether the zones are conditioned or not?

**Comment by mostaphaRoudsari** [comment]
@antonszilasi thanks for reporting this. @chriswmackey has implemented this and knows more. I had a quick look and I think you're right but again Chris is the right person to comment on this.

**Comment by chriswmackey** [comment]
Thanks for catching this bug @antonszilasi .  I just fixed it:
https://github.com/mostaphaRoudsari/honeybee/commit/9e7495ce2838ada0abdf81de1cecc5489f098933
