### ISSUE TITLE
Set Ep Air Flow possible Bug

### ISSUE THREAD

**Issue by devngc** [mostaphaRoudsari/honeybee#602]
on [this](https://github.com/mostaphaRoudsari/honeybee/blob/master/src/Honeybee_Set%20EP%20Air%20Flow.py#L509) line, should it not be windDisCoeff == 1 ?

**Comment by mostaphaRoudsari** [comment]
Thanks @devngc! I think it is a bug but let's wait for @chriswmackey's input.

**Comment by chriswmackey** [comment]
Thank you very much for catching this @devngc ,
I just fixed it here:
https://github.com/mostaphaRoudsari/honeybee/commit/86122238d210f48ae102140a6cadc4d96dd3a973

**Comment by devngc** [comment]
Thank you @chriswmackey!
