### ISSUE TITLE
read results for multiple zones day lighting analysis 

### ISSUE THREAD

**Issue by THEtantaarchitect** [mostaphaRoudsari/honeybee#604]
i'm trying to read the lighting analysis results for multiple zone in order to use it as schedules in HBZones for energy analysis 
the process as i understand is as follows:
1 Honeybee take the model to radiance and day sim to do the analysis and come back with results to grasshopper 
2 Honey bee read the lighting results and add it to "HBzones"  before energy analysis 
3 HBzones delivered to energy sim by honey bee 

The main glitch is in 2
It needs to be ran twice to have a good understanding of the results and link it properly to its zones 

My assumption and what I am going to test next until we meet is 
The lighting analysis component rearrange the order of zones in the list  in a different way other than how it was delivered to it in the first place 

to understand the full picture about the issue:
http://www.grasshopper3d.com/forum/topics/lighting-integration-for-multiple-zones?groupUrl=ladybug&xg_source=activity&groupId=2985220%3AGroup%3A658987&id=2985220%3ATopic%3A1657139&page=3#comments

i made a light version of my work and attached it to the discussion in the link above so you can understand the problem better

regards
anas

**Comment by THEtantaarchitect** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/20110471/23065111/73a1f336-f4d9-11e6-9eb5-654cad7b9d18.png)

a photo illustration of the component crash to get a better picture of it

**Comment by chriswmackey** [comment]
@THEtantaarchitect ,

That results because of a bug in DAYSIM which has existed for years and no one knows where it comes from. All I know is that it usually goes away if you rerun the results importer component. The new revision of Honeybee will not have this as it is no longer using DAYSIM to run annual analyses.

**Comment by THEtantaarchitect** [comment]
hi Chris
what are you going to use for annual daylight and when is it going to be released 
regards
anas

**Comment by chriswmackey** [comment]
@THEtantaarchitect ,
@mostapharoudsari will be releasing [HoneybeePlus](https://github.com/ladybug-analysis-tools/honeybee-plus) soon within the next few weeks. It will be a while before we get all of the features of this Honeybee github into HoneybeePlus but the first release will have annual daylight simulations run with just Radiance (and not DAYSIM).
-Chris

**Comment by mostaphaRoudsari** [comment]
@THEtantaarchitect, @chriswmackey I just addressed this issue during the weekend: https://github.com/mostaphaRoudsari/honeybee/commit/5f6ef6cdc1e6d19cec9cd07182558dd7916fccef

@THEtantaarchitect update your definition and it should work fine.

**Comment by THEtantaarchitect** [comment]
@mostaphaRoudsari thank you Mustapha very much I'm testing it right now
