### ISSUE TITLE
Honeybee_Microclimate_Map_analysis PET

### ISSUE THREAD

**Issue by Vyrwn** [mostaphaRoudsari/honeybee#608]
Hi @chriswmackey ,

I was checking the Microclimate Map component because I want to get the effect of vegetation and shading on the MRT and then on outdoor comfort. 

The UTCI version works fine, but when i plugged the PET component, there were some errors. 

PETComfMtx is not defined
line 1915: 
    for lineCount, line in enumerate(PETComfMtx) 

same for PETCategoryMtx
line 1928:
    for lineCount, line in enumerate(PETCategoryMtx)

I changed them into PET_ComfMtx and PET_CategoeryMtx respectively and seems to be fine. I will make sure there is no other error and will pull request.

**Comment by chriswmackey** [comment]
@Vyrwn ,
Thank you very much for finding the bug.  This must of happened because of a change that I made in which I forgot to update the PET maps.  I'll merge it in once you send the pull request.
-Chris

**Comment by chriswmackey** [comment]
Also, if you have a GH file that recreates the issue, I can fix if myself (if this would be faster than you sending the pull request).

**Comment by chriswmackey** [comment]
@Vyrwn ,
I could not recreate the issue on my end and everything is running fine.
![image](https://cloud.githubusercontent.com/assets/5567574/24885255/7824d066-1e1b-11e7-8f63-11c58e57caba.png)

As such, I am closing out the issue and feel free to reopen it if I am mistaken.
-Chris
