### ISSUE TITLE
Falsecolor link not working

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/honeybee#611]
Hi,
FYI the link in the installing instructions for the falsecolor.exe is broken.

Thanks,
-A.

**Comment by ayezioro** [comment]
Hi,
Since i told my students to install all that is need to work with LB+HB, and the links for falsecolor and evalglare are not working i sent them the files. Hope it is fine. Just FYI.
Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
Thanks Abraham! If you're installing recent versions of Radiance evalglare is part of the standard distribution. We should probably remove it from the installation process.
Back to FalseColor we need to check the license and if the distribution is permitted, which I think it is, then just copy it to the resources folder.

**Comment by ayezioro** [comment]
OK. Good to know. I'll take out from my instructions the evalglare stuff.
Thanks,
-A.

**Comment by mostaphaRoudsari** [comment]
Added it to resources folder and updated the link.
