### ISSUE TITLE
Rhino 5 crash when  calculate the Psychrometric chart.

### ISSUE THREAD

**Issue by zhangzhennico** [mostaphaRoudsari/honeybee#613]
I have an issue that rhino 5 crash when I calculate the Psych chart, which is a very basic and simple program. The grasshopper and LH are all the latest version.this is the warming and error below, I would be grateful if any one could give me some suggestions. Thank you so much.

![qq 20170323134839](https://cloud.githubusercontent.com/assets/26587689/24233838/9e27ea0a-0fcf-11e7-99d2-2bc90f5ee11a.png)
![qq 20170323134924](https://cloud.githubusercontent.com/assets/26587689/24233839/9e280bb6-0fcf-11e7-855e-23ec23ce9243.png)

**Comment by mostaphaRoudsari** [comment]
Hi @zhangzhennico, This is a ladybug issue and not honeybee but regardless this was a bug in Rhino which they fixed two years ago. Try to update Rhino to the latest version and it will work fine.

**Comment by chriswmackey** [comment]
Thanks for taking care of this @mostaphaRoudsari
