### ISSUE TITLE
Glazing based on ratio

### ISSUE THREAD

**Issue by apalapa86** [mostaphaRoudsari/honeybee#619]
Hi ... I was following the video playlist for honeybee, and I seem to be having a difficult time with the glazing based on ration. When I follow the procedure in the video, I kind of get windows that are from floor to floor (See the attached picture), and modifying the window height and sill height does not seem to change anything. 

Could someone please help me out here?

Thank You,

Kal.

![image](https://cloud.githubusercontent.com/assets/27441481/25017311/43a38e6c-2051-11e7-8e16-a0ae01e5e5c6.png)

**Comment by chriswmackey** [comment]
@apalapa86 ,
This happens because your Rhino model units are likely not set to meters.  Change the Rhino units to meters, recompute your GH canvas, and the windows should be sized correctly.  If this doesn't fix it, upload your .gh file and I'll see if I can re-create the issue on my end.
-Chris

**Comment by apalapa86** [comment]
Chris,

Again thank you for responding. I guess I asked the same question on Youtube, and you helped me out there. And it did fix it!

Warm Regards,

Kal.

**Comment by chriswmackey** [comment]
Ah, good to hear. I'm closing out the issue, then.
