### ISSUE TITLE
Issue with Energy+ Model wHVAC using Ideal Air Loads and Microclimate Maps

### ISSUE THREAD

**Issue by jankiv** [mostaphaRoudsari/honeybee#623]
I've set up an energy model for an interior space to a building with three zones. Two perimeter and one core. Side walls, ceiling and floor are adiabatic and the energy simulation is set to run with ideal loads. When I run the energy model and use the results to create an annual microclimate map, the temperature range that I see are much lower than the setpoints in my model as if ideal loads are not modelled. It's possible I did not set the model up correctly using systems. If anyone has time to take a look at my script I would greatly appreciate some feedback! See attached. The results files were to big to attach here but if you run for a single day in the winter you will see that the air temperature results are much colder then the system setpoint. 
[Upload to GitHub.zip](https://github.com/mostaphaRoudsari/honeybee/files/945172/Upload.to.GitHub.zip)

**Comment by jankiv** [comment]
Okay so I've been troubleshooting this further and I think I might have identified the culprit. I used the set to adiabatic surfaces prior to creating an HBzone. Once the zone is created and I check attributes for the zone boundary condition, the surfaces are still reading as outdoors. Could this be a bug? 

![image](https://cloud.githubusercontent.com/assets/25178111/25286813/123fa7c4-268d-11e7-921e-5f0fe6c644ce.png)

![image](https://cloud.githubusercontent.com/assets/25178111/25286796/fd205794-268c-11e7-8a11-5dcca1d903f5.png)

**Comment by chriswmackey** [comment]
@jankiv ,
Thank you very much for finding and reporting this bug.  I have just fixed it:
https://github.com/mostaphaRoudsari/honeybee/commit/59724c5dda0dd1964619303e7382b725401bb144
I had overlooked this one and I usually set surface boundary conditions on the createHBSrf component rather than using the MakeAdiabatic component.

If you sync your components with the github, everything in your file should work correctly now.
-Chris

**Comment by jankiv** [comment]
Hi @chriswmackey Thanks for looking into this! I updated the file on my end, but I think in doing so I crashed something else. I've been troubleshooting it for 2days/3 nights now. It works once when I run the microclimate map using HOY but when I plug in an analysis period and let it run overnight it freezes and crashes. Errors are shown below. I then have to reconnect all the panels, replace some of them and rerun. 

The error I am getting says the comfort recipe doesn't have any surface temperatures in the CSV file but they are there. I am able to read annual values for both indoor and outdoor temperatures for all 29 surfaces in the zone.
Any guess as to what the problem can be? I'm guessing it has something to do with the output of the comfort recipe. 

**ERROR** 
![image](https://cloud.githubusercontent.com/assets/25178111/25485808/2ef4a122-2b2d-11e7-942e-9bbcefb9e372.png)

**ENERGYPLUS OUTPUT**
![image](https://cloud.githubusercontent.com/assets/25178111/25486587/a3d66ff0-2b2f-11e7-9f3d-e32d288ffd3d.png)
![image](https://cloud.githubusercontent.com/assets/25178111/25486569/9ac4b782-2b2f-11e7-8833-8bddecdf731d.png)

**COMFORT RECIPE**
![image](https://cloud.githubusercontent.com/assets/25178111/25486612/b975b69a-2b2f-11e7-8ac4-46fbd38c8fea.png)
![image](https://cloud.githubusercontent.com/assets/25178111/25486621/c1227c16-2b2f-11e7-9673-35bc3f5a6319.png)
