### ISSUE TITLE
OpenStudio Glazing U value setting error

### ISSUE THREAD

**Issue by MingboPeng** [mostaphaRoudsari/honeybee#625]
Hi Mostapha,

It seems there is a problem of exporting glazing material to openstudio. I checked the simulation results that ran from grasshopper and OpenStudio, their final results matches, so I assuming this is not set correctly in "exportToOpenStudio". 

![image](https://cloud.githubusercontent.com/assets/9031066/25870891/bde069c0-34d3-11e7-9eac-b52ef08e2aaf.png)

![image](https://cloud.githubusercontent.com/assets/9031066/25870835/8ffde654-34d3-11e7-8d97-b0a2fe4352f6.png)

**Comment by chriswmackey** [comment]
@MingboPeng ,
I use this feature all of the time and see changes in the results with different U-Values.  Otherwise, I would not be able to run Design Explorer studies like this one:
http://tt-acm.github.io/DesignExplorer/?GFOLDER=0BwESNksS3Eucbm5raV85eVFQMlk
It must be something different with your grasshopper file.  Could you post a link to your GH file that is causing this issue?
-Chris

**Comment by MingboPeng** [comment]
Hi @chriswmackey ,

I just recreated a example, it is still the same. please find the attached zip file (GH and osm file)
[OpenStudio.zip](https://github.com/mostaphaRoudsari/honeybee/files/989788/OpenStudio.zip)

Thanks,
Mingbo

**Comment by MingboPeng** [comment]
@chriswmackey  I think this might because of the newest OpenStudio 2.1.

**Comment by chriswmackey** [comment]
@MingboPeng ,
I know what's happening.  A U-Value of 1.25 (IP) is a higher U-Value than a single pane of glass.  OpenStudio must be trying to correct for such an input that would violate laws of physics.  

You should set it to something more realistic like 0.4 (standard double pane) or 0.25 (standard triple pane).  For example, when I set it to Triple pane (0.25), everything works correctly:
![image](https://cloud.githubusercontent.com/assets/5567574/25974126/3fb6094e-3675-11e7-8833-3b1b6d83a871.png)

-Chris

**Comment by MingboPeng** [comment]
@chriswmackey  ha, thanks, and I found that OS accepts max UValue(IP) 1.232771, and also someone says EnergyPlus cannot model more than 5.8 W/m2-K (IP:1.02).  [https://unmethours.com/question/890/openstudio-u-factor-maximum-value-for-simple-glazing/](url)

The reason I was using 1.25 IP is because of modeling a "poor performed" existing building.

Good to know this, thanks again.
Mingbo

**Comment by chriswmackey** [comment]
@MingboPeng ,
Thanks for finding this limit.  I have added a warning to the EnergyPlus Window Material component that alerts people when they pass this acceptable limit:
https://github.com/mostaphaRoudsari/honeybee/commit/7ff72f1abf12760207ed2fa8c6c0932be307a710
Thanks again!
