### ISSUE TITLE
Dividing honeybee?

### ISSUE THREAD

**Issue by arkdanielnielsen** [mostaphaRoudsari/Honeybee#64]
Now, when there is so many components under Honeybee would it be a idea to split the group in two; one for daylighting and a other for energy?

**Comment by mostaphaRoudsari** [comment]
@arkdanielnielsen we are going to do it! It is getting so big now and we agree that it is better to create three separate tabs for Ladybug and Honeybee! We made a new issue to it stays on top of the list: https://github.com/mostaphaRoudsari/Honeybee/issues/242
