### ISSUE TITLE
rotateHBObj not working when angle == 0

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/honeybee#643]
Hi,
The rotateHBObj returns Null geometry when the rotation angle is 0.
Suggest to fix as follows (line 105):
if _HBObj and _angle != None:

Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
I agree with your suggestion and I'll try to implement it soon. For now, you can input 360 for a non-rotated zone output if you need this for parametric studies of rotated models.

**Comment by mostaphaRoudsari** [comment]
To be the [PEP8](https://www.python.org/dev/peps/pep-0008/) police here it's recommended to use `_angle is not None` when checking a None value. 🚥

**Comment by chriswmackey** [comment]
Thank you PEP8 police!
That was definitely the cleanest way to solve the issue.
Closed!
https://github.com/mostaphaRoudsari/honeybee/commit/5485041c450f592a421caa4cf57d85af45aad4cf

**Comment by ayezioro** [comment]
Thank you officer @chriswmackey and officer @mostaphaRoudsari 
Citizen -A.
