### ISSUE TITLE
Honeybee Transform Components Should Transform the E+ Daylight Control Sensor

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/honeybee#645]
I just woke up this morning and realized that, if you assign an E+ daylight control sensor to a zone and then transform it, the zone will be transformed but the sensor will remain where it was.  This is a quick fix that I would implement shortly.

In the meantime, hopefully users transform their HBObjects before applying daylight control sensors with the "Set Zone Thresholds" Component.

**Comment by ayezioro** [comment]
Hi @chriswmackey,
Don't know where my head is but i opened yesterday an issue exactly about this and didn't noticed that you already did it. Sorry. I'll close it.
If this is interesting this is how i solved the issue for now:
![29302855-69060a04-8190-11e7-8ed0-d5dc4ff9f99d](https://user-images.githubusercontent.com/7526023/29350434-45b81a38-8267-11e7-8829-e31c3b0fde72.JPG)

At the final stage, before simulation, i array the sensor location.
Checking the idf i see they are well located.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
I had a feeling that you would be the first one to recognize this issue in your workflows :). I'll move this to the top of my agenda since it's such a quick fix anyway. I'll post back here sometime before the end of today.
-Chris

**Comment by chriswmackey** [comment]
@ayezioro ,
This is now fixed:
https://github.com/mostaphaRoudsari/honeybee/commit/c53796be02ff28560f32603a89b6d6e5b4c49d4d
Thanks for providing the motivation to fix this one more quickly :)

**Comment by ayezioro** [comment]
Thanks @chriswmackey,
Works like a char.
All those transformation components are vital, i would say.
Glad to be the trigger.
-A.
