### ISSUE TITLE
Honeybee Daylight simulation error- rotating the scene

### ISSUE THREAD

**Issue by IanChaplin** [mostaphaRoudsari/honeybee#646]
Running the honeybee_run_daylightsimulation component only works when not rotating the scene (see, img 1 vs 2); both when using a vector or with a number to rotate the scene . A work-around is using the HB_rotateHBObj ( img 3: as mentioned by Abraham Yezioro) 

![no rotation of the scene](https://user-images.githubusercontent.com/30826498/29065665-687877c4-7c5f-11e7-9b02-6fcc4eba36d6.jpg)
![rotate scene 180 degrees](https://user-images.githubusercontent.com/30826498/29065664-68760778-7c5f-11e7-8536-a37712c36dca.jpg)
![capture](https://user-images.githubusercontent.com/30826498/29065713-85e742ae-7c5f-11e7-9dd1-fba8f5d31d4b.JPG)

**Comment by chriswmackey** [comment]
This has been fixed via https://github.com/mostaphaRoudsari/honeybee/commit/c551c322430fc0d5f6bf9b9cbfad9a1a62cc688e
