### ISSUE TITLE
Multiple CPU causing errors (Radiance)

### ISSUE THREAD

**Issue by LudvigHaav** [mostaphaRoudsari/honeybee#647]
This is a copy of the issue here: 

[http://www.grasshopper3d.com/group/ladybug/forum/topics/multiple-cpu-causing-errors-radiance]

I thought it might be best to have the issue dealt with here, since I suspect a bug and there has been slow response in the GH forums and it might get lost in the flood of questions.

/ Ludvig

**Comment by chriswmackey** [comment]
@LudvigHaav ,
As you saw, I provided a response on the GH forum. It might be a bit though to fix given that we're not easily able to recreate the error on our machines.  Just a thought: have you tried re-importing the results using the "Honeybee_Lookup Daylight Folder" and checking to see if they are still in the worng order?
![image](https://user-images.githubusercontent.com/5567574/29419049-13a3a3fc-833c-11e7-8f6e-e934c8c0da38.png)

-Chris

**Comment by chriswmackey** [comment]
I'm closing out this issue due to inactivity and because no one was able to recreate it except for @LudvigHaav .  If the issue still persists, @LudvigHaav , feel free to let us know and we will reopen the issue.
