### ISSUE TITLE
View factor - Transparency schedule for outdoor calculation

### ISSUE THREAD

**Issue by NallaV** [mostaphaRoudsari/honeybee#648]
Hello there,

I am trying to run a UTCI calculation through Honeybee and I wanted to take into account the trees. I built a schedule of transparency for the trees that varies between different seasons, which I used in the E+ calculation, but I cannot use the same schedule in the ViewFactor component. It may be an "overkill" to implement transmittance schedule for the trees in the Viewfactor but I am still wondering if it is even possible.

The component's description says that you can input a list of values as a transmittance schedule for the shading elements. However, when I do so, the MicroclimateMap component throws an error. I checked where the error appeared and it was in the script lines where the component tries to implement the transmittance schedule. If I have single transmittance values instead of a schedule, it works fine. So, is the transmittance schedule available only for interior view factor calculations? 

Thank you!

**Comment by chriswmackey** [comment]
@NallaV ,
Yes, this is possible, although it requires the use of Grasshopper data trees, which are one of the more difficult concepts to understand in Grasshopper.  Here is an example file that shows how to do it:
https://www.dropbox.com/s/j31b3ojpp4rsggx/Trees_in_Outdoor_Thermal_Comfort_ANNUAL.gh?dl=0
-Chris

**Comment by NallaV** [comment]
Thank you for the reply Chris. This is exactly what I did. I added the schedule as a tree. Around 500 branches, first 35 with the schedule for the 35 trees and the rest with 0 values for the opaque surfaces. I will try again and probably upload my script so you can have a look if you have time.

**Comment by chriswmackey** [comment]
@NallaV ,
Make sure that the input for transmittance into the view factor component is not flattened.  In the future, I'm thinking of just having people plug in context  surfaces and read their respective transmittance schedules so that you don't have to create these data trees with 500 branches.  Would that have made things easier on your end?

**Comment by NallaV** [comment]
Yes! this would definitely make things easier. Thank you Chris!
