### ISSUE TITLE
Microclimate map - Wind speed as csv

### ISSUE THREAD

**Issue by NallaV** [mostaphaRoudsari/honeybee#651]
Hello there!

I have been trying to run a UTCI calculation through the OutdoorComfRecipe+MicroclimateMap components. I tried to add windspeed into the comfort recipe as a csv and I get the error "The calculation has been terminated by the user!" in MicroclimateMap. The csv has 8760 rows and same columns as the test points.

So here is the grasshopper file and the csv file. Maybe someone can help me with it!

I also had problems with the transparency schedule for the trees. I haven't been able to resolve it yet (#648). The error with the wind speed appears when I use single values for transparency. Otherwise I get different errors. Maybe someone would like to check this as well.

[Microclimate.zip](https://github.com/mostaphaRoudsari/honeybee/files/1244745/Microclimate.zip)

**Comment by chriswmackey** [comment]
@NallaV ,
Your number of test points is 9216:
![image](https://user-images.githubusercontent.com/5567574/29643000-0e663938-883a-11e7-9032-825bdc86c45c.png)

The number of columns in your excel is 1024:
![image](https://user-images.githubusercontent.com/5567574/29643022-2c49463e-883a-11e7-82df-f94c79a4f487.png)

This is why your file is not running. On a side note, you should break up the ground surface if you want to model the thermal diversity in surface temperature from the neighboring building's shadows.

**Comment by NallaV** [comment]
Thank you Chris! 

This is weird. Maybe something went wrong in the conversion from xlsx to csv since I checked multiple times the number of points. Did you get the error with the transparency or is it only me?

P.S. Thanks for the tip! I was indeed planning to divide the ground in pieces to get a better effect from the shadows after I make sure everything else goes smoothly!
