### ISSUE TITLE
Search across Ladybug & Honeybee

### ISSUE THREAD

**Issue by devngc** [mostaphaRoudsari/honeybee#655]
Hello Everyone,

[Some Background]
Usually, you when you're looking up code inside a component, You want to look up a function from Ladybug_Ladybug or Honeybee_Honeybee, and so you find that function in Ladybug_Ladybug or Honeybee_Honeybee. It's straightforward.

Recently, while working on a component, I found myself in a reverse situation. I knew a function in Honeybee_Honeybee and I had to find all the components using it. Therefore, I wrote a few lines to look through all the .Py files in C:\ladybug\honeybeeSrc\honeybee-master\src to get the only files using the function I was looking for.
[End of Background]

While doing this, it occurred to me that we can do something similar to perform a keyword search through all Ladybug and Honeybee .Py files.
![rainman](https://user-images.githubusercontent.com/20086924/30034374-877da08a-91be-11e7-988b-b82cadb4a54a.jpg)

In the image above, you can see what happens when you search for "Drybulb." The native GH search is not very helpful. 

I am proposing we have a component that 
1. Looks through the args, returns, and description of all the components
2. Ranks them based on hits 
3. Returns a list of the names of the components.

What you see in the image is really primitive. I believe I can refine the results to be more specific. The idea is to receive a list of components that deal with (Either takes it as input or outputs it) the query (keyword).

I am raising this issue to trigger a discussion. **I would be very glad to hear your thoughts on whether this should be a part of Ladybug Suite.** 

Thank you!
Devang

**Comment by devngc** [comment]
[Note to self] Honeybee_Honeybee or Ladybug_Ladybug must not be a part of this list.

**Comment by sariths** [comment]
Hi @devngc , just out of curiosity, which IDE do you use for Python?

**Comment by devngc** [comment]
Hi @sariths,
I generally use  Atom editor, but for LB / HB development, I code inside the Python component in Grasshopper. If there's a better way, then I would love to hear about it. I read somewhere that it is possible to import Rhino libraries in Atom. I haven't tried that yet.
Thanks,
Devang

**Comment by sariths** [comment]
Mostapha and I were discussing this earlier today (after seeing your post). I am not sure if this possible in Atom, but in Pycharm it is possible to locate (almost) all instances of usages through built-in functionality. Here is a HB example:
![selection_021](https://user-images.githubusercontent.com/10361848/30046264-0bdc7d46-91cf-11e7-9b9d-8118b5fb4928.jpg)
The logic inside Pycharm is mature enough to discriminate between docstrings, comments and actual code. I am not sure if similar functionality exists in Atom. Anyway, if you are used to coding in Atom, I won't suggest switching.

**Comment by devngc** [comment]
@sariths,
Thanks for sharing this native capability of Pycharm. I was not aware of this. Pycharm is indeed great IDE.  I used it when I was learning to code. 

The component I have in mind is for the users of the tool and not the developers. I believe we can offer a list of components that deal with the query the user provides.

Again, thank you for sharing and participating!

**Comment by Vyrwn** [comment]
@devngc ,

I find this idea very interesting and handy especially for students, getting started. Being able to find all the relevant components to a key word or phrase is a useful addition. Even myself after all this time of following development and using LB/HB, I found out about a couple of components by accidentally typing :)

I agree pycharm is extremely strong and if you have any university affiliation you can go for the full version. I do find atom though much more customizable and responsive. IDE though is usually a very personal thing.

**Comment by devngc** [comment]
Hi @Vyrwn,

I totally understand when you say you found a new component by accidentally typing. It happens with me as well. LB / HB overwhelms me too.

Thank you for sharing your thoughts!

**Comment by Vyrwn** [comment]
@sariths,

Updating my last comment, the last 2 days I worked only on Pycharm to give it another go and I have to agree that it has amazing capabilities, also the ease of the git push is great compared to the atom one.

**Comment by sariths** [comment]
Hi @Vyrwn, 

On the issue of licenses, actually I use both the Enterprise version (thanks to my concurrent .edu status!) and Community version of Pycharm. For the most part, I don't find much of a difference in my productivity except for one critical aspect: the Enterprise version has amazing SSH and Cloud (mostly remote browsing and terminal related)support. Here is an example of that: 

![2017-09-07 10_48_11-presentation1 - powerpoint](https://user-images.githubusercontent.com/10361848/30172311-20007484-93ba-11e7-9eb3-563b0d61094a.png)

(Apologies to Devang for somewhat hijacking this thread with Pycharm PSA. This is the last off-the-topic comment from me !)

**Comment by devngc** [comment]
[This](https://github.com/devngc/Work-in-Progress/blob/master/Rainman/Rainman.gh) is what I have in mind. Currently, the search is limited to one keyword. But I agree with @Vyrwn's idea and eventually, the component should accept phrases as well.

**Comment by Vyrwn** [comment]
@devngc,
I gave it a go and worked like a charm. And it is very useful in my opinion. My only worry is how to make people aware of the search component. It is a sort of a loop, know how to find the component that will search everything else :), but that might be me over-complicating things. 

Very nice work anyway. 
Thanks for this.

**Comment by devngc** [comment]
Thank you @Vyrwn for review and encouraging words! A way get it noted will be to put it in 0 | Ladybug or to have a very obvious logo for the component. The magnifying glass.

**Comment by chriswmackey** [comment]
@devangc ,

Sorry for the late reply on this. I will admit that the use of this component seems to be a bit redundant of github's "Search this Repo" functionality that you can probably see at the top of this web page (or at the top of any github repo homepage).  I am usually using this github feature to find all of the components that reference a certain function.

It's also perhaps a bit redundant of our Ladybug Primer and Honeybee Primer, which were set up to allow you to search through all of the component descriptions.

Still, this might be useful for some situations where someone needs to search offline so, if you send a pull request to the WIP section, I'll merge it in. For best practices about how to build a search component I would encourage you to check out Honeybee's searchListByKeyword function.

-Chris

**Comment by devngc** [comment]
Hi @chriswmackey,

Thank you for sharing your thoughts. Always appreciated.

> this component seems to be a bit redundant of github's "Search this Repo" functionality that you can probably see at the top of this web page (or at the top of any github repo homepage). I am usually using this github feature to find all of the components that reference a certain function.
> 
The targetted users of this component that I had in mind were definitely not the developers. In addition to what you suggest, I found a native feature in Atom to look up multiple files [This I found after reading Sarith's posts]. 

> It's also perhaps a bit redundant of our Ladybug Primer and Honeybee Primer, which were set up to allow you to search through all of the component descriptions.
> 
I completely missed this. This is exactly why I sought your review. This makes more sense.

> Still, this might be useful for some situations where someone needs to search offline so, if you send a pull request to the WIP section, I'll merge it in.
> 
Considering the redundancy, I am hesitant to push this component. Let's see if we receive some more feedback.

Thank you for your time!
-Devang

**Comment by chriswmackey** [comment]
@devangc ,

Yes, I'm sorry that I didn't post the feedback sooner. I had also wanted to take the time to understand what the setup you are using. Now that I see that the user needs to have the py files available on their machine, I'm also hesitant about how many people we will get using it. I feel that many users are still unaware of the Primers (this github issue is perhaps a case-in-point) and so anything we can do to make people aware of them (or of general component search capabilities) is helpful. This said, I'm wondering now if it's not more helpful to make a component that automatically opens the Primers in a browser (much like the download epw component).

Let me know your thoughts.

**Comment by devngc** [comment]
@chriswmackey,

I like the idea of opening primer pages from GH and am willing to explore this. The primary advantage of doing this is that I no longer have to separate component information [Description + Args + Returns] from code. This is something I was doing.

Yes, download epw is a good example for opening web pages from GH. I believe I should also look at update components and/or hydra components to access files on GitHub.

Thank you for sharing your idea!
-Devang

**Comment by devngc** [comment]
I will re-open when I get around to implement this.

**Comment by chriswmackey** [comment]
Sounds good @devngc . Thanks, as always!

**Comment by devngc** [comment]
> This said, I'm wondering now if it's not more helpful to make a component that automatically opens the Primers in a browser (much like the download epw component).

@chriswmackey,
This [PR](https://github.com/mostaphaRoudsari/ladybug/pull/437) is made in compliance with your comment.

**Comment by chriswmackey** [comment]
Thanks again, @devngc .  This component is really helpful.
