### ISSUE TITLE
solution exception: index out of range 1

### ISSUE THREAD

**Issue by zhangzhennico** [mostaphaRoudsari/honeybee#656]
I have an issue "solution exception: index out of range 1" when I try to run the open studio energy simulation to calculate indoor PMV comfort. and I check all the components and still can not find the reasons. Could you help me check it?
Many thanks for all your help and my definition is attached with this issue post.
![screenshot 4](https://user-images.githubusercontent.com/26587689/30192708-a4b0fd36-947b-11e7-83aa-b3bae5682870.png)

**Comment by devngc** [comment]
@zhangzhennico,
I don't see your definition. Can you please re-attach. I can take a look.

**Comment by zhangzhennico** [comment]
[VERNACULAR PROTOTYPE_B_Indoor_PMV_Comfort.zip](https://github.com/mostaphaRoudsari/honeybee/files/1314696/VERNACULAR.PROTOTYPE_B_Indoor_PMV_Comfort.zip)

**Comment by chriswmackey** [comment]
@zhangzhennico ,
You did not intersect your zone masses before turning them into HBZones and one of your zones had an interior surface inside of it.  Please watch all of the tutorial videos on the geometry rules of E+ before posting to any forum:
https://www.youtube.com/watch?v=cDvBWDA0aF0&index=10&list=PLruLh1AdY-SgW4uDtNSMLeiUmA8YXEHT_

Also, in the future, issues like this that aren't bugs in the software should be posted to the [Forum]() after you have searched the discussions there to see if your issue has already been addressed:
http://discourse.ladybug.tools/
-Chris
https://www.dropbox.com/s/qrc7i0mcw65jf3h/VERNACULAR%20PROTOTYPE_B_Indoor_PMV_Comfort_CWM.gh?dl=0

**Comment by zhangzhennico** [comment]
Noted, many thanks for all your help.
