### ISSUE TITLE
makeAdiabatic -  global name 'srfType' is not defined

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/honeybee#664]
Hi,
Using the makeAdiabatic component i've found this error:

> Runtime error (UnboundNameException): global name 'srfType' is not defined
> Traceback:
>   line 51, in changeSrfType, "<string>"
> 

![capture](https://user-images.githubusercontent.com/7526023/32615995-e6461acc-c579-11e7-8247-da01459ed694.JPG)

So the srfType is not defined in the code.
I fix the code like this, but i'm not sure if this is OK as a solution to be implemented for the component (the original code is commented). The above image shows the fixed and the original in red.
```
def changeSrfType(HBSurface):
    #if srfType == None and str(HBSurface.type).startswith('2'):
    #    HBSurface.setType(2, False)
    #elif srfType == None and str(HBSurface.type).startswith('1'):
    #    HBSurface.setType(3, False)
    if str(HBSurface.type).startswith('2'):
        HBSurface.setType(2, False)
    elif str(HBSurface.type).startswith('1'):
        HBSurface.setType(3, False)
    HBSurface.setEPConstruction(HBSurface.intCnstrSet[HBSurface.type])

```
Thanks,
-A.

**Comment by MingboPeng** [comment]
This happens in makeAdiabaticByNames as well.

**Comment by chriswmackey** [comment]
@ayezioro  and @MingboPeng ,

Thank you for finding this and this one was definitely my fault:
https://github.com/mostaphaRoudsari/honeybee/blame/master/src/Honeybee_Make%20Adiabatic.py#L50

I must have copy/pasted this code from elsewhere where there was another variable called srfType.  I have just fixed it and you assumption was correct, @ayezioro 
https://github.com/mostaphaRoudsari/honeybee/commit/6d701aba2bf244172545fa42d0be972b8987f259
