### ISSUE TITLE
Window Shade Generator- number of Shade

### ISSUE THREAD

**Issue by anupamarana** [mostaphaRoudsari/honeybee#665]
Hi
I am trying to generate various shading options and compare EUIs. 
It works fine for all other iteration, except for below
- with one horizontal shade 
- with all numbers of vertical shades

for above two condition the window / wall tend to disappear prompting error " All of your HBSrfs must make a closed volume." in Create HBZone component. 

I have attached my GH file. and pictures showing error.
Looking forward to hear soon.
Best Regards
Anupama

**Comment by anupamarana** [comment]
![error-1_](https://user-images.githubusercontent.com/31266576/32829573-664f0b18-ca2d-11e7-9fc2-ecaa5050aa62.PNG)
![error-1](https://user-images.githubusercontent.com/31266576/32829566-6071f692-ca2d-11e7-9221-658c8c3c613d.PNG)

**Comment by anupamarana** [comment]
Link for GH file is here

[https://www.dropbox.com/s/n1ii9gkqaihpgd5/Overhang.gh?dl=0&m=](url)

**Comment by saeranv** [comment]
@anupamarana your link doesn't work. Maybe post it on the discourse forums? Should be easier there.

**Comment by anupamarana** [comment]
https://www.dropbox.com/s/n1ii9gkqaihpgd5/Overhang.gh?dl=0

**Comment by anupamarana** [comment]
Hi Saeranv
The link above shoul work now. 
Thank you for your prompt response.
Best Regards
Anupama

**Comment by anupamarana** [comment]
![error-1](https://user-images.githubusercontent.com/31266576/32867878-8b5e12f0-caaa-11e7-83cd-5ebb26d90dcc.PNG)
![error-1_](https://user-images.githubusercontent.com/31266576/32867883-960c0b58-caaa-11e7-8e48-bc4ed07d0803.PNG)

**Comment by devngc** [comment]
[This](https://www.dropbox.com/s/n6u27sf6rafa4gs/Overhang.gh?dl=0) is one way to do it. As Saeran said, it's better to post such questions on the forum please.

**Comment by anupamarana** [comment]
Hi
With Archsim create zone and energyplus components it works, but not with honebee create zone and energyplus component.
Best Regards
Anupama

**Comment by anupamarana** [comment]
Thank you Devngc
I have just send request to get accepted into the honeybee/ladybug discourse forum

**Comment by devngc** [comment]
@anupamarana,
Although both use the same calculation engine, the workflow for setting up a simulation may not necessarily be the same. In case you want to familiarize yourself with energy modelling routines for Honeybee, I would recommend you go through the Honeybee Energy modelling Tutorial series on Youtube from Chris Mackey.

**Comment by chriswmackey** [comment]
@anupamarana ,

The reason why you don't get EPObjWShades is that, when you only have a single overhang (not a set of horizontal louvers), you really should not be using a ["blinds" or "louvers" approximation](https://bigladdersoftware.com/epx/docs/8-7/input-output-reference/group-surface-construction-elements.html#windowmaterialblind), which is what gets assigned to the HBObjWShades by the component when you have multiple shades.

Instead, for your case here, you should just use the output shade geometry and plug it into an EP Context component like so:
![overhang workflow](https://user-images.githubusercontent.com/5567574/32895533-5c5b2dae-caae-11e7-8e4a-9f7f3acb5f92.PNG)
You will also see in the image that the readMe! of the Shade Generator component (circled in red) is telling you to use this workflow.

https://www.dropbox.com/s/4b8ukw98dkdlsoe/Overhang_CWM.gh?dl=0
-Chris

**Comment by anupamarana** [comment]
Thanks chris for the clarification.
