### ISSUE TITLE
Mass2Zones input geometries have same key as output geometries

### ISSUE THREAD

**Issue by saeranv** [mostaphaRoudsari/honeybee#666]
From this thread: http://discourse.ladybug.tools/t/askme-component-showing-zone-info-not-connected-to-it/2261/8

Which is causing some UI confusion. 

Is the solution to this simply one line?  
```
_zoneMasses = copy.deepcopy(_zoneMasses) 
```

**Comment by mostaphaRoudsari** [comment]
Yes. That will be the solution.

**Comment by saeranv** [comment]
Okay, I can fix this and submit the PR then!
