### ISSUE TITLE
Honeybee - Issue with orientation of walls using HBTransformation components

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/honeybee#672]
Hi,
I was in doubt if re-opening [this issue](https://github.com/mostaphaRoudsari/honeybee/issues/615) or opening a new one. Though it is related, it doesn't fit the title of the issue.
So here it is: For my class i prepared i file that wanted to demonstrate the advantages of defining a single zone and then copying it with the HB transformation components.
Everything works fine but ... when i added windows with the glazingCreator (say 0.2, 0.2, 0.4, 0.2, meaning 0.4 for south facades), the transformed window geometry was set wrong. Seems to be that the facade orientation is not updated with the transformation and then the glazingCreator fails in assigning the right size for each facade. See image below.

![capture](https://user-images.githubusercontent.com/7526023/33901200-b7d21122-df79-11e7-82b9-82cfd26516a3.JPG)

Look at [this file](https://www.dropbox.com/s/j6jot0tn48i0wdv/HB_Transformations_WindowIssue.gh?dl=0). For specific reasons i need to apply the solveAdjacencies twice. I ask for the glazingCreeator just after that.

Any ideas?
Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
Thanks for finding this issue.  It definitely looks like a bug and I will check it as soon as I can.

**Comment by chriswmackey** [comment]
@ayezioro ,
Excellent work finding this.  It seems there was one final bug t be fixed in the transform code:
https://github.com/mostaphaRoudsari/honeybee/commit/fe45010a0d7ddb78e8bb7ea1f1fe934a35657cc5
It all works correctly now:
![image](https://user-images.githubusercontent.com/5567574/34051556-0d740634-e18d-11e7-8fff-ebf8a02d8f4d.png)

Thanks again!
-Chris

**Comment by ayezioro** [comment]
Thank YOU @chriswmackey !!
