### ISSUE TITLE
Honeybee_IES Luminaire

### ISSUE THREAD

**Issue by eddiespaghetti187** [mostaphaRoudsari/honeybee#675]
This component seems to generate an error message ("1. Solution exception:Local variable 'dirpath' referenced before assignment.") related to folder paths when the radiance folder doesn't exist. Similar components seem to create the folder if they don't already exist. Is it possible to update this component to do the same?

**Comment by chriswmackey** [comment]
@eddiespaghetti187 ,
Yes, I'm sure that we can add something here to create the directory. Can you let me know what line of the code in the component the error is occurring on? This should be output in the ReadMe of the component.

**Comment by eddiespaghetti187** [comment]
Cheers Chris. Full output from the component below. 
```
Runtime error (UnboundLocalException): Local variable 'dirpath' referenced before assignment.
Traceback:
  line 672, in fixIesFile, "<string>"
  line 687, in script
```
Thanks,
Ed

**Comment by chriswmackey** [comment]
@eddiespaghetti187 ,
This has been fixed:
https://github.com/mostaphaRoudsari/honeybee/commit/9d0a9131570878dd2435b755b9bee2e66b177ad9
Thanks for bringing this to our attention!
