### ISSUE TITLE
IntersectMasses fails after the new fix for Rhino 6

### ISSUE THREAD

**Issue by mostaphaRoudsari** [mostaphaRoudsari/honeybee#681]

**Comment by chriswmackey** [comment]
This has been fixed via https://github.com/mostaphaRoudsari/honeybee/commit/256ca5c23265d9b47d5ea96a42462b7502b6e91a

I tested the new component in a lot of cases with both curved and planar geometry and up to 100 zones. I could not get it to fail so it seems that this newer component finally has the reliability of the older one.
