### ISSUE TITLE
forced natural ventilation - schedule shorter timestep

### ISSUE THREAD

**Issue by dbriels** [mostaphaRoudsari/honeybee#689]
Hello everyone!

First of all: standing ovations for the ladybug tools team. Thanks a lot!

At the moment I´m working on simulations of prototypical climbing halls espacially regarding the natural ventilation. Therefore I wanted to test a forced natural ventilation (because some climbing halls are using this at the moment) where the openable windows open with a certain time schedule. I was thinking about using the openingAreaFractionalSched from Set EP Air Flow. The problem is, that I want to open the windows for max. 1 minute and not a whole hour.

Is it somehow possible to create a schedule for every minute? Or does someone has another idea to implement this?

I tried it to Create CSV Schedule with 35040 values which doesn´t work.

Thanks a lot!

**Comment by mostaphaRoudsari** [comment]
Hi @dbriels. Thank you for the kind words. This is a question and not a bug report and should be posted to the forum. See here: http://discourse.ladybug.tools/t/welcome-to-ladybug-tools-forum/8
