### ISSUE TITLE
Holidays not working for simulation

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/honeybee#690]
Hi,
I updated a file that was working a couple of months ago.
When  try to run the _HB_OS complains about:

> 1. Solution exception:E:\Git\OS1\openstudiocore\src\model\RunPeriodControlSpecialDays.cpp@245 : '' is not correctly formatted

I input the holidays as a list of dates to the HB_EnergySimPar (also tried as a list of DOYs). When i disconnect the list it works fine.
So i assume that in the process of updating the last HB_OS something get unsync with this issue.

![capture](https://user-images.githubusercontent.com/7526023/39738461-f73ee636-5293-11e8-8a78-5759fdb695ef.JPG)

As you can see, the top case has the list attached (not working) and the bottom one hasn't (works).

Can you help?

Thanks,
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
I'll take a look as soon as I get the chance.

**Comment by ayezioro** [comment]
Thanks @chriswmackey,
No rush. Luckily i can run with R5.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
I am not able to recreate the issue on my end.  Could you share a file that recreates the issue?  Also, what version of Rhino 6 are you using?  Is it an experimental version like the one mentioned here?
https://discourse.ladybug.tools/t/rhino-6-and-honeybee-intersect-masses-issue/2650/24
-Chris

**Comment by ayezioro** [comment]
Hi @chriswmackey,
I'm using 6.3.18090.471, 03/31/2018, which is the most official release.
Attached the Rhino and GH files.
Thanks,
-A.
[HolidaysIssue.zip](https://github.com/mostaphaRoudsari/honeybee/files/1986278/HolidaysIssue.zip)

**Comment by chriswmackey** [comment]
@ayezioro ,
The issue was that you had two empty strings at the end of your list of holidays:
![image](https://user-images.githubusercontent.com/5567574/39819602-d26673ea-5371-11e8-87fc-f83e8764cad9.png)
If you remove these, it runs fine.  I added some code to automatically remove empty strings and nulls:
https://github.com/mostaphaRoudsari/honeybee/commit/bf9af228158f09574cb17e0c98fba7d479e8af45

**Comment by chriswmackey** [comment]
It's all good! R5 must have had some means of taking the empty strings out of the list and this isn't present in R6. Now we know better about this and I'm definitely thinking of implementing some plugin wide Checks in HB+ to remove empty strings.
