### ISSUE TITLE
Honeybee addHBGlz strange bugs from R5 -> R6

### ISSUE THREAD

**Issue by mikhaildemtchenko** [mostaphaRoudsari/honeybee#692]
Windows are not being correctly added to the HBObj_ in the addHBGlz module. After some testing, the exact same model in Rhino 5 adds glazing correctly, however in Rhino 6 only adds some of the glazing. I assume this is due to the component referencing something that doesn't exist anymore in Rhino 6.

Just wanted to make you aware of this bug,
Thanks for the hard work

**Comment by mostaphaRoudsari** [comment]
@mikhaildemtchenko thanks. probably it happens for the same reasons behind this one: https://github.com/mostaphaRoudsari/honeybee/issues/691

**Comment by chriswmackey** [comment]
This has been fixed via:
https://github.com/mostaphaRoudsari/honeybee/commit/920ddf5ebf58d3ff7eae22a6059ab5937ac24eda
