### ISSUE TITLE
export to open studio not working. receiving error:cannot create a surface with vertices[...]

### ISSUE THREAD

**Issue by oscarperk** [mostaphaRoudsari/honeybee#695]
I was following a tutorial online to perform an energy simulation however it used an old version of honeybee/ladybug where the simulator automatically generated an .idf file to send to energyplus (i think). I have installed openstudio however this is the complete error i receive:

1. Solution exception:C:\Git\OS\openstudiocore\src\model\PlanarSurface.cpp@644 : Cannot create a surface with vertices [[-0.0199062, -0.010716, 0.003], [-0.0199062, -0.010716, 0], [-0.0159062, -0.010716, 0], [-0.0159062, -0.010716, 0.003]]

I have uploaded my file below so whoever can see the error.

[PROJECT.zip](https://github.com/mostaphaRoudsari/honeybee/files/2046497/PROJECT.zip)

**Comment by devngc** [comment]
You should please post on the forum for such errors. Their you can get attention of a lot of experienced users

**Comment by oscarperk** [comment]
Hello, which forum is that?

Thanks

**Comment by devngc** [comment]
discourse.ladybug.tools

**Comment by oscarperk** [comment]
Ok thank you I will try find that

**Comment by oscarperk** [comment]
Sorry devngc, I am unsure on how to create an account for discourse.ladybug.tools , cannot find a register link anywhere on the home page

Do you know how to?

**Comment by devngc** [comment]
Can you share your email id?

**Comment by oscarperk** [comment]
oscar.perkins@connect.qut.edu.au

**Comment by devngc** [comment]
Alright. I sent you an invite

**Comment by oscarperk** [comment]
Thanks for your help

**Comment by devngc** [comment]
I also checked your model. It ran without any fatal errors. please check if the unit in rhino is Meters. You can check this by typing Units in the command line of Rhino.

**Comment by devngc** [comment]
I replied to your post on the forum. I will close this now.

**Comment by chriswmackey** [comment]
Thanks @devngc for taking care of this ones and, yes I have seen people get his error a lot when they think they are working in Meters but the Rhino units are actually millimeters. I going to close this issue now that it is taken care of. Thanks again.
