### ISSUE TITLE
Have the "Read THERM Result" Component Output the UFactorLengths and the DeltaT

### ISSUE THREAD

**Issue by chriswmackey** [mostaphaRoudsari/honeybee#702]
@edpmay did a good example of this on this discussion:
https://discourse.ladybug.tools/t/using-honeybee-therm-to-calculate-psi-values/3328

The info just lives in the UFactorFile:
![image](https://user-images.githubusercontent.com/5567574/43297667-a125c7f8-9120-11e8-8e74-91cfcd8927ab.png)

... and it can be parsed in as @edpmay shows here:
![image](https://user-images.githubusercontent.com/5567574/43297654-8e33401c-9120-11e8-8212-a200ba01f673.png)

**Comment by chriswmackey** [comment]
This has been addressed via https://github.com/mostaphaRoudsari/honeybee/commit/aba3ea33c4020225a23808683b0c0c54a69898a7

**Comment by liariel** [comment]
hi chriswmackey, I'm trying to add the thermal bridge in honeybee 1.5.0, but some components can't be found.
