### ISSUE TITLE
Enhancement: Suggestions of functionalities, Honeybee - EnergyPlus

### ISSUE THREAD

**Issue by TobySkov** [mostaphaRoudsari/honeybee#703]
Hi 

I have a few suggestions of functionalities that I think could be generally helpfull:

-The Honeybee component "Honeybee_Set EnergyPlus Zone Thresholds" should when inputtet "2" in "outdoorAirReq_" write "None" in the Energyplus object "HVACTemplate:Zone:IdealLoadsAirSystem" under "!- Outdoor Air Method"; instead of writing "None" in the EnergyPlus object "DesignSpecification:OutdoorAir" under "!- Outdoor Air Method" as it does right now. This will produce the desired result without EP crashing. Example file: 
[None_example.zip](https://github.com/mostaphaRoudsari/honeybee/files/2277890/None_example.zip)

-Possibility to assign "Floor Area" in the Honeybee component "Honeybee_Set Zone Properties". 
The main motivation behind this is to raise the precision of simulations. The suggested approach to model geometry in EnergyPlus is to use centerline surface for inside constructions and outside surface for external constructions (https://bigladdersoftware.com/epx/docs/8-3/tips-and-tricks-using-energyplus/building-surface-dimensions-inside-outside.html#building-surface-dimensions---inside-outside-or-centerline). This is so to get the correct amount of thermal mass, construction surface area, window placement, etc. However the default calculation of floor area (when nothing is assigned in the EnergyPlus "Zone" object) is the total distance between the zero thickness surfaces (not accounting for the wall thickness). Then when using any form of definition by floorarea, this will introduce imprecision (for instance anything defined by the Honeybee component "Honeybee_Set EnergyPlus Zone Loads").

-Possibility of assigning "!- Frame and Divider Name" in the EnergyPlus object "FenestrationSurface:Detailed", taking input from LBNL Window, to accurately model frame and divider properties such as cold bridges around fenestrations. 

Cheers Tobias

**Comment by chriswmackey** [comment]
@TobySkov ,

Sorry for the late response but you should definitely be opening different issues for each change that you are proposing here.  I would also recommend asking if such functionality exists on the forum before opening github issues (we really want to reserve github issues for just the things that we know are either new features or bugs).

Frame and Divider objects are already supported in Honeybee.  You just need to use the ["Import WINDOW IDF Report"](https://mostapharoudsari.gitbooks.io/honeybee-primer/text/components/Import_WINDOW_IDF_Report.html) component to import a Glazing System IDF from WINDOW that includes the Frame and Divider Objects.  As long as the Frame and Divider objects are included in the IDF report that you import, they will be assigned to all constructions of the glazing system when they get exported to OpenStudio.

Overriding the floor area to not be the actual floor area of the zone has the potential to create a whole manner of confusion.  I really do not think that this property should be changed and it really doesn't seem like too much effort to do the conversions you talk about with a few native grasshopper components.  Also, the loads in the default templates have values per floor area that correspond with the suggested practice of modeling centerlines.  If you want to open another issue and make a stronger case, we will listen.

For the outdoor air requirement, this is a bug that was introduced as a result of recent changes to E+:
https://bigladdersoftware.com/epx/docs/8-9/input-output-reference/group-design-objects.html#designspecificationoutdoorair
It seems that they have done away with the old methods for setting outdoor air methods.  Accordingly, I have updated the component here:
https://github.com/mostaphaRoudsari/honeybee/commit/d7d18a80f32bfce6ce91ce0e82204b173fcf6c57
