### ISSUE TITLE
The extract time period function in the runEnergySimulation component doesn't check if the last output variable end with one of the four time period terms.

### ISSUE THREAD

**Issue by hopezh** [mostaphaRoudsari/honeybee#704]
The observation is originally posted [here](https://discourse.ladybug.tools/t/issue-with-the-extract-time-period-function-in-the-runenergysimulation-component/3648).

**1. Issue**
As shown below, in some situations, in the IDF file generated from GH+LB+HB workflow in which generator system object is created, the last output variable **_DISTRIBUTIONSYSTEM,Electric Load Center Produced Electric Energy_** is wrongly written as the following, in which the last word “Simple” should be one of the four time period words, i.e. “**hourly**”, “**daily**”, “**monthly**”, and “**annual**”.

> Output:Variable,My_PV_generator_system:DISTRIBUTIONSYSTEM,Electric Load Center Produced Electric Energy, Simple;

This could result in:
- Error while running EnergyPlus simulation through LB+HB.
- The time period of this output variable been interpreted as “hourly” by E+, rather than that been specified for the rest of the output variables through the EPOutput component.

Related discussion is shown in the following post [here](https://unmethours.com/question/33400/severe-error-failed-to-match-against-any-enum-values/) on UnmetHours.com. 

**2. Source of error**
The following function is to extract the time period from the last word of the last output variable specified by the user (### line 1926 to 1932 in the code for **runEnergySimulation, v 0.0.63, JAN_20_2018**, or **line 1937 to 1943** in the code for **runEnergySimulation, v 0.0.63, JUL_24_2018** ) :

```
   def extracttimeperiod(simulationOutputs):
        try:
            timeperiod = simulationOutputs[-1].split(',')[-1]
            HBgeneratortimeperiod = timeperiod.replace(";","")
            return HBgeneratortimeperiod
        except:
            pass
```

However, the last output variable specified by the user may not be one ended with a time period term. E.g:

> Output:Variable,*,Surface Outside Face Incident Ground Diffuse Solar Radiation Rate per Area, annual;
> Output:Diagnostics,DisplayExtraWarnings;
> Output:SQLite, Simple;

**3. Solution**
**3.1 Solution A**
Rearrange the order of the additional output variables in the GH+LB+HB workflow so that the last one is one ended with a time period:

> Output:Diagnostics,DisplayExtraWarnings;
> Output:SQLite, Simple;
> Output:Variable,*,Surface Outside Face Incident Ground Diffuse Solar Radiation Rate per Area, annual;

**3.2 Solution B**
Revise the function to loop through all output variables, and see if the last word matches one of the four time period terms (I’m sure the code can be written more succinctly):

```
   def extracttimeperiod(simulationOutputs):
        try:
            timePeriods = ['hourly', 'daily', 'monthly', 'annual']

            for output in simulationOutputs:
                endWord = output.split(',')[-1].strip().replace(";","")
                print endWord
                if endWord in timePeriods:
                    HBgeneratortimeperiod = endWord
            return HBgeneratortimeperiod

        except:
            pass
```

An example file with the code revised is attached here as reference.

Appreciate if the development team can take a look and see if the code revision is necessary.

[test_extract_timePeriod_issue.zip](https://github.com/mostaphaRoudsari/honeybee/files/2355137/test_extract_timePeriod_issue.zip)

**Comment by chriswmackey** [comment]
@hopezh ,

This has been addressed via the latest commit that I have made:
https://github.com/mostaphaRoudsari/honeybee/commit/512282195b03be6c04caf97132a2350a5b39c56a

Thank you for reporting the isssue.  You may also be happy to know that I have now moved the generation components back out of WIP and I have uploaded an updated example file here:
http://hydrashare.github.io/hydra/viewer?owner=chriswmackey&fork=hydra_2&id=Energy_Simulation_With_Photovoltaics&slide=0&scale=1&offset=0,0

**Comment by hopezh** [comment]
Dear Chris, thank you very much for the update. Can't wait to use the new generation component.
