### ISSUE TITLE
importIdf - E+V9.0 - No windows imported

### ISSUE THREAD

**Issue by ayezioro** [mostaphaRoudsari/honeybee#717]
Hi,
Trying to import an IDF i noticed that for version 9.0 the windows are not imported while for version 8.9 they are.
I know there were some formatting changes in E+ that can cause this issue.
Can you help?
An example can be found [here](https://www.dropbox.com/s/v55qhj03a20kfdw/NonCompact_01.zip?dl=0).

Thanks,
-A.

**Comment by chriswmackey** [comment]
We now know that this is just a display issue that was solved here:
https://discourse.ladybug.tools/t/missing-windows-in-idf/4876

... so I am closing out this issue.
