### ISSUE TITLE
Gendaylit Error

### ISSUE THREAD

**Issue by RMistrick** [mostaphaRoudsari/honeybee#721]
There appears to be an error in gendaylit in the calculation of skyclearness (def sky_clearness).  The equation for skyclearness (value = ) is doing integer arithmetic  when it divides (diffuseirradiance + directirradiance) / (diffuseirradiance).   If you float() either the numerator or denominator, this fixes the error.  I don't know if a similar error might be occurring in any other modules.  I believe this fix brings the solar illuminance into alignment with the Radiance gendaylit skies, which is not the case currently.

Rick

**Comment by mostaphaRoudsari** [comment]
Hi @RMistrick, This issue seems to be related to Honeybee[+]: https://github.com/ladybug-tools/honeybee/issues

Thank you for reporting the issue. This should fix it.

https://github.com/ladybug-tools/honeybee/commit/ac514d0f99bf43b5b446a1e423edb32fb583a1fa
