### ISSUE TITLE
KeyNotFoundException  when creating own HBZone geometries.

### ISSUE THREAD

**Issue by aegis1980** [mostaphaRoudsari/honeybee#723]
So, I have possibly taken a long-way-round and made my own adjacent inner and outer zones in HB. 
But I broke something. 
I get the same error if I try and run the AdjacentZones component or the ExporttoOpenStudio component:

```
Runtime error (KeyNotFoundException): 5ab0472d-1005-43c6-bd0d-4bc2a67f00de
Traceback:
  line 8385, in callFromHoneybeeHive, "<string>"
  line 5439, in main, "<string>"
  line 5663, in script
)
```

The common error is from line 8385 in callFromHoneybeeHive

 I have tried: 
- Using the Intersect masses component
- Using the same a duplicate surface object for the adjacent surface. 

Attached is the GH file. 
[help me.zip](https://github.com/mostaphaRoudsari/honeybee/files/3231278/help.me.zip)

Please help! Going crazy.

**Comment by mostaphaRoudsari** [comment]
@aegis1980,

You should post this question to the forum (https://discourse.ladybug.tools/).

To address this issue right click on canvas and select Recompute.

**Comment by aegis1980** [comment]
Thanks. WIll post on forum.
Recompute does not work.
