### ISSUE TITLE
trying to run the simulation and it keep giving me error even after updating openstudio

### ISSUE THREAD

**Issue by MalakelShorbagy** [mostaphaRoudsari/Honeybee#754]
![Untitled](https://user-images.githubusercontent.com/123310179/214021244-23640519-deb5-4ffc-8ba4-05a43f4e707d.jpg)

**Comment by mostaphaRoudsari** [comment]
Hi, @MalakelShorbagy -

1. You are using the LBT plugin and not the legacy one.
2. You should post your questions to the forum: https://discourse.ladybug.tools
3. This has been asked a few times and the error message also tells you how to fix it. Your model is most likely in meters but the Rhino units are in millimeters.

Please continue the conversation on Discourse if you have any other questions. Thank you!
